<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Data Wrangling and Preparation | An Introduction to the People Analytics Lifecycle: With Applications in R</title>
  <meta name="description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="generator" content="bookdown 0.24.4 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Data Wrangling and Preparation | An Introduction to the People Analytics Lifecycle: With Applications in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="github-repo" content="crstarbuck/peopleanalytics-lifecycle-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Data Wrangling and Preparation | An Introduction to the People Analytics Lifecycle: With Applications in R" />
  
  <meta name="twitter:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  

<meta name="author" content="Craig Starbuck" />


<meta name="date" content="2022-06-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inf-stats.html"/>
<link rel="next" href="aod.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<link href="libs/tabwid-1.0.0/scrool.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">An Introduction to the People Analytics Lifecycle: With Applications in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#guiding-principles"><i class="fa fa-check"></i><b>1.1</b> Guiding Principles</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="getting-started.html"><a href="getting-started.html#pro-employee-thinking"><i class="fa fa-check"></i><b>1.1.1</b> Pro Employee Thinking</a></li>
<li class="chapter" data-level="1.1.2" data-path="getting-started.html"><a href="getting-started.html#quality"><i class="fa fa-check"></i><b>1.1.2</b> Quality</a></li>
<li class="chapter" data-level="1.1.3" data-path="getting-started.html"><a href="getting-started.html#prioritization"><i class="fa fa-check"></i><b>1.1.3</b> Prioritization</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#tools"><i class="fa fa-check"></i><b>1.2</b> Tools</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="getting-started.html"><a href="getting-started.html#r"><i class="fa fa-check"></i><b>1.2.1</b> R</a></li>
<li class="chapter" data-level="1.2.2" data-path="getting-started.html"><a href="getting-started.html#data"><i class="fa fa-check"></i><b>1.2.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#d-framework"><i class="fa fa-check"></i><b>1.3</b> 4D Framework</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="getting-started.html"><a href="getting-started.html#discover"><i class="fa fa-check"></i><b>1.3.1</b> Discover</a></li>
<li class="chapter" data-level="1.3.2" data-path="getting-started.html"><a href="getting-started.html#design"><i class="fa fa-check"></i><b>1.3.2</b> Design</a></li>
<li class="chapter" data-level="1.3.3" data-path="getting-started.html"><a href="getting-started.html#develop"><i class="fa fa-check"></i><b>1.3.3</b> Develop</a></li>
<li class="chapter" data-level="1.3.4" data-path="getting-started.html"><a href="getting-started.html#deliver"><i class="fa fa-check"></i><b>1.3.4</b> Deliver</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-intro.html"><a href="r-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-intro.html"><a href="r-intro.html#getting-started-1"><i class="fa fa-check"></i><b>2.1</b> Getting Started</a></li>
<li class="chapter" data-level="2.2" data-path="r-intro.html"><a href="r-intro.html#vectors"><i class="fa fa-check"></i><b>2.2</b> Vectors</a></li>
<li class="chapter" data-level="2.3" data-path="r-intro.html"><a href="r-intro.html#matrices"><i class="fa fa-check"></i><b>2.3</b> Matrices</a></li>
<li class="chapter" data-level="2.4" data-path="r-intro.html"><a href="r-intro.html#factors"><i class="fa fa-check"></i><b>2.4</b> Factors</a></li>
<li class="chapter" data-level="2.5" data-path="r-intro.html"><a href="r-intro.html#data-frames"><i class="fa fa-check"></i><b>2.5</b> Data Frames</a></li>
<li class="chapter" data-level="2.6" data-path="r-intro.html"><a href="r-intro.html#lists"><i class="fa fa-check"></i><b>2.6</b> Lists</a></li>
<li class="chapter" data-level="2.7" data-path="r-intro.html"><a href="r-intro.html#loops"><i class="fa fa-check"></i><b>2.7</b> Loops</a></li>
<li class="chapter" data-level="2.8" data-path="r-intro.html"><a href="r-intro.html#user-defined-functions-udfs"><i class="fa fa-check"></i><b>2.8</b> User-Defined Functions (UDFs)</a></li>
<li class="chapter" data-level="2.9" data-path="r-intro.html"><a href="r-intro.html#graphics"><i class="fa fa-check"></i><b>2.9</b> Graphics</a></li>
<li class="chapter" data-level="2.10" data-path="r-intro.html"><a href="r-intro.html#review-questions"><i class="fa fa-check"></i><b>2.10</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="measure-sampl.html"><a href="measure-sampl.html"><i class="fa fa-check"></i><b>3</b> Measurement &amp; Sampling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#variable-types"><i class="fa fa-check"></i><b>3.1</b> Variable Types</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="measure-sampl.html"><a href="measure-sampl.html#independent-variables-iv"><i class="fa fa-check"></i><b>3.1.1</b> Independent Variables (IV)</a></li>
<li class="chapter" data-level="3.1.2" data-path="measure-sampl.html"><a href="measure-sampl.html#dependent-variables-dv"><i class="fa fa-check"></i><b>3.1.2</b> Dependent Variables (DV)</a></li>
<li class="chapter" data-level="3.1.3" data-path="measure-sampl.html"><a href="measure-sampl.html#control-variables-cv"><i class="fa fa-check"></i><b>3.1.3</b> Control Variables (CV)</a></li>
<li class="chapter" data-level="3.1.4" data-path="measure-sampl.html"><a href="measure-sampl.html#moderating-variables"><i class="fa fa-check"></i><b>3.1.4</b> Moderating Variables</a></li>
<li class="chapter" data-level="3.1.5" data-path="measure-sampl.html"><a href="measure-sampl.html#mediating-variables"><i class="fa fa-check"></i><b>3.1.5</b> Mediating Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="measure-sampl.html"><a href="measure-sampl.html#measurement-scales"><i class="fa fa-check"></i><b>3.2</b> Measurement Scales</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="measure-sampl.html"><a href="measure-sampl.html#discrete-variables"><i class="fa fa-check"></i><b>3.2.1</b> Discrete Variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="measure-sampl.html"><a href="measure-sampl.html#continuous-variables"><i class="fa fa-check"></i><b>3.2.2</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling"><i class="fa fa-check"></i><b>3.3</b> Sampling</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-nonsampling-error"><i class="fa fa-check"></i><b>3.3.1</b> Sampling &amp; Nonsampling Error</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="measure-sampl.html"><a href="measure-sampl.html#review-questions-1"><i class="fa fa-check"></i><b>3.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="research.html"><a href="research.html"><i class="fa fa-check"></i><b>4</b> Research Fundamentals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="research.html"><a href="research.html#research-questions"><i class="fa fa-check"></i><b>4.1</b> Research Questions</a></li>
<li class="chapter" data-level="4.2" data-path="research.html"><a href="research.html#research-hypotheses"><i class="fa fa-check"></i><b>4.2</b> Research Hypotheses</a></li>
<li class="chapter" data-level="4.3" data-path="research.html"><a href="research.html#internal-vs.-external-validity"><i class="fa fa-check"></i><b>4.3</b> Internal vs. External Validity</a></li>
<li class="chapter" data-level="4.4" data-path="research.html"><a href="research.html#research-methods"><i class="fa fa-check"></i><b>4.4</b> Research Methods</a></li>
<li class="chapter" data-level="4.5" data-path="research.html"><a href="research.html#research-designs"><i class="fa fa-check"></i><b>4.5</b> Research Designs</a></li>
<li class="chapter" data-level="4.6" data-path="research.html"><a href="research.html#review-questions-2"><i class="fa fa-check"></i><b>4.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="desc-stats.html"><a href="desc-stats.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="5.1" data-path="desc-stats.html"><a href="desc-stats.html#univariate-analysis"><i class="fa fa-check"></i><b>5.1</b> Univariate Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>5.1.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="5.1.2" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-spread"><i class="fa fa-check"></i><b>5.1.2</b> Measures of Spread</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="desc-stats.html"><a href="desc-stats.html#bivariate-analysis"><i class="fa fa-check"></i><b>5.2</b> Bivariate Analysis</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="desc-stats.html"><a href="desc-stats.html#covariance"><i class="fa fa-check"></i><b>5.2.1</b> Covariance</a></li>
<li class="chapter" data-level="5.2.2" data-path="desc-stats.html"><a href="desc-stats.html#correlation"><i class="fa fa-check"></i><b>5.2.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="desc-stats.html"><a href="desc-stats.html#review-questions-3"><i class="fa fa-check"></i><b>5.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inf-stats.html"><a href="inf-stats.html"><i class="fa fa-check"></i><b>6</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inf-stats.html"><a href="inf-stats.html#introduction-to-probability"><i class="fa fa-check"></i><b>6.1</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="inf-stats.html"><a href="inf-stats.html#probability-distributions"><i class="fa fa-check"></i><b>6.1.1</b> Probability Distributions</a></li>
<li class="chapter" data-level="6.1.2" data-path="inf-stats.html"><a href="inf-stats.html#conditional-probability"><i class="fa fa-check"></i><b>6.1.2</b> Conditional Probability</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inf-stats.html"><a href="inf-stats.html#central-limit-theorem"><i class="fa fa-check"></i><b>6.2</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="6.3" data-path="inf-stats.html"><a href="inf-stats.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="inf-stats.html"><a href="inf-stats.html#hypothesis-testing"><i class="fa fa-check"></i><b>6.3.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="6.3.2" data-path="inf-stats.html"><a href="inf-stats.html#alpha"><i class="fa fa-check"></i><b>6.3.2</b> Alpha</a></li>
<li class="chapter" data-level="6.3.3" data-path="inf-stats.html"><a href="inf-stats.html#type-i-ii-errors"><i class="fa fa-check"></i><b>6.3.3</b> Type I &amp; II Errors</a></li>
<li class="chapter" data-level="6.3.4" data-path="inf-stats.html"><a href="inf-stats.html#p-values"><i class="fa fa-check"></i><b>6.3.4</b> <span class="math inline">\(p\)</span>-Values</a></li>
<li class="chapter" data-level="6.3.5" data-path="inf-stats.html"><a href="inf-stats.html#bonferroni-correction"><i class="fa fa-check"></i><b>6.3.5</b> Bonferroni Correction</a></li>
<li class="chapter" data-level="6.3.6" data-path="inf-stats.html"><a href="inf-stats.html#statistical-power"><i class="fa fa-check"></i><b>6.3.6</b> Statistical Power</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="inf-stats.html"><a href="inf-stats.html#review-questions-4"><i class="fa fa-check"></i><b>6.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html"><i class="fa fa-check"></i><b>7</b> Data Wrangling and Preparation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#data-management"><i class="fa fa-check"></i><b>7.1</b> Data Management</a></li>
<li class="chapter" data-level="7.2" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#sql"><i class="fa fa-check"></i><b>7.2</b> SQL</a></li>
<li class="chapter" data-level="7.3" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#data-screening-cleaning"><i class="fa fa-check"></i><b>7.3</b> Data Screening &amp; Cleaning</a></li>
<li class="chapter" data-level="7.4" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#one-hot-encoding"><i class="fa fa-check"></i><b>7.4</b> One-Hot Encoding</a></li>
<li class="chapter" data-level="7.5" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#feature-engineering"><i class="fa fa-check"></i><b>7.5</b> Feature Engineering</a></li>
<li class="chapter" data-level="7.6" data-path="data-wrang-prep.html"><a href="data-wrang-prep.html#review-questions-5"><i class="fa fa-check"></i><b>7.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="aod.html"><a href="aod.html"><i class="fa fa-check"></i><b>8</b> Analysis of Differences</a>
<ul>
<li class="chapter" data-level="8.1" data-path="aod.html"><a href="aod.html#parametric-vs.-nonparametric-tests"><i class="fa fa-check"></i><b>8.1</b> Parametric vs. Nonparametric Tests</a></li>
<li class="chapter" data-level="8.2" data-path="aod.html"><a href="aod.html#differences-in-discrete-data"><i class="fa fa-check"></i><b>8.2</b> Differences in Discrete Data</a></li>
<li class="chapter" data-level="8.3" data-path="aod.html"><a href="aod.html#differences-in-continuous-data"><i class="fa fa-check"></i><b>8.3</b> Differences in Continuous Data</a></li>
<li class="chapter" data-level="8.4" data-path="aod.html"><a href="aod.html#review-questions-6"><i class="fa fa-check"></i><b>8.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="lm.html"><a href="lm.html"><i class="fa fa-check"></i><b>9</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="lm.html"><a href="lm.html#sample-size"><i class="fa fa-check"></i><b>9.1</b> Sample Size</a></li>
<li class="chapter" data-level="9.2" data-path="lm.html"><a href="lm.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="9.3" data-path="lm.html"><a href="lm.html#multiple-linear-regression"><i class="fa fa-check"></i><b>9.3</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="9.4" data-path="lm.html"><a href="lm.html#model-comparisons"><i class="fa fa-check"></i><b>9.4</b> Model Comparisons</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="lm.html"><a href="lm.html#moderation"><i class="fa fa-check"></i><b>9.4.1</b> Moderation</a></li>
<li class="chapter" data-level="9.4.2" data-path="lm.html"><a href="lm.html#mediation"><i class="fa fa-check"></i><b>9.4.2</b> Mediation</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="lm.html"><a href="lm.html#review-questions-7"><i class="fa fa-check"></i><b>9.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lme.html"><a href="lme.html"><i class="fa fa-check"></i><b>10</b> Non-Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="lme.html"><a href="lme.html#polynomial-regression"><i class="fa fa-check"></i><b>10.1</b> Polynomial Regression</a></li>
<li class="chapter" data-level="10.2" data-path="lme.html"><a href="lme.html#logistic-regression"><i class="fa fa-check"></i><b>10.2</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="lme.html"><a href="lme.html#binomial-logistic-regression"><i class="fa fa-check"></i><b>10.2.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="10.2.2" data-path="lme.html"><a href="lme.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>10.2.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="10.2.3" data-path="lme.html"><a href="lme.html#proportional-odds-logistic-regression"><i class="fa fa-check"></i><b>10.2.3</b> Proportional Odds Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="lme.html"><a href="lme.html#poisson-regression"><i class="fa fa-check"></i><b>10.3</b> Poisson Regression</a></li>
<li class="chapter" data-level="10.4" data-path="lme.html"><a href="lme.html#review-questions-8"><i class="fa fa-check"></i><b>10.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pred-mod.html"><a href="pred-mod.html"><i class="fa fa-check"></i><b>11</b> Predictive Models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pred-mod.html"><a href="pred-mod.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>11.1</b> Bias-Variance Trade-Off</a></li>
<li class="chapter" data-level="11.2" data-path="pred-mod.html"><a href="pred-mod.html#cross-validation"><i class="fa fa-check"></i><b>11.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="11.3" data-path="pred-mod.html"><a href="pred-mod.html#balancing-classes"><i class="fa fa-check"></i><b>11.3</b> Balancing Classes</a></li>
<li class="chapter" data-level="11.4" data-path="pred-mod.html"><a href="pred-mod.html#model-performance"><i class="fa fa-check"></i><b>11.4</b> Model Performance</a></li>
<li class="chapter" data-level="11.5" data-path="pred-mod.html"><a href="pred-mod.html#automated-machine-learning-automl"><i class="fa fa-check"></i><b>11.5</b> Automated Machine Learning (AutoML)</a></li>
<li class="chapter" data-level="11.6" data-path="pred-mod.html"><a href="pred-mod.html#review-questions-9"><i class="fa fa-check"></i><b>11.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unsup-lrn.html"><a href="unsup-lrn.html"><i class="fa fa-check"></i><b>12</b> Unsupervised Learning</a>
<ul>
<li class="chapter" data-level="12.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#factor-analysis"><i class="fa fa-check"></i><b>12.1</b> Factor Analysis</a></li>
<li class="chapter" data-level="12.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#clustering"><i class="fa fa-check"></i><b>12.2</b> Clustering</a></li>
<li class="chapter" data-level="12.3" data-path="unsup-lrn.html"><a href="unsup-lrn.html#review-questions-10"><i class="fa fa-check"></i><b>12.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="data-viz.html"><a href="data-viz.html"><i class="fa fa-check"></i><b>13</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="13.1" data-path="data-viz.html"><a href="data-viz.html#design-guidelines"><i class="fa fa-check"></i><b>13.1</b> Design Guidelines</a></li>
<li class="chapter" data-level="13.2" data-path="data-viz.html"><a href="data-viz.html#visualization-types"><i class="fa fa-check"></i><b>13.2</b> Visualization Types</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="data-viz.html"><a href="data-viz.html#tables"><i class="fa fa-check"></i><b>13.2.1</b> Tables</a></li>
<li class="chapter" data-level="13.2.2" data-path="data-viz.html"><a href="data-viz.html#heatmaps"><i class="fa fa-check"></i><b>13.2.2</b> Heatmaps</a></li>
<li class="chapter" data-level="13.2.3" data-path="data-viz.html"><a href="data-viz.html#scatterplots"><i class="fa fa-check"></i><b>13.2.3</b> Scatterplots</a></li>
<li class="chapter" data-level="13.2.4" data-path="data-viz.html"><a href="data-viz.html#line-graphs"><i class="fa fa-check"></i><b>13.2.4</b> Line Graphs</a></li>
<li class="chapter" data-level="13.2.5" data-path="data-viz.html"><a href="data-viz.html#slopegraphs"><i class="fa fa-check"></i><b>13.2.5</b> Slopegraphs</a></li>
<li class="chapter" data-level="13.2.6" data-path="data-viz.html"><a href="data-viz.html#bar-charts"><i class="fa fa-check"></i><b>13.2.6</b> Bar Charts</a></li>
<li class="chapter" data-level="13.2.7" data-path="data-viz.html"><a href="data-viz.html#waterfall-charts"><i class="fa fa-check"></i><b>13.2.7</b> Waterfall Charts</a></li>
<li class="chapter" data-level="13.2.8" data-path="data-viz.html"><a href="data-viz.html#area-charts"><i class="fa fa-check"></i><b>13.2.8</b> Area Charts</a></li>
<li class="chapter" data-level="13.2.9" data-path="data-viz.html"><a href="data-viz.html#pie-charts"><i class="fa fa-check"></i><b>13.2.9</b> Pie Charts</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="data-viz.html"><a href="data-viz.html#review-questions-11"><i class="fa fa-check"></i><b>13.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="storytelling.html"><a href="storytelling.html"><i class="fa fa-check"></i><b>14</b> Data Storytelling</a>
<ul>
<li class="chapter" data-level="14.1" data-path="storytelling.html"><a href="storytelling.html#know-your-audience"><i class="fa fa-check"></i><b>14.1</b> Know Your Audience</a></li>
<li class="chapter" data-level="14.2" data-path="storytelling.html"><a href="storytelling.html#tldr"><i class="fa fa-check"></i><b>14.2</b> TL;DR</a></li>
<li class="chapter" data-level="14.3" data-path="storytelling.html"><a href="storytelling.html#telling-the-story"><i class="fa fa-check"></i><b>14.3</b> Telling the Story</a></li>
<li class="chapter" data-level="14.4" data-path="storytelling.html"><a href="storytelling.html#reference-material"><i class="fa fa-check"></i><b>14.4</b> Reference Material</a></li>
<li class="chapter" data-level="14.5" data-path="storytelling.html"><a href="storytelling.html#review-questions-12"><i class="fa fa-check"></i><b>14.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="bibli.html"><a href="bibli.html"><i class="fa fa-check"></i><b>15</b> Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to the People Analytics Lifecycle</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrang-prep" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Data Wrangling and Preparation</h1>
<p>To begin a data analysis, we must first access, integrate, and clean the relevant data. These tasks account for a large part of the work analytics professionals do.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ds-tasks"></span>
<img src="graphics/data_scientist_tasks.jpeg" alt="What Data Scientists Really Do" width="75%" />
<p class="caption">
Figure 7.1: What Data Scientists Really Do
</p>
</div>
<div id="data-management" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Data Management</h2>
<p>Data are extracted directly from the source systems in which they are generated or from downstream repositories such as a <em>data lake</em>, <em>data warehouse</em>, or <em>data mart</em>.</p>
<p>A <strong>data lake</strong> stores myriad types of data – both structured and unstructured – in its native format until needed. <strong>Structured data</strong> refers to data that fits a predefined data model, such as hire dates formatted as <code>MM/DD/YYYY</code> or zip codes stored as a five-digit string. <strong>Unstructured data</strong> has no predefined data model, such as audio and video files, free-form performance review comments, emails, or digital exhaust from messaging tools; it is difficult to structure this type of data within a set of related tables.</p>
<p>The main difference between a data lake and data warehouse is the type of data they are designed to store. A <strong>data warehouse (DW)</strong> is designed to support analytics across large collections of data, such as transactional data (e.g., point-of-sale systems), point-in-time snapshots (e.g., month-end close reports), survey responses, spreadsheets, and more. As shown in Figure <a href="data-wrang-prep.html#fig:dw-schema">7.2</a>, data in a DW are structured and organized into schemas of related tables to enhance the performance of queries spanning sets of large and diverse data.</p>
<p>Figure <a href="data-wrang-prep.html#fig:dw-schema">7.2</a> illustrates how worker, position, and recruiting schemas may be related. For example, a candidate submits a job application to a posted requisition, which is connected to an open position Finance approved as part of the company’s workforce plan; when the selected candidate is hired, they become a worker with one or many events (hire, promotion, transfer, termination) and activities (learning, performance appraisals, surveys) during their tenure with the company.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dw-schema"></span>
<img src="graphics/dw_schema.png" alt="Related Tables Organized within Schemas" width="100%" />
<p class="caption">
Figure 7.2: Related Tables Organized within Schemas
</p>
</div>
<p>Tables in a DW are related using a set of keys. Each table needs a <strong>Primary Key (PK)</strong>, which is a unique identifier for each row in the table. A PK may be a single column or multiple columns; a multi-column PK is often referred to as a <em>composite key</em>. It is generally best to leverage non-recyclable system-generated ids for PKs, as descriptors like names tend to be unreliable. A <strong>Foreign Key (FK)</strong> is a column whose values correspond to the values of a PK in another table. <strong>Referential integrity</strong> is the logical dependency of a FK on a PK, and these constraints protect against orphaned FK values in child tables by deleting PK values from an associated parent table.</p>
<p>Figure <a href="data-wrang-prep.html#fig:dw-erd">7.3</a> shows an <strong>Entity Relationship Diagram (ERD)</strong> that depicts PK/FK relationships among the Position, Worker, and Requisition tables. Notice that the PK of each related table shown in Figure <a href="data-wrang-prep.html#fig:dw-schema">7.2</a> is listed as a FK.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dw-erd"></span>
<img src="graphics/dw_erd.png" alt="Entity Relationship Diagram (ERD)" width="75%" />
<p class="caption">
Figure 7.3: Entity Relationship Diagram (ERD)
</p>
</div>
<p>A DW may contain many different types of tables, but the two most common are <em>Type 1</em> and <em>Type 2</em> tables. These tables are sometimes referred to as <strong>slowly changing dimensions (SCD)</strong>. A <strong>Type 1 table</strong> is overwritten on a regular cadence (usually daily) and contains no history – only current values. For example, a Type 1 table may contain the latest known attributes for each active and terminated worker such as job, location, and manager. A Type 1 table is convenient when only current information needs to be queried. A <strong>Type 2 table</strong> is a table in which a new record is inserted when a change occurs for one or more specified dimensions. Jobs, managers, and locations are examples of slowly changing dimensions but unlike the Type 1 table which is truncated and reloaded with the latest information, the Type 2 table houses a <em>start date</em> and <em>end date</em> for each worker and dimension to facilitate reporting and analysis on changes to attribute values over time.</p>
<p>Figure <a href="data-wrang-prep.html#fig:type-2-tbl">7.4</a> illustrates the design of a Type 2 SCD for an active worker’s job, manager, and location changes. As the data show, worker 123 was promoted from Data Analyst to Sr. Data Analyst 1.5 years after joining, began reporting to their original manager (456) after a short stint reporting to someone else (789), and has worked remotely throughout their tenure with the company.</p>
<p>Note that the combination of <code>end_date = '12/31/9999'</code> and <code>current_record = 'Y'</code> indicate <em>current attributes</em> for active workers. For inactive workers, <code>end_date</code> is set to the worker’s termination date for rows that represent the <em>last known attributes</em> along with <code>current_record = 'Y'</code>:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:type-2-tbl"></span>
<img src="graphics/type_2_table.png" alt="Type 2 SCD" width="100%" />
<p class="caption">
Figure 7.4: Type 2 SCD
</p>
</div>
<p>While we could select rows where <code>current_record = 'Y'</code> to construct a view of the last known attributes for each worker in this table, the task would be unnecessarily complex. Using a Type 1 table simplifies the task and output since each dimension value is stored in a separate column and there is only one row per employee. Figure <a href="data-wrang-prep.html#fig:type-1-tbl">7.5</a> shows how the current record for worker 123 would look in a Type 1 SCD:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:type-1-tbl"></span>
<img src="graphics/type_1_table.png" alt="Type 1 SCD" width="100%" />
<p class="caption">
Figure 7.5: Type 1 SCD
</p>
</div>
<p>A <strong>data mart</strong> is a subset of a DW designed to easily deliver specific information to a certain set of users on a particular subject or for a well-defined use case. For example, in a people analytics context a diversity data mart could be developed to better isolate and secure restricted data such as gender and ethnicity. This data may be used to support diversity descriptives and trends for a limited audience approved by Data Privacy and Employment Law counsel based on justified business needs.</p>
</div>
<div id="sql" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> SQL</h2>
<p><strong>Structured Query Language (SQL)</strong> is the most common language used to extract and wrangle data contained in a relational database. SQL is an essential skill for anyone working in analytics.</p>
<p>When working with large datasets, it is best to filter records on the database side to avoid reading superfluous records into an analytics tool such as R only to then filter data to the relevant subset. For example, if we are performing an analysis on employees in the Engineering department, we should ideally filter to this subset on the database side rather than loading into R data on the entire workforce before filtering down to the relevant records. Fewer records can help enhance the performance of R scripts – especially when R is running on a local machine, such as a laptop, rather than on a more powerful server.</p>
<p><strong>Basics</strong></p>
<p>There are three main <em>clauses</em> in a SQL query: (a) <code>SELECT</code>, (b) <code>FROM</code>, and (c) <code>WHERE</code>. The <code>SELECT</code> and <code>FROM</code> clauses are required, though the optional <code>WHERE</code> clause is frequently needed.</p>
<ul>
<li><strong>SELECT</strong>: Specifies the columns to include in the output</li>
<li><strong>FROM</strong>: Specifies the table(s) in which the relevant data are contained</li>
<li><strong>WHERE</strong>: Specifies the rows to search</li>
</ul>
<p>Despite the clauses being ordered as shown above (<code>SELECT</code> then <code>FROM</code> then <code>WHERE</code>), the <code>FROM</code> clause is the first to execute since we first need to identify the relevant table(s) before filtering rows and selecting columns. The <code>SELECT</code> clause is the last to execute.</p>
<p>Additional clauses are available for grouping and sorting data.</p>
<ul>
<li><strong>GROUP BY</strong>: Specifies the columns by which data should be grouped when using aggregate functions</li>
<li><strong>HAVING</strong>: Specifies conditions for filtering rows based on aggregate functions</li>
<li><strong>ORDER BY</strong>: Specifies how data should be sorted in the output</li>
</ul>
<p>When implementing aggregate functions in a <code>SELECT</code> clause, such as counting, summing, or averaging a numeric field, all other non-aggregated fields must be included in the <code>GROUP BY</code> clause.</p>
<p>Though it is important to execute SQL queries directly on the database to minimize the amount of data read into R, we will use the <code>sqldf</code> library within R to demonstrate the mechanics of a SQL query for easily replicable examples. The <code>sqldf</code> library allows us to write SQL to query a data frame in R in lieu of a database. While the syntax of SQL may vary by database, the core structure of queries is universal.</p>
<p>First, let’s load the data sets:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="data-wrang-prep.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets</span></span>
<span id="cb202-2"><a href="data-wrang-prep.html#cb202-2" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/employees.csv&quot;</span>)</span>
<span id="cb202-3"><a href="data-wrang-prep.html#cb202-3" aria-hidden="true" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/status.csv&quot;</span>)</span>
<span id="cb202-4"><a href="data-wrang-prep.html#cb202-4" aria-hidden="true" tabindex="-1"></a>benefits <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/benefits.csv&quot;</span>)</span>
<span id="cb202-5"><a href="data-wrang-prep.html#cb202-5" aria-hidden="true" tabindex="-1"></a>demographics <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/demographics.csv&quot;</span>)</span>
<span id="cb202-6"><a href="data-wrang-prep.html#cb202-6" aria-hidden="true" tabindex="-1"></a>job <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/job.csv&quot;</span>)</span>
<span id="cb202-7"><a href="data-wrang-prep.html#cb202-7" aria-hidden="true" tabindex="-1"></a>payroll <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/payroll.csv&quot;</span>)</span>
<span id="cb202-8"><a href="data-wrang-prep.html#cb202-8" aria-hidden="true" tabindex="-1"></a>performance <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/performance.csv&quot;</span>)</span>
<span id="cb202-9"><a href="data-wrang-prep.html#cb202-9" aria-hidden="true" tabindex="-1"></a>prior_employment <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/prior_employment.csv&quot;</span>)</span>
<span id="cb202-10"><a href="data-wrang-prep.html#cb202-10" aria-hidden="true" tabindex="-1"></a>survey_response <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/survey_response.csv&quot;</span>)</span>
<span id="cb202-11"><a href="data-wrang-prep.html#cb202-11" aria-hidden="true" tabindex="-1"></a>tenure <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/tenure.csv&quot;</span>)</span>
<span id="cb202-12"><a href="data-wrang-prep.html#cb202-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb202-13"><a href="data-wrang-prep.html#cb202-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Return row and column counts</span></span>
<span id="cb202-14"><a href="data-wrang-prep.html#cb202-14" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(employees)</span></code></pre></div>
<pre><code>## [1] 1470   36</code></pre>
<p>Next, we will apply the <code>sqldf()</code> function to our data frame to extract specific rows and columns. In addition to the <code>SELECT</code>, <code>FROM</code>, and <code>WHERE</code> clauses, we will use the <code>LIMIT</code> clause to limit the number of rows that are displayed given the data frame’s size (<span class="math inline">\(n = 1,470\)</span>). In a practical setting, the <code>LIMIT</code> clause is only used for efficient data profiling and troubleshooting, as we would not want to arbitrarily truncate a data set used for analysis.</p>
<p>A best practice in writing SQL is to capitalize the names of clauses and functions and to use separate lines and indentation to make the SQL statements more readable:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="data-wrang-prep.html#cb204-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load SQL library</span></span>
<span id="cb204-2"><a href="data-wrang-prep.html#cb204-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sqldf)</span>
<span id="cb204-3"><a href="data-wrang-prep.html#cb204-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb204-4"><a href="data-wrang-prep.html#cb204-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string using the paste() function</span></span>
<span id="cb204-5"><a href="data-wrang-prep.html#cb204-5" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb204-6"><a href="data-wrang-prep.html#cb204-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      employee_id</span></span>
<span id="cb204-7"><a href="data-wrang-prep.html#cb204-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb204-8"><a href="data-wrang-prep.html#cb204-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb204-9"><a href="data-wrang-prep.html#cb204-9" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb204-10"><a href="data-wrang-prep.html#cb204-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb204-11"><a href="data-wrang-prep.html#cb204-11" aria-hidden="true" tabindex="-1"></a><span class="st">                    LIMIT 10&quot;</span>)</span>
<span id="cb204-12"><a href="data-wrang-prep.html#cb204-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb204-13"><a href="data-wrang-prep.html#cb204-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb204-14"><a href="data-wrang-prep.html#cb204-14" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##    employee_id
## 1         1002
## 2         1003
## 3         1004
## 4         1005
## 5         1006
## 6         1007
## 7         1008
## 8         1009
## 9         1010
## 10        1011</code></pre>
<p>This query returned a list of employee ids for employees in the Research &amp; Development department.</p>
<p><strong>Aggregate Functions</strong></p>
<p>Next, let’s take a look at average organization tenure by job for those in the Research &amp; Development department:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="data-wrang-prep.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb206-2"><a href="data-wrang-prep.html#cb206-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb206-3"><a href="data-wrang-prep.html#cb206-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb206-4"><a href="data-wrang-prep.html#cb206-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      AVG(org_tenure)</span></span>
<span id="cb206-5"><a href="data-wrang-prep.html#cb206-5" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb206-6"><a href="data-wrang-prep.html#cb206-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb206-7"><a href="data-wrang-prep.html#cb206-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb206-8"><a href="data-wrang-prep.html#cb206-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb206-9"><a href="data-wrang-prep.html#cb206-9" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb206-10"><a href="data-wrang-prep.html#cb206-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb206-11"><a href="data-wrang-prep.html#cb206-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb206-12"><a href="data-wrang-prep.html#cb206-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb206-13"><a href="data-wrang-prep.html#cb206-13" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title AVG(org_tenure)
## 1 Healthcare Representative        8.618321
## 2     Laboratory Technician        5.019305
## 3                   Manager       13.673077
## 4    Manufacturing Director        7.600000
## 5         Research Director       10.937500
## 6        Research Scientist        5.113014
## 7            Vice President        9.500000</code></pre>
<p>There are 7 distinct job titles among employees in the Research &amp; Development department, and the average organization tenure for these ranges from <code>5</code> to <code>13.7</code> years.</p>
<p>Since there could be a small number of employees in certain jobs, in which case average organization tenure may not be as meaningful, we can use the <code>COUNT(*)</code> function to count the number of rows for each group. In this case, <code>COUNT(*)</code> will return the number of employees in each job in the Research &amp; Development department. We will also apply column aliases via <code>AS</code> in the <code>SELECT</code> clause to assign different names to the output fields:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="data-wrang-prep.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb208-2"><a href="data-wrang-prep.html#cb208-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb208-3"><a href="data-wrang-prep.html#cb208-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb208-4"><a href="data-wrang-prep.html#cb208-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb208-5"><a href="data-wrang-prep.html#cb208-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      AVG(org_tenure) AS avg_org_tenure</span></span>
<span id="cb208-6"><a href="data-wrang-prep.html#cb208-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb208-7"><a href="data-wrang-prep.html#cb208-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb208-8"><a href="data-wrang-prep.html#cb208-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb208-9"><a href="data-wrang-prep.html#cb208-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb208-10"><a href="data-wrang-prep.html#cb208-10" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb208-11"><a href="data-wrang-prep.html#cb208-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb208-12"><a href="data-wrang-prep.html#cb208-12" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb208-13"><a href="data-wrang-prep.html#cb208-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb208-14"><a href="data-wrang-prep.html#cb208-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb208-15"><a href="data-wrang-prep.html#cb208-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb208-16"><a href="data-wrang-prep.html#cb208-16" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure
## 1 Healthcare Representative          131       8.618321
## 2     Laboratory Technician          259       5.019305
## 3                   Manager           52      13.673077
## 4    Manufacturing Director          145       7.600000
## 5         Research Director           80      10.937500
## 6        Research Scientist          292       5.113014
## 7            Vice President            2       9.500000</code></pre>
<p>The output shows that there are only 2 Vice Presidents in the Research &amp; Development department, while other job titles are much more prevalent.</p>
<p>Since relatively few employees are Vice Presidents, let’s use the <code>HAVING</code> clause to only show average organization tenure for Research &amp; Development department jobs with more than 10 employees. We can also use the <code>ROUND()</code> function to truncate average organization tenure to one significant digit:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="data-wrang-prep.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb210-2"><a href="data-wrang-prep.html#cb210-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb210-3"><a href="data-wrang-prep.html#cb210-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb210-4"><a href="data-wrang-prep.html#cb210-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb210-5"><a href="data-wrang-prep.html#cb210-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure</span></span>
<span id="cb210-6"><a href="data-wrang-prep.html#cb210-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb210-7"><a href="data-wrang-prep.html#cb210-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb210-8"><a href="data-wrang-prep.html#cb210-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb210-9"><a href="data-wrang-prep.html#cb210-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb210-10"><a href="data-wrang-prep.html#cb210-10" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb210-11"><a href="data-wrang-prep.html#cb210-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb210-12"><a href="data-wrang-prep.html#cb210-12" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb210-13"><a href="data-wrang-prep.html#cb210-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb210-14"><a href="data-wrang-prep.html#cb210-14" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb210-15"><a href="data-wrang-prep.html#cb210-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb210-16"><a href="data-wrang-prep.html#cb210-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb210-17"><a href="data-wrang-prep.html#cb210-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb210-18"><a href="data-wrang-prep.html#cb210-18" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure
## 1 Healthcare Representative          131            8.6
## 2     Laboratory Technician          259            5.0
## 3                   Manager           52           13.7
## 4    Manufacturing Director          145            7.6
## 5         Research Director           80           10.9
## 6        Research Scientist          292            5.1</code></pre>
<p><strong>Joins</strong></p>
<p>In a practical setting, the required data are rarely contained within a single table. Therefore, we must query multiple tables and join them together. Figure <a href="data-wrang-prep.html#fig:sql-joins">7.6</a> illustrates SQL join types using Venn diagrams:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sql-joins"></span>
<img src="graphics/sql_joins.png" alt="Types of SQL Joins" width="100%" />
<p class="caption">
Figure 7.6: Types of SQL Joins
</p>
</div>
<p>The structure of SQL queries containing each type of join is represented below:</p>
<p><strong>LEFT INCLUSIVE</strong></p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="data-wrang-prep.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb212-2"><a href="data-wrang-prep.html#cb212-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb212-3"><a href="data-wrang-prep.html#cb212-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb212-4"><a href="data-wrang-prep.html#cb212-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>LEFT EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="data-wrang-prep.html#cb213-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb213-2"><a href="data-wrang-prep.html#cb213-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb213-3"><a href="data-wrang-prep.html#cb213-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb213-4"><a href="data-wrang-prep.html#cb213-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb213-5"><a href="data-wrang-prep.html#cb213-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE B.Key IS NULL</span></span></code></pre></div>
<p><strong>FULL OUTER INCLUSIVE</strong></p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="data-wrang-prep.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb214-2"><a href="data-wrang-prep.html#cb214-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb214-3"><a href="data-wrang-prep.html#cb214-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  FULL OUTER JOIN B</span></span>
<span id="cb214-4"><a href="data-wrang-prep.html#cb214-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>FULL OUTER EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="data-wrang-prep.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb215-2"><a href="data-wrang-prep.html#cb215-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb215-3"><a href="data-wrang-prep.html#cb215-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  FULL OUTER JOIN B</span></span>
<span id="cb215-4"><a href="data-wrang-prep.html#cb215-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb215-5"><a href="data-wrang-prep.html#cb215-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE A.Key IS NULL OR B.Key IS NULL  </span></span></code></pre></div>
<p><strong>RIGHT INCLUSIVE</strong></p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="data-wrang-prep.html#cb216-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb216-2"><a href="data-wrang-prep.html#cb216-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb216-3"><a href="data-wrang-prep.html#cb216-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  RIGHT OUTER JOIN B</span></span>
<span id="cb216-4"><a href="data-wrang-prep.html#cb216-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>RIGHT EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="data-wrang-prep.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb217-2"><a href="data-wrang-prep.html#cb217-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb217-3"><a href="data-wrang-prep.html#cb217-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb217-4"><a href="data-wrang-prep.html#cb217-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb217-5"><a href="data-wrang-prep.html#cb217-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE A.Key IS NULL</span></span></code></pre></div>
<p><strong>INNER JOIN</strong></p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="data-wrang-prep.html#cb218-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb218-2"><a href="data-wrang-prep.html#cb218-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb218-3"><a href="data-wrang-prep.html#cb218-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  INNER JOIN B</span></span>
<span id="cb218-4"><a href="data-wrang-prep.html#cb218-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p>To illustrate how SQL joins work, we will leverage three of the data sets used to produce the consolidated <code>employees</code> data set we have been using: <code>job</code>, <code>tenure</code>, and <code>demographics</code>. For many people analytics projects, employee id is the PK since this identifier for one employee should not be assigned to another employee – past, present, or future. Email or network id may also be a suitable PK. We will use the <code>employee_id</code> column in each of the three data frames to facilitate joins:</p>
<p>Next, we will query these data frames to return the average organization tenure and average commute distance for employees in the Research &amp; Development department, grouped by jobs with more than 10 employees. For this, we will leverage an <code>INNER JOIN</code>, which will return records only for employee ids which are present in all three data frames. For example, if a record exists in <code>demographics</code> and <code>tenure</code> for a particular employee id, but there is no corresponding record in <code>job</code>, that employee id would not be included in the output.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="data-wrang-prep.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb219-2"><a href="data-wrang-prep.html#cb219-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb219-3"><a href="data-wrang-prep.html#cb219-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb219-4"><a href="data-wrang-prep.html#cb219-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb219-5"><a href="data-wrang-prep.html#cb219-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure,</span></span>
<span id="cb219-6"><a href="data-wrang-prep.html#cb219-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb219-7"><a href="data-wrang-prep.html#cb219-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb219-8"><a href="data-wrang-prep.html#cb219-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb219-9"><a href="data-wrang-prep.html#cb219-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb219-10"><a href="data-wrang-prep.html#cb219-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        tenure</span></span>
<span id="cb219-11"><a href="data-wrang-prep.html#cb219-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb219-12"><a href="data-wrang-prep.html#cb219-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = tenure.employee_id</span></span>
<span id="cb219-13"><a href="data-wrang-prep.html#cb219-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb219-14"><a href="data-wrang-prep.html#cb219-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb219-15"><a href="data-wrang-prep.html#cb219-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb219-16"><a href="data-wrang-prep.html#cb219-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb219-17"><a href="data-wrang-prep.html#cb219-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb219-18"><a href="data-wrang-prep.html#cb219-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb219-19"><a href="data-wrang-prep.html#cb219-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb219-20"><a href="data-wrang-prep.html#cb219-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb219-21"><a href="data-wrang-prep.html#cb219-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb219-22"><a href="data-wrang-prep.html#cb219-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb219-23"><a href="data-wrang-prep.html#cb219-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb219-24"><a href="data-wrang-prep.html#cb219-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb219-25"><a href="data-wrang-prep.html#cb219-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-26"><a href="data-wrang-prep.html#cb219-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb219-27"><a href="data-wrang-prep.html#cb219-27" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure avg_commute_dist
## 1 Healthcare Representative          131            8.6              9.8
## 2     Laboratory Technician          259            5.0              9.4
## 3                   Manager           52           13.7              7.2
## 4    Manufacturing Director          145            7.6              9.5
## 5         Research Director           80           10.9              8.4
## 6        Research Scientist          292            5.1              9.0</code></pre>
<p>Note that the <code>INNER JOIN</code> in this SQL query was structured such that both <code>tenure</code> and <code>job</code> were joined to <code>demographics</code> via the <code>employee_id</code> column. We could have instead joined <code>job</code> to <code>tenure</code> since we joined <code>tenure</code> to <code>demographics</code>; this would have achieved the same result since all employee ids exist in each of the three data frames.</p>
<p>If it were possible for all employee ids to exist in <code>demographics</code> but not in either <code>tenure</code> or <code>job</code>, we could leverage a <code>LEFT JOIN</code> to ensure all records from <code>demographics</code> are included in the output irrespective of whether they have matches in <code>tenure</code> or <code>job</code>:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="data-wrang-prep.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb221-2"><a href="data-wrang-prep.html#cb221-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb221-3"><a href="data-wrang-prep.html#cb221-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb221-4"><a href="data-wrang-prep.html#cb221-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb221-5"><a href="data-wrang-prep.html#cb221-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure,</span></span>
<span id="cb221-6"><a href="data-wrang-prep.html#cb221-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb221-7"><a href="data-wrang-prep.html#cb221-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb221-8"><a href="data-wrang-prep.html#cb221-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb221-9"><a href="data-wrang-prep.html#cb221-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb221-10"><a href="data-wrang-prep.html#cb221-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        tenure</span></span>
<span id="cb221-11"><a href="data-wrang-prep.html#cb221-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb221-12"><a href="data-wrang-prep.html#cb221-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = tenure.employee_id</span></span>
<span id="cb221-13"><a href="data-wrang-prep.html#cb221-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb221-14"><a href="data-wrang-prep.html#cb221-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb221-15"><a href="data-wrang-prep.html#cb221-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb221-16"><a href="data-wrang-prep.html#cb221-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb221-17"><a href="data-wrang-prep.html#cb221-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb221-18"><a href="data-wrang-prep.html#cb221-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb221-19"><a href="data-wrang-prep.html#cb221-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb221-20"><a href="data-wrang-prep.html#cb221-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb221-21"><a href="data-wrang-prep.html#cb221-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb221-22"><a href="data-wrang-prep.html#cb221-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb221-23"><a href="data-wrang-prep.html#cb221-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb221-24"><a href="data-wrang-prep.html#cb221-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb221-25"><a href="data-wrang-prep.html#cb221-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb221-26"><a href="data-wrang-prep.html#cb221-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb221-27"><a href="data-wrang-prep.html#cb221-27" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure avg_commute_dist
## 1 Healthcare Representative          131            8.6              9.8
## 2     Laboratory Technician          259            5.0              9.4
## 3                   Manager           52           13.7              7.2
## 4    Manufacturing Director          145            7.6              9.5
## 5         Research Director           80           10.9              8.4
## 6        Research Scientist          292            5.1              9.0</code></pre>
<p>In this case, if demographics is the base data set which contains all employee ids (i.e., the ‘LEFT’ dataset), it is important for <code>tenure</code> and <code>job</code> to be joined to it. Joining <code>job</code> to <code>tenure</code> may result in information loss if an employee id exists in <code>demographics</code> and <code>job</code> but not in the intermediate <code>tenure</code> data set.</p>
<p>When integrating data within R, the <code>tidyverse</code> provides a more efficient and parsimonious method of joining many data sets using various join types. The example below joins nine data sets into a single <code>employees</code> data frame using a left join on the <code>employee_id</code> column:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="data-wrang-prep.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load tidyverse</span></span>
<span id="cb223-2"><a href="data-wrang-prep.html#cb223-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb223-3"><a href="data-wrang-prep.html#cb223-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb223-4"><a href="data-wrang-prep.html#cb223-4" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">list</span>(demographics,</span>
<span id="cb223-5"><a href="data-wrang-prep.html#cb223-5" aria-hidden="true" tabindex="-1"></a>                  status,</span>
<span id="cb223-6"><a href="data-wrang-prep.html#cb223-6" aria-hidden="true" tabindex="-1"></a>                  benefits,</span>
<span id="cb223-7"><a href="data-wrang-prep.html#cb223-7" aria-hidden="true" tabindex="-1"></a>                  job,</span>
<span id="cb223-8"><a href="data-wrang-prep.html#cb223-8" aria-hidden="true" tabindex="-1"></a>                  payroll,</span>
<span id="cb223-9"><a href="data-wrang-prep.html#cb223-9" aria-hidden="true" tabindex="-1"></a>                  performance,</span>
<span id="cb223-10"><a href="data-wrang-prep.html#cb223-10" aria-hidden="true" tabindex="-1"></a>                  prior_employment,</span>
<span id="cb223-11"><a href="data-wrang-prep.html#cb223-11" aria-hidden="true" tabindex="-1"></a>                  survey_response,</span>
<span id="cb223-12"><a href="data-wrang-prep.html#cb223-12" aria-hidden="true" tabindex="-1"></a>                  tenure) <span class="sc">%&gt;%</span></span>
<span id="cb223-13"><a href="data-wrang-prep.html#cb223-13" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">reduce</span>(left_join, <span class="at">by =</span> <span class="st">&quot;employee_id&quot;</span>)</span></code></pre></div>
<p><strong>Subqueries</strong></p>
<p><strong>Subqueries</strong> are queries nested within other queries. Subqueries are often referred to as <strong>inner queries</strong>, while the main queries are referred to as <strong>outer queries</strong>.</p>
<p>For example, if we are interested in performing an analysis on employees with more than a year of organization tenure, we can use a subquery to pass a list of employee ids that meet this criterion into the outer query for filtering. In this case, we would not need to include <code>tenure</code> in the join conditions of our main query:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="data-wrang-prep.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb224-2"><a href="data-wrang-prep.html#cb224-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: Since employee_id exists in multiple data sets, we must name a specific data set when referencing it</span></span>
<span id="cb224-3"><a href="data-wrang-prep.html#cb224-3" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb224-4"><a href="data-wrang-prep.html#cb224-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb224-5"><a href="data-wrang-prep.html#cb224-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb224-6"><a href="data-wrang-prep.html#cb224-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb224-7"><a href="data-wrang-prep.html#cb224-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb224-8"><a href="data-wrang-prep.html#cb224-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb224-9"><a href="data-wrang-prep.html#cb224-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb224-10"><a href="data-wrang-prep.html#cb224-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb224-11"><a href="data-wrang-prep.html#cb224-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb224-12"><a href="data-wrang-prep.html#cb224-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb224-13"><a href="data-wrang-prep.html#cb224-13" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb224-14"><a href="data-wrang-prep.html#cb224-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id IN (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1)</span></span>
<span id="cb224-15"><a href="data-wrang-prep.html#cb224-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      AND </span></span>
<span id="cb224-16"><a href="data-wrang-prep.html#cb224-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb224-17"><a href="data-wrang-prep.html#cb224-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb224-18"><a href="data-wrang-prep.html#cb224-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb224-19"><a href="data-wrang-prep.html#cb224-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb224-20"><a href="data-wrang-prep.html#cb224-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb224-21"><a href="data-wrang-prep.html#cb224-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb224-22"><a href="data-wrang-prep.html#cb224-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb224-23"><a href="data-wrang-prep.html#cb224-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-24"><a href="data-wrang-prep.html#cb224-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb224-25"><a href="data-wrang-prep.html#cb224-25" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_commute_dist
## 1 Healthcare Representative          118              9.7
## 2     Laboratory Technician          198              9.6
## 3                   Manager           49              6.9
## 4    Manufacturing Director          133              9.7
## 5         Research Director           74              8.3
## 6        Research Scientist          238              9.2</code></pre>
<p><strong>Virtual Tables</strong></p>
<p>An alternative to a subquery is creating a <strong>virtual table</strong> in the <code>FROM</code> clause. When using an <code>INNER JOIN</code> to connect <code>demographics</code> to the virtual table <code>ids</code>, which provides a list of employee ids for those with more than a year of organization tenure, any records in <code>demographics</code> or <code>job</code> that do not relate to employees with at least a year of organization tenure will be dropped. This is true even though a <code>LEFT JOIN</code> is used to join <code>job</code> to <code>demographics</code> since records in <code>demographics</code> will be filtered based on <code>employee_id</code> matches in the virtual table. With this approach, our <code>WHERE</code> clause is limited to the <code>department = 'Research &amp; Development'</code> condition:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="data-wrang-prep.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb226-2"><a href="data-wrang-prep.html#cb226-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb226-3"><a href="data-wrang-prep.html#cb226-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb226-4"><a href="data-wrang-prep.html#cb226-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb226-5"><a href="data-wrang-prep.html#cb226-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb226-6"><a href="data-wrang-prep.html#cb226-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb226-7"><a href="data-wrang-prep.html#cb226-7" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb226-8"><a href="data-wrang-prep.html#cb226-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb226-9"><a href="data-wrang-prep.html#cb226-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb226-10"><a href="data-wrang-prep.html#cb226-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb226-11"><a href="data-wrang-prep.html#cb226-11" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb226-12"><a href="data-wrang-prep.html#cb226-12" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb226-13"><a href="data-wrang-prep.html#cb226-13" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb226-14"><a href="data-wrang-prep.html#cb226-14" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb226-15"><a href="data-wrang-prep.html#cb226-15" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = ids.employee_id</span></span>
<span id="cb226-16"><a href="data-wrang-prep.html#cb226-16" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb226-17"><a href="data-wrang-prep.html#cb226-17" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb226-18"><a href="data-wrang-prep.html#cb226-18" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb226-19"><a href="data-wrang-prep.html#cb226-19" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb226-20"><a href="data-wrang-prep.html#cb226-20" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb226-21"><a href="data-wrang-prep.html#cb226-21" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb226-22"><a href="data-wrang-prep.html#cb226-22" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb226-23"><a href="data-wrang-prep.html#cb226-23" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb226-24"><a href="data-wrang-prep.html#cb226-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb226-25"><a href="data-wrang-prep.html#cb226-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb226-26"><a href="data-wrang-prep.html#cb226-26" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_commute_dist
## 1 Healthcare Representative          118              9.7
## 2     Laboratory Technician          198              9.6
## 3                   Manager           49              6.9
## 4    Manufacturing Director          133              9.7
## 5         Research Director           74              8.3
## 6        Research Scientist          238              9.2</code></pre>
<p>As you can see, the output of the query using a virtual table matches the results from the preceding approach that utilized a subquery.</p>
<p><strong>Window Functions</strong></p>
<p><strong>Window functions</strong> are used for performing calculations over a set of rows without collapsing the records. Unlike the aggregate functions we’ve covered, window functions do not collapse rows into a single value; the calculated value is returned for each of the rows over which the calculation is performed.</p>
<p>For example, we can assign an organization tenure rank by Research &amp; Development job using the <code>RANK()</code> and <code>OVER()</code> functions in the <code>SELECT</code> clause. The <code>PARTITION BY</code> argument functions like a <code>GROUP BY</code> clause but without collapsing rows, while the <code>ORDER BY</code> argument sorts the records in ascending (<code>ASC</code>) or descending (<code>DESC</code>) order for proper ranking:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="data-wrang-prep.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb228-2"><a href="data-wrang-prep.html#cb228-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Limit output to 10 records since query does not collapse records</span></span>
<span id="cb228-3"><a href="data-wrang-prep.html#cb228-3" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb228-4"><a href="data-wrang-prep.html#cb228-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      demographics.employee_id,</span></span>
<span id="cb228-5"><a href="data-wrang-prep.html#cb228-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb228-6"><a href="data-wrang-prep.html#cb228-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      commute_dist,</span></span>
<span id="cb228-7"><a href="data-wrang-prep.html#cb228-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb228-8"><a href="data-wrang-prep.html#cb228-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb228-9"><a href="data-wrang-prep.html#cb228-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb228-10"><a href="data-wrang-prep.html#cb228-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb228-11"><a href="data-wrang-prep.html#cb228-11" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb228-12"><a href="data-wrang-prep.html#cb228-12" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb228-13"><a href="data-wrang-prep.html#cb228-13" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb228-14"><a href="data-wrang-prep.html#cb228-14" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb228-15"><a href="data-wrang-prep.html#cb228-15" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb228-16"><a href="data-wrang-prep.html#cb228-16" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb228-17"><a href="data-wrang-prep.html#cb228-17" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = ids.employee_id</span></span>
<span id="cb228-18"><a href="data-wrang-prep.html#cb228-18" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb228-19"><a href="data-wrang-prep.html#cb228-19" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb228-20"><a href="data-wrang-prep.html#cb228-20" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb228-21"><a href="data-wrang-prep.html#cb228-21" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb228-22"><a href="data-wrang-prep.html#cb228-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      commute_dist_rank</span></span>
<span id="cb228-23"><a href="data-wrang-prep.html#cb228-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    LIMIT 10&quot;</span>)</span>
<span id="cb228-24"><a href="data-wrang-prep.html#cb228-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb228-25"><a href="data-wrang-prep.html#cb228-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb228-26"><a href="data-wrang-prep.html#cb228-26" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##    employee_id                 job_title commute_dist commute_dist_rank
## 1         2325 Healthcare Representative           29                 1
## 2         1414 Healthcare Representative           28                 2
## 3         1010 Healthcare Representative           27                 3
## 4         1573 Healthcare Representative           27                 3
## 5         2200 Healthcare Representative           26                 5
## 6         1730 Healthcare Representative           25                 6
## 7         1833 Healthcare Representative           25                 6
## 8         1993 Healthcare Representative           25                 6
## 9         2415 Healthcare Representative           25                 6
## 10        1164 Healthcare Representative           24                10</code></pre>
<p>Notice that in the case of commute distance ties, the <code>RANK()</code> function assigns the same rank and then adds the number of ties to that rank to determine the rank for the next highest value of commute distance.</p>
<p>We can also treat this query as a virtual table, and then filter on the derived <code>commute_dist_rank</code> field to return the highest commute distance for each job. We can add a <code>DISTINCT()</code> function in the <code>SELECT</code> clause to collapse jobs for which there are more than one employee with the max commute distance, and display the number of ties for each using the <code>COUNT(*)</code> function:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="data-wrang-prep.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb230-2"><a href="data-wrang-prep.html#cb230-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb230-3"><a href="data-wrang-prep.html#cb230-3" aria-hidden="true" tabindex="-1"></a><span class="st">                        DISTINCT(job_title) AS job_title,</span></span>
<span id="cb230-4"><a href="data-wrang-prep.html#cb230-4" aria-hidden="true" tabindex="-1"></a><span class="st">                        COUNT(*) AS employee_count,</span></span>
<span id="cb230-5"><a href="data-wrang-prep.html#cb230-5" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist</span></span>
<span id="cb230-6"><a href="data-wrang-prep.html#cb230-6" aria-hidden="true" tabindex="-1"></a><span class="st">                     FROM</span></span>
<span id="cb230-7"><a href="data-wrang-prep.html#cb230-7" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT</span></span>
<span id="cb230-8"><a href="data-wrang-prep.html#cb230-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          demographics.employee_id,</span></span>
<span id="cb230-9"><a href="data-wrang-prep.html#cb230-9" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb230-10"><a href="data-wrang-prep.html#cb230-10" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist,</span></span>
<span id="cb230-11"><a href="data-wrang-prep.html#cb230-11" aria-hidden="true" tabindex="-1"></a><span class="st">                          RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb230-12"><a href="data-wrang-prep.html#cb230-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        FROM</span></span>
<span id="cb230-13"><a href="data-wrang-prep.html#cb230-13" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics</span></span>
<span id="cb230-14"><a href="data-wrang-prep.html#cb230-14" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN</span></span>
<span id="cb230-15"><a href="data-wrang-prep.html#cb230-15" aria-hidden="true" tabindex="-1"></a><span class="st">                            job</span></span>
<span id="cb230-16"><a href="data-wrang-prep.html#cb230-16" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb230-17"><a href="data-wrang-prep.html#cb230-17" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = job.employee_id</span></span>
<span id="cb230-18"><a href="data-wrang-prep.html#cb230-18" aria-hidden="true" tabindex="-1"></a><span class="st">                          INNER JOIN</span></span>
<span id="cb230-19"><a href="data-wrang-prep.html#cb230-19" aria-hidden="true" tabindex="-1"></a><span class="st">                            (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb230-20"><a href="data-wrang-prep.html#cb230-20" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb230-21"><a href="data-wrang-prep.html#cb230-21" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = ids.employee_id</span></span>
<span id="cb230-22"><a href="data-wrang-prep.html#cb230-22" aria-hidden="true" tabindex="-1"></a><span class="st">                        WHERE</span></span>
<span id="cb230-23"><a href="data-wrang-prep.html#cb230-23" aria-hidden="true" tabindex="-1"></a><span class="st">                          dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb230-24"><a href="data-wrang-prep.html#cb230-24" aria-hidden="true" tabindex="-1"></a><span class="st">                        ORDER BY</span></span>
<span id="cb230-25"><a href="data-wrang-prep.html#cb230-25" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb230-26"><a href="data-wrang-prep.html#cb230-26" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist_rank) tbl</span></span>
<span id="cb230-27"><a href="data-wrang-prep.html#cb230-27" aria-hidden="true" tabindex="-1"></a><span class="st">                      WHERE</span></span>
<span id="cb230-28"><a href="data-wrang-prep.html#cb230-28" aria-hidden="true" tabindex="-1"></a><span class="st">                        tbl.commute_dist_rank = 1</span></span>
<span id="cb230-29"><a href="data-wrang-prep.html#cb230-29" aria-hidden="true" tabindex="-1"></a><span class="st">                      GROUP BY</span></span>
<span id="cb230-30"><a href="data-wrang-prep.html#cb230-30" aria-hidden="true" tabindex="-1"></a><span class="st">                        job_title&quot;</span>)</span>
<span id="cb230-31"><a href="data-wrang-prep.html#cb230-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb230-32"><a href="data-wrang-prep.html#cb230-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb230-33"><a href="data-wrang-prep.html#cb230-33" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_count commute_dist
## 1 Healthcare Representative              1           29
## 2     Laboratory Technician              6           29
## 3                   Manager              2           29
## 4    Manufacturing Director              4           29
## 5         Research Director              3           28
## 6        Research Scientist              4           29
## 7            Vice President              1            8</code></pre>
<p>An alternative approach is to use a <strong>common table expression (CTE)</strong>, which is the result set of a query that exists temporarily and only for use in a larger query. Like the virtual table example, CTEs do not persist data in objects or tables; the data exist only for the duration of the query.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="data-wrang-prep.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb232-2"><a href="data-wrang-prep.html#cb232-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;WITH max_commute_job</span></span>
<span id="cb232-3"><a href="data-wrang-prep.html#cb232-3" aria-hidden="true" tabindex="-1"></a><span class="st">                     AS</span></span>
<span id="cb232-4"><a href="data-wrang-prep.html#cb232-4" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT</span></span>
<span id="cb232-5"><a href="data-wrang-prep.html#cb232-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          demographics.employee_id,</span></span>
<span id="cb232-6"><a href="data-wrang-prep.html#cb232-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb232-7"><a href="data-wrang-prep.html#cb232-7" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist,</span></span>
<span id="cb232-8"><a href="data-wrang-prep.html#cb232-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb232-9"><a href="data-wrang-prep.html#cb232-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        FROM</span></span>
<span id="cb232-10"><a href="data-wrang-prep.html#cb232-10" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics</span></span>
<span id="cb232-11"><a href="data-wrang-prep.html#cb232-11" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN</span></span>
<span id="cb232-12"><a href="data-wrang-prep.html#cb232-12" aria-hidden="true" tabindex="-1"></a><span class="st">                            job</span></span>
<span id="cb232-13"><a href="data-wrang-prep.html#cb232-13" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb232-14"><a href="data-wrang-prep.html#cb232-14" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = job.employee_id</span></span>
<span id="cb232-15"><a href="data-wrang-prep.html#cb232-15" aria-hidden="true" tabindex="-1"></a><span class="st">                          INNER JOIN</span></span>
<span id="cb232-16"><a href="data-wrang-prep.html#cb232-16" aria-hidden="true" tabindex="-1"></a><span class="st">                            (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb232-17"><a href="data-wrang-prep.html#cb232-17" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb232-18"><a href="data-wrang-prep.html#cb232-18" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = ids.employee_id</span></span>
<span id="cb232-19"><a href="data-wrang-prep.html#cb232-19" aria-hidden="true" tabindex="-1"></a><span class="st">                        WHERE</span></span>
<span id="cb232-20"><a href="data-wrang-prep.html#cb232-20" aria-hidden="true" tabindex="-1"></a><span class="st">                          dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb232-21"><a href="data-wrang-prep.html#cb232-21" aria-hidden="true" tabindex="-1"></a><span class="st">                        ORDER BY</span></span>
<span id="cb232-22"><a href="data-wrang-prep.html#cb232-22" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb232-23"><a href="data-wrang-prep.html#cb232-23" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist_rank)</span></span>
<span id="cb232-24"><a href="data-wrang-prep.html#cb232-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      </span></span>
<span id="cb232-25"><a href="data-wrang-prep.html#cb232-25" aria-hidden="true" tabindex="-1"></a><span class="st">                      SELECT</span></span>
<span id="cb232-26"><a href="data-wrang-prep.html#cb232-26" aria-hidden="true" tabindex="-1"></a><span class="st">                        DISTINCT(job_title) AS job_title,</span></span>
<span id="cb232-27"><a href="data-wrang-prep.html#cb232-27" aria-hidden="true" tabindex="-1"></a><span class="st">                        COUNT(*) AS employee_count,</span></span>
<span id="cb232-28"><a href="data-wrang-prep.html#cb232-28" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist</span></span>
<span id="cb232-29"><a href="data-wrang-prep.html#cb232-29" aria-hidden="true" tabindex="-1"></a><span class="st">                     FROM</span></span>
<span id="cb232-30"><a href="data-wrang-prep.html#cb232-30" aria-hidden="true" tabindex="-1"></a><span class="st">                        max_commute_job</span></span>
<span id="cb232-31"><a href="data-wrang-prep.html#cb232-31" aria-hidden="true" tabindex="-1"></a><span class="st">                      WHERE</span></span>
<span id="cb232-32"><a href="data-wrang-prep.html#cb232-32" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist_rank = 1</span></span>
<span id="cb232-33"><a href="data-wrang-prep.html#cb232-33" aria-hidden="true" tabindex="-1"></a><span class="st">                      GROUP BY</span></span>
<span id="cb232-34"><a href="data-wrang-prep.html#cb232-34" aria-hidden="true" tabindex="-1"></a><span class="st">                        job_title&quot;</span>)</span>
<span id="cb232-35"><a href="data-wrang-prep.html#cb232-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb232-36"><a href="data-wrang-prep.html#cb232-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb232-37"><a href="data-wrang-prep.html#cb232-37" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_count commute_dist
## 1 Healthcare Representative              1           29
## 2     Laboratory Technician              6           29
## 3                   Manager              2           29
## 4    Manufacturing Director              4           29
## 5         Research Director              3           28
## 6        Research Scientist              4           29
## 7            Vice President              1            8</code></pre>
</div>
<div id="data-screening-cleaning" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Data Screening &amp; Cleaning</h2>
<p>The initial data review process is sometimes referred to as <strong>exploratory data analysis (EDA)</strong>. EDA involves investigating patterns, completeness, anomalies, and assumptions using summary statistics and graphical representations.</p>
<p>A handy function in base R for initial data screening is <code>summary()</code>:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="data-wrang-prep.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize df</span></span>
<span id="cb234-2"><a href="data-wrang-prep.html#cb234-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(employees)</span></code></pre></div>
<pre><code>##   employee_id        age         commute_dist        ed_lvl     
##  Min.   :1001   Min.   :18.00   Min.   : 1.000   Min.   :1.000  
##  1st Qu.:1368   1st Qu.:30.00   1st Qu.: 2.000   1st Qu.:2.000  
##  Median :1736   Median :36.00   Median : 7.000   Median :3.000  
##  Mean   :1736   Mean   :36.92   Mean   : 9.193   Mean   :2.913  
##  3rd Qu.:2103   3rd Qu.:43.00   3rd Qu.:14.000   3rd Qu.:4.000  
##  Max.   :2470   Max.   :60.00   Max.   :29.000   Max.   :5.000  
##    ed_field            gender          marital_sts           active         
##  Length:1470        Length:1470        Length:1470        Length:1470       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##  stock_opt_lvl      trainings         dept              job_lvl     
##  Min.   :0.0000   Min.   :0.000   Length:1470        Min.   :1.000  
##  1st Qu.:0.0000   1st Qu.:2.000   Class :character   1st Qu.:1.000  
##  Median :1.0000   Median :3.000   Mode  :character   Median :2.000  
##  Mean   :0.7939   Mean   :2.799                      Mean   :2.064  
##  3rd Qu.:1.0000   3rd Qu.:3.000                      3rd Qu.:3.000  
##  Max.   :3.0000   Max.   :6.000                      Max.   :5.000  
##   job_title           overtime         business_travel     hourly_rate    
##  Length:1470        Length:1470        Length:1470        Min.   : 30.00  
##  Class :character   Class :character   Class :character   1st Qu.: 48.00  
##  Mode  :character   Mode  :character   Mode  :character   Median : 66.00  
##                                                           Mean   : 65.89  
##                                                           3rd Qu.: 83.75  
##                                                           Max.   :100.00  
##    daily_comp     monthly_comp    annual_comp      standard_hrs salary_hike_pct
##  Min.   :240.0   Min.   : 5200   Min.   : 62400   Min.   :80    Min.   :11.00  
##  1st Qu.:384.0   1st Qu.: 8320   1st Qu.: 99840   1st Qu.:80    1st Qu.:12.00  
##  Median :528.0   Median :11440   Median :137280   Median :80    Median :14.00  
##  Mean   :527.1   Mean   :11421   Mean   :137054   Mean   :80    Mean   :15.21  
##  3rd Qu.:670.0   3rd Qu.:14517   3rd Qu.:174200   3rd Qu.:80    3rd Qu.:18.00  
##  Max.   :800.0   Max.   :17333   Max.   :208000   Max.   :80    Max.   :25.00  
##   perf_rating    prior_emplr_cnt    env_sat        engagement      job_sat     
##  Min.   :3.000   Min.   :0.000   Min.   :1.000   Min.   :1.00   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.:2.00   1st Qu.:2.000  
##  Median :3.000   Median :2.000   Median :3.000   Median :3.00   Median :3.000  
##  Mean   :3.154   Mean   :2.693   Mean   :2.722   Mean   :2.73   Mean   :2.729  
##  3rd Qu.:3.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:3.00   3rd Qu.:4.000  
##  Max.   :4.000   Max.   :9.000   Max.   :4.000   Max.   :4.00   Max.   :4.000  
##     rel_sat        wl_balance       work_exp       org_tenure    
##  Min.   :1.000   Min.   :1.000   Min.   : 0.00   Min.   : 0.000  
##  1st Qu.:2.000   1st Qu.:2.000   1st Qu.: 6.00   1st Qu.: 3.000  
##  Median :3.000   Median :2.000   Median :10.00   Median : 5.000  
##  Mean   :2.712   Mean   :1.841   Mean   :11.28   Mean   : 7.032  
##  3rd Qu.:4.000   3rd Qu.:2.000   3rd Qu.:15.00   3rd Qu.: 9.000  
##  Max.   :4.000   Max.   :2.000   Max.   :40.00   Max.   :72.000  
##    job_tenure       last_promo       mgr_tenure    
##  Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  
##  1st Qu.: 2.000   1st Qu.: 0.000   1st Qu.: 2.000  
##  Median : 3.000   Median : 1.000   Median : 3.000  
##  Mean   : 4.229   Mean   : 2.188   Mean   : 4.123  
##  3rd Qu.: 7.000   3rd Qu.: 3.000   3rd Qu.: 7.000  
##  Max.   :18.000   Max.   :15.000   Max.   :17.000</code></pre>
<p>Note that fields with <code>NA's</code> contain missing values. Also, by default <code>employee_id</code> is treated as an integer in R, which is why descriptive statistics appropriate for numeric data are provided. <code>employee_id</code> should actually be treated as a character string since we will not perform any arithmetic operations using these ids.</p>
<p><strong>Missingness</strong></p>
<p>Before considering whether and how to handle missing data, it is important to distinguish between <em>structural missingness</em> and <em>informative missingness</em> (Kuhn &amp; Johnson, 2013).</p>
<p><strong>Structural missingness</strong> relates to data that are missing for a logical reason. For example, we would not expect a new joiner with a few days of tenure to have a performance score. Likewise, we would not expect an active employee who is not a rehire to have a termination date. Therefore, it would not make sense to define a value to address missing data in these cases.</p>
<p><strong>Informative missingness</strong> relates to missing data that is informative regarding an outcome of interest. For example, in a survey context we may find a relationship between missing values on manager effectiveness questions and unfavorability on a psychological safety scale. This may indicate that employees who are fearful of retaliation are uncomfortable providing honest feedback about their managers, while employees who feel it is safe to speak up about issues are more comfortable responding in prosocial ways.</p>
<p>In some cases, we have the luxury of simply removing observations with missing values and using the remaining complete cases for analysis. However, since we are often working with wide datasets containing relatively few observations in people analytics, this may not be feasible. As we will cover in later chapters, sample size considerations are fundamental to achieving adequate power in statistical testing, so case removal is only possible with larger datasets. Also, elimination of many impacted records – even with a sufficiently large sample – may bias analyses if there are missingness patterns.</p>
<p><strong>Data imputation</strong> refers to the methods by which missing data are replaced with substituted values when case removal is not appropriate. The most common data imputation method is replacing missing values with a descriptive statistic such as the mean, median, or mode based on available data. For example, if most employees have an age in the system, the average, median, or most frequent age could be used in place of the cases with a missing age. To be more precise, the average, median, or most frequent age of those with <em>similar characteristics</em> may be used (e.g., similar years of experience, job, level). We would expect there to be less variability in age within a well-defined segment relative to the entire employee population, so this would likely be a more accurate substitute for an individual’s actual age.</p>
<p>Let’s evaluate the <code>employees</code> data frame for missing <code>annual_comp</code> values using the logical <code>is.na()</code> function, and return values of variables relevant in determining one’s annual compensation:</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="data-wrang-prep.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store original annual comp for sample employee</span></span>
<span id="cb236-2"><a href="data-wrang-prep.html#cb236-2" aria-hidden="true" tabindex="-1"></a>orig_comp <span class="ot">&lt;-</span> <span class="fu">subset</span>(employees, employee_id <span class="sc">==</span> <span class="st">&#39;2176&#39;</span>, <span class="at">select =</span> annual_comp)</span>
<span id="cb236-3"><a href="data-wrang-prep.html#cb236-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb236-4"><a href="data-wrang-prep.html#cb236-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Force a NA in lieu of annual comp for illustrative purposes</span></span>
<span id="cb236-5"><a href="data-wrang-prep.html#cb236-5" aria-hidden="true" tabindex="-1"></a>employees[employees<span class="sc">$</span>employee_id <span class="sc">==</span> <span class="st">&#39;2176&#39;</span>, <span class="st">&#39;annual_comp&#39;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb236-6"><a href="data-wrang-prep.html#cb236-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb236-7"><a href="data-wrang-prep.html#cb236-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Return relevant employee characteristics where annual comp is missing</span></span>
<span id="cb236-8"><a href="data-wrang-prep.html#cb236-8" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(employees, <span class="fu">is.na</span>(annual_comp), <span class="at">select =</span> <span class="fu">c</span>(employee_id, job_title, job_lvl))</span></code></pre></div>
<pre><code>##      employee_id              job_title job_lvl
## 1176        2176 Manufacturing Director       2</code></pre>
<p>Next, we can impute the average value of <code>annual_comp</code> based on employees with the same values for the relevant variables:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="data-wrang-prep.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return average annual comp for employees with similar characteristics, excluding employees with missing comp values</span></span>
<span id="cb238-2"><a href="data-wrang-prep.html#cb238-2" aria-hidden="true" tabindex="-1"></a>imputed_comp <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">subset</span>(employees, job_title <span class="sc">==</span> <span class="st">&#39;Manufacturing Director&#39;</span> <span class="sc">&amp;</span> job_lvl <span class="sc">==</span> <span class="dv">2</span>, <span class="at">select =</span> annual_comp), mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb238-3"><a href="data-wrang-prep.html#cb238-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb238-4"><a href="data-wrang-prep.html#cb238-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Impute missing comp for relevant segment</span></span>
<span id="cb238-5"><a href="data-wrang-prep.html#cb238-5" aria-hidden="true" tabindex="-1"></a>employees[employees<span class="sc">$</span>employee_id <span class="sc">==</span> <span class="st">&#39;2176&#39;</span>, <span class="st">&#39;annual_comp&#39;</span>] <span class="ot">&lt;-</span> imputed_comp</span>
<span id="cb238-6"><a href="data-wrang-prep.html#cb238-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb238-7"><a href="data-wrang-prep.html#cb238-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display absolute difference between original and imputed comp</span></span>
<span id="cb238-8"><a href="data-wrang-prep.html#cb238-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">abs</span>(orig_comp <span class="sc">-</span> <span class="fu">subset</span>(employees, employee_id <span class="sc">==</span> <span class="st">&#39;2176&#39;</span>, <span class="at">select =</span> annual_comp)), <span class="dv">0</span>)</span></code></pre></div>
<pre><code>##      annual_comp
## 1176        1169</code></pre>
<p>While this approach should help in demonstrating the mechanics of imputing a missing value on a case-by-case basis, a more scalable solution is needed for data with a large number of missing values across employees with different values of these variables. There are more sophisticated methods of data imputation that involve models to estimate missing values. <em>Linear regression</em> and <em>K-Nearest Neighbor (KNN)</em> models are commonly used for this and will be covered in later chapters. These modeling techniques leverage a similar approach to the method outlined above in that the target values of cases with similar characteristics to those with missing values are used to aid estimation. <strong>Multiple imputation</strong> combines the information from multiple data sets imputed using different methods with a goal of minimizing the potential bias introduced by a singular method of imputation.</p>
<p><strong>Outliers</strong></p>
<p>The treatment of outliers is a controversial topic. Appropriate methods for defining and addressing outliers are domain-specific, and there are many important considerations that should inform whether and how outliers should be treated. As discussed in Chapter <a href="desc-stats.html#desc-stats">5</a>, a common method of outlier detection is identifying values which fall outside the following interval:</p>
<p><span class="math display">\[I = Q1 - 1.5 * IQR; Q3 + 1.5 * IQR\]</span></p>
<p><strong>Low Variability</strong></p>
<p>Variables with <strong>low variability</strong> often do not provide sufficient information for identifying patterns in data. For example, if we are interested in using information on stock options to understand why employees vary in their levels of retention risk, but find that the employee stock purchase plan (ESPP) terms are identical for nearly all employees, including a stock option variable in the analysis is unlikely to provide any meaningful signal.</p>
<p>When working with survey data, checking for <strong>straightlining</strong> should be an early data screening step. Straightlining refers to a constant response across all survey items, which may be evidence that the respondent lost motivation or was not attentive and thoughtful when taking the survey. Since straight-line responses may influence results, it is often best to discard these cases – especially when the sample size is adequately large for the planned analyses without them. If the same response is given for both positively and negatively worded versions of a question (e.g., comparing “I plan to be here in a year” to “I do not plan to be here in a year”), which we expect to be inversely related, this gives added support for discarding these responses.</p>
<p>Fields with low variability can be easily identified using descriptive statistics from the <code>summary()</code> function. If the <code>Min</code> and <code>Max</code> values are equal, there is no variability in the field’s values. Based on the following descriptives, we should remove <code>standard_hrs</code> from the data:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="data-wrang-prep.html#cb240-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return descriptives to understand distribution of standard hours</span></span>
<span id="cb240-2"><a href="data-wrang-prep.html#cb240-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(employees<span class="sc">$</span>standard_hrs)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      80      80      80      80      80      80</code></pre>
<p>Given that the data dictionary in Chapter <a href="getting-started.html#getting-started">1</a> indicates performance ratings range from 1 to 4, the following descriptives should raise red flags:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="data-wrang-prep.html#cb242-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return descriptives to understand distribution of standard hours</span></span>
<span id="cb242-2"><a href="data-wrang-prep.html#cb242-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(employees<span class="sc">$</span>perf_rating)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.000   3.000   3.000   3.154   3.000   4.000</code></pre>
<p>Assuming not everyone in the company is a stellar performer (i.e., only Noteworthy and Exceptional ratings), we may be working with a partial data set that could bias analyses. This may be due to poor integrity of performance data in the source system or repository from which the data were pulled, or the data may have been limited via a condition in the query.</p>
<p><strong>Inconsistent Categories</strong></p>
<p><strong>Inconsistent categories</strong> impact aggregation and trending by categorical dimensions. It is often necessary to create mappings based on logical rules in order to standardize dimension values across time. In the case of reorgs, a department may be disbanded, renamed, or integrated into one or multiple other departments. Therefore, when working with historical data, records may contain legacy department names that do not align with the current organizational taxonomy. Mapping from former to current departments may require logic based on manager ids, divisions, job profiles, locations, or other variables depending on the nature of reorgs over time.</p>
<p>Job architecture projects often introduce the need for mappings as well. Jobs and levels may completely change for all employees with a job architecture revamp, in which case trending along job and level dimensions (e.g., attrition by job or level over multiple years) is only possible with logic that clarifies how legacy jobs and levels map to those in the new career framework.</p>
<p>Changes to allowable values in source systems often result in inconsistent categorical data over time. For example, the education field may switch from a free-form text field in which employees can enter any value (e.g., B.S., B.A., BS, BA, Bachelor of Science, Bachelor of Arts, Bachelor’s, Bachelors, Bachelor’s Degree, Bachelor Degree, undergraduate degree, 4-year degree, four-year degree) to a standardized solution in which there is a clean and well-defined set of allowable values from which employees can choose (e.g., Bachelor’s Degree, Master’s Degree, Doctoral Degree). This warrants either a one-time historical cleanup upon implementing the allowable values or downstream logic to tidy up data for analytics. A best practice is to address data quality issues upstream (e.g., in the source system) to avoid duplicative data cleaning procedures across downstream applications.</p>
<p><strong>Data Binning</strong></p>
<p><strong>Data binning</strong> refers to the process by which larger high-level groups of values are defined and constructed. As a general rule, extremely granular categories should be avoided – especially when there is no theoretical basis for such categories facilitating a project’s objectives or deepening insights. Where the <span class="math inline">\(n\)</span>-count is expected to be consistently low for a defined categorical bin, it is usually best to define a larger bin. For example, a variable measuring highest level of educational attainment that contains 9th, 10th, 11th, and 12th grade categories may be converted into higher-level “High School Not Completed” and “High School Completed” bins.</p>
<p>For modeling applications, it is important to let the algorithm determine the cutpoints for numeric data in relation to the outcome. For example, if organization tenure is measured in years, arbitrarily defining bin sizes of ‘Less Than 1 Year’, ‘1-5 Years’, and ‘More Than 5 Years’ will likely result in information loss. Any variability <em>within</em> these bins that may be useful in explaining variance in the outcome would be lost with such wide bins. In fact, machine learning (ML) models such as decision trees, which will be covered in later chapters, are great for algorithmically determining cut points for binning numeric data across descriptive, diagnostic, and predictive projects alike.</p>
</div>
<div id="one-hot-encoding" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> One-Hot Encoding</h2>
<p><strong>One-hot encoding</strong>, also known as <strong>dummy coding</strong>, involves transforming a categorical variable into numeric values on which statistical procedures can be performed. For EDA, this is not required, as counts and percent of total metrics can be calculated on these dimensions for descriptive purposes. However, for statistical and ML modeling applications, categorical variables must be converted into <span class="math inline">\(k-1\)</span> variables, where <span class="math inline">\(k\)</span> is the number of categories, using binary (1/0) coding.</p>
<p>Understanding how categorical data are coded is critical to a correct interpretation of output. For example, if a remote work variable exists with “Remote” or “Non-Remote” values, we may code “Remote” values as 1 and “Non-Remote” values as 0. We could then evaluate the statistical relationship of this transformed categorical variable with other numeric variables.</p>
<p>If a categorical variable has more than 2 values, we must create a separate 1/0 field for each value and omit one category for use as a reference group. As we will cover in Chapter <a href="lm.html#lm">9</a>, one of several assumptions in linear regression is that independent variables are not collinear; that is no pair of independent variables is highly correlated. Without an omitted category, each of the one-hot encoded fields will be perfectly correlated with the others. That is, when the field representing category A is 1, the fields for other categories will always be 0. As illustrated in Figure <a href="data-wrang-prep.html#fig:onehot-encoding">7.7</a>, by omitting a category there will be cases when all fields have a 0 value (i.e., rows where the value is the omitted category), which will reduce the strength of the bivariate correlations.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:onehot-encoding"></span>
<img src="graphics/onehot_encoding.png" alt="One-Hot Encoding" width="75%" />
<p class="caption">
Figure 7.7: One-Hot Encoding
</p>
</div>
<p>For a categorical variable with only two values, the <code>ifelse()</code> function can be leveraged to assign values:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="data-wrang-prep.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return unique values of gender field</span></span>
<span id="cb244-2"><a href="data-wrang-prep.html#cb244-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(employees<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## [1] &quot;Female&quot; &quot;Male&quot;</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="data-wrang-prep.html#cb246-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gender one-hot encoding</span></span>
<span id="cb246-2"><a href="data-wrang-prep.html#cb246-2" aria-hidden="true" tabindex="-1"></a>employees<span class="sc">$</span>gender_ohe <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(employees<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">&#39;Female&#39;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb246-3"><a href="data-wrang-prep.html#cb246-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb246-4"><a href="data-wrang-prep.html#cb246-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview records</span></span>
<span id="cb246-5"><a href="data-wrang-prep.html#cb246-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">subset</span>(employees, <span class="at">select =</span> <span class="fu">c</span>(employee_id, gender_ohe)))</span></code></pre></div>
<pre><code>##   employee_id gender_ohe
## 1        1001          1
## 2        1002          0
## 3        1003          0
## 4        1004          1
## 5        1005          0
## 6        1006          0</code></pre>
<p>For variables with more than 2 categories, we can leverage the <code>model.matrix()</code> function for one-hot encoding. Let’s illustrate be encoding locations.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="data-wrang-prep.html#cb248-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return counts by department</span></span>
<span id="cb248-2"><a href="data-wrang-prep.html#cb248-2" aria-hidden="true" tabindex="-1"></a>employees <span class="sc">%&gt;%</span> <span class="fu">count</span>(dept, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##                     dept   n
## 1 Research &amp; Development 961
## 2                  Sales 446
## 3        Human Resources  63</code></pre>
<p>By default, the <code>model.matrix()</code> function will produce a matrix of 1/0 values for <span class="math inline">\(k-1\)</span> categories. The first column in the matrix is an intercept column containing a value of 1 for each row to ensure linear independence, and the default behavior results in the first value of the factor being the omitted group. For more flexibility over which value is omitted, we can drop the intercept using <code>-1</code> in the first argument passed to <code>model.matrix()</code> and then choose the reference group for the analysis in a subsequent step.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="data-wrang-prep.html#cb250-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Department one-hot encoding</span></span>
<span id="cb250-2"><a href="data-wrang-prep.html#cb250-2" aria-hidden="true" tabindex="-1"></a>dept_ohe <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>dept<span class="dv">-1</span>, <span class="at">data =</span> employees)</span>
<span id="cb250-3"><a href="data-wrang-prep.html#cb250-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb250-4"><a href="data-wrang-prep.html#cb250-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview data</span></span>
<span id="cb250-5"><a href="data-wrang-prep.html#cb250-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dept_ohe)</span></code></pre></div>
<pre><code>##   deptHuman Resources deptResearch &amp; Development deptSales
## 1                   0                          0         1
## 2                   0                          1         0
## 3                   0                          1         0
## 4                   0                          1         0
## 5                   0                          1         0
## 6                   0                          1         0</code></pre>
<p>We will drop the department with the lowest <span class="math inline">\(n\)</span> rather than the more arbitrary method based on the first value of the factor. Since departments are coded as either <span class="math inline">\(1\)</span> or <span class="math inline">\(0\)</span>, we can use the <code>colSums()</code> function to sum each column and the <code>which.min()</code> function to identify which has the lowest sum (i.e., smallest department by employee count).</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="data-wrang-prep.html#cb252-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop department with lowest sum (lowest n-count)</span></span>
<span id="cb252-2"><a href="data-wrang-prep.html#cb252-2" aria-hidden="true" tabindex="-1"></a>dept_ohe <span class="ot">&lt;-</span> dept_ohe[, <span class="sc">-</span><span class="fu">which.min</span>(<span class="fu">colSums</span>(dept_ohe))]</span>
<span id="cb252-3"><a href="data-wrang-prep.html#cb252-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb252-4"><a href="data-wrang-prep.html#cb252-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview refined one-hot encoded data</span></span>
<span id="cb252-5"><a href="data-wrang-prep.html#cb252-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dept_ohe)</span></code></pre></div>
<pre><code>##   deptResearch &amp; Development deptSales
## 1                          0         1
## 2                          1         0
## 3                          1         0
## 4                          1         0
## 5                          1         0
## 6                          1         0</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="data-wrang-prep.html#cb254-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine employees and matrix containing one-hot encoded departments</span></span>
<span id="cb254-2"><a href="data-wrang-prep.html#cb254-2" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">cbind</span>(employees, dept_ohe)</span>
<span id="cb254-3"><a href="data-wrang-prep.html#cb254-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb254-4"><a href="data-wrang-prep.html#cb254-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop original department field</span></span>
<span id="cb254-5"><a href="data-wrang-prep.html#cb254-5" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">subset</span>(employees, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(dept))</span></code></pre></div>
</div>
<div id="feature-engineering" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Feature Engineering</h2>
<p>Level one people analytics tends to utilize only the delivered fields from the HRIS (e.g., location, job profile, org tenure), but a good next step is to derive smarter variables from these fields. These can then be used to cut data differently or as inputs in models. Below are some examples of how basic data available in the HRIS can be transformed into new variables that provide different information. This can be easily accomplished using the arithmetic functions we’ve covered.</p>
<ul>
<li>Number of jobs per unit of tenure (larger proportions tend to see greater career pathing)</li>
<li>Office/remote worker (binary variable dummy coded as 1/0)</li>
<li>Local/remote manager (binary variable dummy coded as 1/0)</li>
<li>Hire/Rehire (binary variable dummy coded as 1/0)</li>
<li>Hired/acquired (proxy for culture shock effects)</li>
<li>Gender isolation (ratio of employee’s gender to number of the same within immediate work
group)</li>
<li>Generation isolation (comparison of age bracket to most frequent generational bracket within
immediate work group)</li>
<li>Ethnic isolation (ratio of employee’s ethnicity to number of the same within immediate work
group)</li>
<li>Difference between employee and manager age</li>
<li>Percentage change between last two performance appraisal scores (per competency and/or
overall)</li>
<li>Team and department quit outbreak indicators (ratio of terms over x months relative to average
headcount over x months)</li>
<li>Industry experience (binary or length in years)</li>
</ul>
</div>
<div id="review-questions-5" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> Review Questions</h2>
<ol style="list-style-type: decimal">
<li><p>What are the differences between data lakes, data warehouses, and data marts?</p></li>
<li><p>What is the difference between a Type 1 and Type 2 table in a DW?</p></li>
<li><p>What two clauses must always be present in a SQL query?</p></li>
<li><p>How do aggregate functions differ from window functions in SQL?</p></li>
<li><p>What is a subquery?</p></li>
<li><p>What is the difference between an INNER JOIN and LEFT JOIN?</p></li>
<li><p>Why is it dangeous to address missing values without domain knowledge of how the data are generated?</p></li>
<li><p>How can missing values be addressed when impacted records cannot be eliminated from a data set?</p></li>
<li><p>When is one-hot encoding required for categorical variables?</p></li>
<li><p>Why should variables with low to no variability be dropped?</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inf-stats.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aod.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["People_Analytics_Lifecycle.pdf", "People_Analytics_Lifecycle.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
