<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Data Wrangling | An Introduction to the People Analytics Lifecycle: With Applications in R</title>
  <meta name="description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="generator" content="bookdown 0.24.4 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Data Wrangling | An Introduction to the People Analytics Lifecycle: With Applications in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="github-repo" content="crstarbuck/peopleanalytics-lifecycle-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Data Wrangling | An Introduction to the People Analytics Lifecycle: With Applications in R" />
  
  <meta name="twitter:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  

<meta name="author" content="Craig Starbuck" />


<meta name="date" content="2022-06-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inf-stats.html"/>
<link rel="next" href="data-prep.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<link href="libs/tabwid-1.0.0/scrool.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">An Introduction to the People Analytics Lifecycle: With Applications in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#guiding-principles"><i class="fa fa-check"></i><b>1.1</b> Guiding Principles</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="getting-started.html"><a href="getting-started.html#pro-employee-thinking"><i class="fa fa-check"></i><b>1.1.1</b> Pro Employee Thinking</a></li>
<li class="chapter" data-level="1.1.2" data-path="getting-started.html"><a href="getting-started.html#quality"><i class="fa fa-check"></i><b>1.1.2</b> Quality</a></li>
<li class="chapter" data-level="1.1.3" data-path="getting-started.html"><a href="getting-started.html#prioritization"><i class="fa fa-check"></i><b>1.1.3</b> Prioritization</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#tools"><i class="fa fa-check"></i><b>1.2</b> Tools</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="getting-started.html"><a href="getting-started.html#r"><i class="fa fa-check"></i><b>1.2.1</b> R</a></li>
<li class="chapter" data-level="1.2.2" data-path="getting-started.html"><a href="getting-started.html#data"><i class="fa fa-check"></i><b>1.2.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#d-framework"><i class="fa fa-check"></i><b>1.3</b> 4D Framework</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="getting-started.html"><a href="getting-started.html#discover"><i class="fa fa-check"></i><b>1.3.1</b> Discover</a></li>
<li class="chapter" data-level="1.3.2" data-path="getting-started.html"><a href="getting-started.html#design"><i class="fa fa-check"></i><b>1.3.2</b> Design</a></li>
<li class="chapter" data-level="1.3.3" data-path="getting-started.html"><a href="getting-started.html#develop"><i class="fa fa-check"></i><b>1.3.3</b> Develop</a></li>
<li class="chapter" data-level="1.3.4" data-path="getting-started.html"><a href="getting-started.html#deliver"><i class="fa fa-check"></i><b>1.3.4</b> Deliver</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-intro.html"><a href="r-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-intro.html"><a href="r-intro.html#getting-started-1"><i class="fa fa-check"></i><b>2.1</b> Getting Started</a></li>
<li class="chapter" data-level="2.2" data-path="r-intro.html"><a href="r-intro.html#vectors"><i class="fa fa-check"></i><b>2.2</b> Vectors</a></li>
<li class="chapter" data-level="2.3" data-path="r-intro.html"><a href="r-intro.html#matrices"><i class="fa fa-check"></i><b>2.3</b> Matrices</a></li>
<li class="chapter" data-level="2.4" data-path="r-intro.html"><a href="r-intro.html#factors"><i class="fa fa-check"></i><b>2.4</b> Factors</a></li>
<li class="chapter" data-level="2.5" data-path="r-intro.html"><a href="r-intro.html#data-frames"><i class="fa fa-check"></i><b>2.5</b> Data Frames</a></li>
<li class="chapter" data-level="2.6" data-path="r-intro.html"><a href="r-intro.html#lists"><i class="fa fa-check"></i><b>2.6</b> Lists</a></li>
<li class="chapter" data-level="2.7" data-path="r-intro.html"><a href="r-intro.html#loops"><i class="fa fa-check"></i><b>2.7</b> Loops</a></li>
<li class="chapter" data-level="2.8" data-path="r-intro.html"><a href="r-intro.html#user-defined-functions-udfs"><i class="fa fa-check"></i><b>2.8</b> User-Defined Functions (UDFs)</a></li>
<li class="chapter" data-level="2.9" data-path="r-intro.html"><a href="r-intro.html#graphics"><i class="fa fa-check"></i><b>2.9</b> Graphics</a></li>
<li class="chapter" data-level="2.10" data-path="r-intro.html"><a href="r-intro.html#review-questions"><i class="fa fa-check"></i><b>2.10</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="measure-sampl.html"><a href="measure-sampl.html"><i class="fa fa-check"></i><b>3</b> Measurement &amp; Sampling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#variable-types"><i class="fa fa-check"></i><b>3.1</b> Variable Types</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="measure-sampl.html"><a href="measure-sampl.html#independent-variables-iv"><i class="fa fa-check"></i><b>3.1.1</b> Independent Variables (IV)</a></li>
<li class="chapter" data-level="3.1.2" data-path="measure-sampl.html"><a href="measure-sampl.html#dependent-variables-dv"><i class="fa fa-check"></i><b>3.1.2</b> Dependent Variables (DV)</a></li>
<li class="chapter" data-level="3.1.3" data-path="measure-sampl.html"><a href="measure-sampl.html#control-variables-cv"><i class="fa fa-check"></i><b>3.1.3</b> Control Variables (CV)</a></li>
<li class="chapter" data-level="3.1.4" data-path="measure-sampl.html"><a href="measure-sampl.html#moderating-variables"><i class="fa fa-check"></i><b>3.1.4</b> Moderating Variables</a></li>
<li class="chapter" data-level="3.1.5" data-path="measure-sampl.html"><a href="measure-sampl.html#mediating-variables"><i class="fa fa-check"></i><b>3.1.5</b> Mediating Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="measure-sampl.html"><a href="measure-sampl.html#measurement-scales"><i class="fa fa-check"></i><b>3.2</b> Measurement Scales</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="measure-sampl.html"><a href="measure-sampl.html#discrete-variables"><i class="fa fa-check"></i><b>3.2.1</b> Discrete Variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="measure-sampl.html"><a href="measure-sampl.html#continuous-variables"><i class="fa fa-check"></i><b>3.2.2</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling"><i class="fa fa-check"></i><b>3.3</b> Sampling</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-nonsampling-error"><i class="fa fa-check"></i><b>3.3.1</b> Sampling &amp; Nonsampling Error</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="measure-sampl.html"><a href="measure-sampl.html#review-questions-1"><i class="fa fa-check"></i><b>3.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="research.html"><a href="research.html"><i class="fa fa-check"></i><b>4</b> Research Fundamentals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="research.html"><a href="research.html#research-questions"><i class="fa fa-check"></i><b>4.1</b> Research Questions</a></li>
<li class="chapter" data-level="4.2" data-path="research.html"><a href="research.html#research-hypotheses"><i class="fa fa-check"></i><b>4.2</b> Research Hypotheses</a></li>
<li class="chapter" data-level="4.3" data-path="research.html"><a href="research.html#internal-vs.-external-validity"><i class="fa fa-check"></i><b>4.3</b> Internal vs. External Validity</a></li>
<li class="chapter" data-level="4.4" data-path="research.html"><a href="research.html#research-methods"><i class="fa fa-check"></i><b>4.4</b> Research Methods</a></li>
<li class="chapter" data-level="4.5" data-path="research.html"><a href="research.html#research-designs"><i class="fa fa-check"></i><b>4.5</b> Research Designs</a></li>
<li class="chapter" data-level="4.6" data-path="research.html"><a href="research.html#review-questions-2"><i class="fa fa-check"></i><b>4.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="desc-stats.html"><a href="desc-stats.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="5.1" data-path="desc-stats.html"><a href="desc-stats.html#univariate-analysis"><i class="fa fa-check"></i><b>5.1</b> Univariate Analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>5.1.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="5.1.2" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-spread"><i class="fa fa-check"></i><b>5.1.2</b> Measures of Spread</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="desc-stats.html"><a href="desc-stats.html#bivariate-analysis"><i class="fa fa-check"></i><b>5.2</b> Bivariate Analysis</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="desc-stats.html"><a href="desc-stats.html#covariance"><i class="fa fa-check"></i><b>5.2.1</b> Covariance</a></li>
<li class="chapter" data-level="5.2.2" data-path="desc-stats.html"><a href="desc-stats.html#correlation"><i class="fa fa-check"></i><b>5.2.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="desc-stats.html"><a href="desc-stats.html#review-questions-3"><i class="fa fa-check"></i><b>5.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inf-stats.html"><a href="inf-stats.html"><i class="fa fa-check"></i><b>6</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inf-stats.html"><a href="inf-stats.html#introduction-to-probability"><i class="fa fa-check"></i><b>6.1</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="inf-stats.html"><a href="inf-stats.html#probability-distributions"><i class="fa fa-check"></i><b>6.1.1</b> Probability Distributions</a></li>
<li class="chapter" data-level="6.1.2" data-path="inf-stats.html"><a href="inf-stats.html#conditional-probability"><i class="fa fa-check"></i><b>6.1.2</b> Conditional Probability</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inf-stats.html"><a href="inf-stats.html#central-limit-theorem"><i class="fa fa-check"></i><b>6.2</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="6.3" data-path="inf-stats.html"><a href="inf-stats.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="inf-stats.html"><a href="inf-stats.html#hypothesis-testing"><i class="fa fa-check"></i><b>6.3.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="6.3.2" data-path="inf-stats.html"><a href="inf-stats.html#alpha"><i class="fa fa-check"></i><b>6.3.2</b> Alpha</a></li>
<li class="chapter" data-level="6.3.3" data-path="inf-stats.html"><a href="inf-stats.html#type-i-ii-errors"><i class="fa fa-check"></i><b>6.3.3</b> Type I &amp; II Errors</a></li>
<li class="chapter" data-level="6.3.4" data-path="inf-stats.html"><a href="inf-stats.html#p-values"><i class="fa fa-check"></i><b>6.3.4</b> <span class="math inline">\(p\)</span>-Values</a></li>
<li class="chapter" data-level="6.3.5" data-path="inf-stats.html"><a href="inf-stats.html#bonferroni-correction"><i class="fa fa-check"></i><b>6.3.5</b> Bonferroni Correction</a></li>
<li class="chapter" data-level="6.3.6" data-path="inf-stats.html"><a href="inf-stats.html#statistical-power"><i class="fa fa-check"></i><b>6.3.6</b> Statistical Power</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="inf-stats.html"><a href="inf-stats.html#review-questions-4"><i class="fa fa-check"></i><b>6.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-wrangl.html"><a href="data-wrangl.html"><i class="fa fa-check"></i><b>7</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangl.html"><a href="data-wrangl.html#data-management"><i class="fa fa-check"></i><b>7.1</b> Data Management</a></li>
<li class="chapter" data-level="7.2" data-path="data-wrangl.html"><a href="data-wrangl.html#sql"><i class="fa fa-check"></i><b>7.2</b> SQL</a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangl.html"><a href="data-wrangl.html#review-questions-5"><i class="fa fa-check"></i><b>7.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-prep.html"><a href="data-prep.html"><i class="fa fa-check"></i><b>8</b> Data Preparation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-prep.html"><a href="data-prep.html#data-screening-cleaning"><i class="fa fa-check"></i><b>8.1</b> Data Screening &amp; Cleaning</a></li>
<li class="chapter" data-level="8.2" data-path="data-prep.html"><a href="data-prep.html#one-hot-encoding"><i class="fa fa-check"></i><b>8.2</b> One-Hot Encoding</a></li>
<li class="chapter" data-level="8.3" data-path="data-prep.html"><a href="data-prep.html#feature-engineering"><i class="fa fa-check"></i><b>8.3</b> Feature Engineering</a></li>
<li class="chapter" data-level="8.4" data-path="data-prep.html"><a href="data-prep.html#review-questions-6"><i class="fa fa-check"></i><b>8.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="aod.html"><a href="aod.html"><i class="fa fa-check"></i><b>9</b> Analysis of Differences</a>
<ul>
<li class="chapter" data-level="9.1" data-path="aod.html"><a href="aod.html#parametric-vs.-nonparametric-tests"><i class="fa fa-check"></i><b>9.1</b> Parametric vs. Nonparametric Tests</a></li>
<li class="chapter" data-level="9.2" data-path="aod.html"><a href="aod.html#differences-in-discrete-data"><i class="fa fa-check"></i><b>9.2</b> Differences in Discrete Data</a></li>
<li class="chapter" data-level="9.3" data-path="aod.html"><a href="aod.html#differences-in-continuous-data"><i class="fa fa-check"></i><b>9.3</b> Differences in Continuous Data</a></li>
<li class="chapter" data-level="9.4" data-path="aod.html"><a href="aod.html#review-questions-7"><i class="fa fa-check"></i><b>9.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lm.html"><a href="lm.html"><i class="fa fa-check"></i><b>10</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="lm.html"><a href="lm.html#sample-size"><i class="fa fa-check"></i><b>10.1</b> Sample Size</a></li>
<li class="chapter" data-level="10.2" data-path="lm.html"><a href="lm.html#simple-linear-regression"><i class="fa fa-check"></i><b>10.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="10.3" data-path="lm.html"><a href="lm.html#multiple-linear-regression"><i class="fa fa-check"></i><b>10.3</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="10.4" data-path="lm.html"><a href="lm.html#model-comparisons"><i class="fa fa-check"></i><b>10.4</b> Model Comparisons</a></li>
<li class="chapter" data-level="10.5" data-path="lm.html"><a href="lm.html#multilevel-models"><i class="fa fa-check"></i><b>10.5</b> Multilevel Models</a></li>
<li class="chapter" data-level="10.6" data-path="lm.html"><a href="lm.html#moderation"><i class="fa fa-check"></i><b>10.6</b> Moderation</a></li>
<li class="chapter" data-level="10.7" data-path="lm.html"><a href="lm.html#mediation"><i class="fa fa-check"></i><b>10.7</b> Mediation</a></li>
<li class="chapter" data-level="10.8" data-path="lm.html"><a href="lm.html#review-questions-8"><i class="fa fa-check"></i><b>10.8</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="lme.html"><a href="lme.html"><i class="fa fa-check"></i><b>11</b> Non-Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="lme.html"><a href="lme.html#polynomial-regression"><i class="fa fa-check"></i><b>11.1</b> Polynomial Regression</a></li>
<li class="chapter" data-level="11.2" data-path="lme.html"><a href="lme.html#logistic-regression"><i class="fa fa-check"></i><b>11.2</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="lme.html"><a href="lme.html#binomial-logistic-regression"><i class="fa fa-check"></i><b>11.2.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="11.2.2" data-path="lme.html"><a href="lme.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>11.2.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="11.2.3" data-path="lme.html"><a href="lme.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>11.2.3</b> Ordinal Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="lme.html"><a href="lme.html#review-questions-9"><i class="fa fa-check"></i><b>11.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pred-mod.html"><a href="pred-mod.html"><i class="fa fa-check"></i><b>12</b> Predictive Models</a>
<ul>
<li class="chapter" data-level="12.1" data-path="pred-mod.html"><a href="pred-mod.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>12.1</b> Bias-Variance Trade-Off</a></li>
<li class="chapter" data-level="12.2" data-path="pred-mod.html"><a href="pred-mod.html#cross-validation"><i class="fa fa-check"></i><b>12.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="12.3" data-path="pred-mod.html"><a href="pred-mod.html#balancing-classes"><i class="fa fa-check"></i><b>12.3</b> Balancing Classes</a></li>
<li class="chapter" data-level="12.4" data-path="pred-mod.html"><a href="pred-mod.html#model-performance"><i class="fa fa-check"></i><b>12.4</b> Model Performance</a></li>
<li class="chapter" data-level="12.5" data-path="pred-mod.html"><a href="pred-mod.html#automated-machine-learning-automl"><i class="fa fa-check"></i><b>12.5</b> Automated Machine Learning (AutoML)</a></li>
<li class="chapter" data-level="12.6" data-path="pred-mod.html"><a href="pred-mod.html#review-questions-10"><i class="fa fa-check"></i><b>12.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="unsup-lrn.html"><a href="unsup-lrn.html"><i class="fa fa-check"></i><b>13</b> Unsupervised Learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#factor-analysis"><i class="fa fa-check"></i><b>13.1</b> Factor Analysis</a></li>
<li class="chapter" data-level="13.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#clustering"><i class="fa fa-check"></i><b>13.2</b> Clustering</a></li>
<li class="chapter" data-level="13.3" data-path="unsup-lrn.html"><a href="unsup-lrn.html#review-questions-11"><i class="fa fa-check"></i><b>13.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="data-viz.html"><a href="data-viz.html"><i class="fa fa-check"></i><b>14</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="14.1" data-path="data-viz.html"><a href="data-viz.html#design-guidelines"><i class="fa fa-check"></i><b>14.1</b> Design Guidelines</a></li>
<li class="chapter" data-level="14.2" data-path="data-viz.html"><a href="data-viz.html#visualization-types"><i class="fa fa-check"></i><b>14.2</b> Visualization Types</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="data-viz.html"><a href="data-viz.html#tables"><i class="fa fa-check"></i><b>14.2.1</b> Tables</a></li>
<li class="chapter" data-level="14.2.2" data-path="data-viz.html"><a href="data-viz.html#heatmaps"><i class="fa fa-check"></i><b>14.2.2</b> Heatmaps</a></li>
<li class="chapter" data-level="14.2.3" data-path="data-viz.html"><a href="data-viz.html#scatterplots"><i class="fa fa-check"></i><b>14.2.3</b> Scatterplots</a></li>
<li class="chapter" data-level="14.2.4" data-path="data-viz.html"><a href="data-viz.html#line-graphs"><i class="fa fa-check"></i><b>14.2.4</b> Line Graphs</a></li>
<li class="chapter" data-level="14.2.5" data-path="data-viz.html"><a href="data-viz.html#slopegraphs"><i class="fa fa-check"></i><b>14.2.5</b> Slopegraphs</a></li>
<li class="chapter" data-level="14.2.6" data-path="data-viz.html"><a href="data-viz.html#bar-charts"><i class="fa fa-check"></i><b>14.2.6</b> Bar Charts</a></li>
<li class="chapter" data-level="14.2.7" data-path="data-viz.html"><a href="data-viz.html#waterfall-charts"><i class="fa fa-check"></i><b>14.2.7</b> Waterfall Charts</a></li>
<li class="chapter" data-level="14.2.8" data-path="data-viz.html"><a href="data-viz.html#area-charts"><i class="fa fa-check"></i><b>14.2.8</b> Area Charts</a></li>
<li class="chapter" data-level="14.2.9" data-path="data-viz.html"><a href="data-viz.html#pie-charts"><i class="fa fa-check"></i><b>14.2.9</b> Pie Charts</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="data-viz.html"><a href="data-viz.html#review-questions-12"><i class="fa fa-check"></i><b>14.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="storytelling.html"><a href="storytelling.html"><i class="fa fa-check"></i><b>15</b> Data Storytelling</a>
<ul>
<li class="chapter" data-level="15.1" data-path="storytelling.html"><a href="storytelling.html#know-your-audience"><i class="fa fa-check"></i><b>15.1</b> Know Your Audience</a></li>
<li class="chapter" data-level="15.2" data-path="storytelling.html"><a href="storytelling.html#tldr"><i class="fa fa-check"></i><b>15.2</b> TL;DR</a></li>
<li class="chapter" data-level="15.3" data-path="storytelling.html"><a href="storytelling.html#telling-the-story"><i class="fa fa-check"></i><b>15.3</b> Telling the Story</a></li>
<li class="chapter" data-level="15.4" data-path="storytelling.html"><a href="storytelling.html#reference-material"><i class="fa fa-check"></i><b>15.4</b> Reference Material</a></li>
<li class="chapter" data-level="15.5" data-path="storytelling.html"><a href="storytelling.html#review-questions-13"><i class="fa fa-check"></i><b>15.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="bibli.html"><a href="bibli.html"><i class="fa fa-check"></i><b>16</b> Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to the People Analytics Lifecycle</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrangl" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Data Wrangling</h1>
<p>To begin a data analysis, we must first access and organize the relevant data. These tasks – together with data preparation steps outlined in Chapter <a href="data-prep.html#data-prep">8</a> – account for a large part of the work analytics professionals do.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ds-tasks"></span>
<img src="graphics/data_scientist_tasks.jpeg" alt="What Data Scientists Really Do" width="75%" />
<p class="caption">
Figure 7.1: What Data Scientists Really Do
</p>
</div>
<div id="data-management" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Data Management</h2>
<p>Data are generally extracted directly from the source systems in which they are generated or from downstream repositories such as a <em>data lake</em>, <em>data warehouse</em>, or <em>data mart</em>.</p>
<p>A <strong>data lake</strong> stores myriad types of data – both structured and unstructured – in its native format until needed. <strong>Structured data</strong> refers to data that fits a predefined data model, such as hire dates formatted as <code>MM/DD/YYYY</code> or zip codes stored as a five-digit string. <strong>Unstructured data</strong> has no predefined data model, such as audio and video files, free-form performance review comments, emails, or digital exhaust from messaging tools; it is difficult to structure this type of data within a set of related tables.</p>
<p>The main difference between a data lake and data warehouse is the type of data they are designed to store. A <strong>data warehouse (DW)</strong> is designed to support analytics across large collections of data, such as transactional data (e.g., point-of-sale systems), point-in-time snapshots (e.g., month-end close reports), survey responses, spreadsheets, and more. As shown in Figure <a href="data-wrangl.html#fig:dw-schema">7.2</a>, data in a DW are structured and organized into schemas of related tables to enhance the performance of queries spanning sets of large and diverse data.</p>
<p>Figure <a href="data-wrangl.html#fig:dw-schema">7.2</a> illustrates how worker, position, and recruiting schemas may be related. For example, a candidate submits a job application to a posted requisition, which is connected to an open position Finance approved as part of the company’s workforce plan; when the selected candidate is hired, they become a worker with one or many events (hire, promotion, transfer, termination) and activities (learning, performance appraisals, surveys) during their tenure with the company.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dw-schema"></span>
<img src="graphics/dw_schema.png" alt="Related Tables Organized within Schemas" width="100%" />
<p class="caption">
Figure 7.2: Related Tables Organized within Schemas
</p>
</div>
<p>Tables in a DW are related using a set of keys. Each table needs a <strong>Primary Key (PK)</strong>, which is a unique identifier for each row in the table. A PK may be a single column or multiple columns; a multi-column PK is often referred to as a <em>composite key</em>. It is generally best to leverage non-recyclable system-generated ids for PKs, as descriptors like names tend to be unreliable. A <strong>Foreign Key (FK)</strong> is a column whose values correspond to the values of a PK in another table. <strong>Referential integrity</strong> is the logical dependency of a FK on a PK, and these constraints protect against orphaned FK values in child tables by deleting PK values from an associated parent table.</p>
<p>Figure <a href="data-wrangl.html#fig:dw-erd">7.3</a> shows an <strong>Entity Relationship Diagram (ERD)</strong> that depicts PK/FK relationships among the Position, Worker, and Requisition tables. Notice that the PK of each related table shown in Figure <a href="data-wrangl.html#fig:dw-schema">7.2</a> is listed as a FK.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dw-erd"></span>
<img src="graphics/dw_erd.png" alt="Entity Relationship Diagram (ERD)" width="75%" />
<p class="caption">
Figure 7.3: Entity Relationship Diagram (ERD)
</p>
</div>
<p>A DW may contain many different types of tables, but this chapter will focus on the two most common which are known as <em>Type 1</em> and <em>Type 2</em> tables. These tables are sometimes referred to as <strong>slowly changing dimensions (SCD)</strong>. A <strong>Type 1 table</strong> is overwritten on a regular cadence (usually daily) and contains no history – only current values. For example, a Type 1 table may contain the latest known attributes for each active and terminated worker such as job, location, and manager. A Type 1 table is convenient when only current information needs to be queried. A <strong>Type 2 table</strong> is a table in which a new record is inserted when a change occurs for one or more specified dimensions. Jobs, managers, and locations are examples of slowly changing dimensions but unlike the Type 1 table which contains only the latest information, the Type 2 table houses a <em>start date</em> and <em>end date</em> for each worker and dimension to facilitate reporting and analysis on changes to attribute values over time.</p>
<p>Figure <a href="data-wrangl.html#fig:type-2-tbl">7.4</a> illustrates the design of a Type 2 SCD for an active worker’s job, manager, and location changes. As the data show, worker 123 was promoted from Data Analyst to Sr. Data Analyst 1.5 years after joining, began reporting to their original manager (456) after a short stint reporting to someone else (789), and has worked remotely throughout their tenure with the company.</p>
<p>Note that the combination of <code>end_date = '12/31/9999'</code> and <code>current_record = 'Y'</code> indicate <em>current attributes</em> for active workers. For inactive workers, <code>end_date</code> is set to the worker’s termination date for rows that represent the <em>last known attributes</em> along with <code>current_record = 'Y'</code>:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:type-2-tbl"></span>
<img src="graphics/type_2_table.png" alt="Type 2 SCD" width="100%" />
<p class="caption">
Figure 7.4: Type 2 SCD
</p>
</div>
<p>While we could select rows where <code>current_record = 'Y'</code> to construct a view of the last known attributes for each worker in this table, the task would be unnecessarily complex. Using a Type 1 table simplifies the task and output since each dimension value is stored in a separate column and there is only one row per employee. Figure <a href="data-wrangl.html#fig:type-1-tbl">7.5</a> shows how the current record for worker 123 would look in a Type 1 SCD:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:type-1-tbl"></span>
<img src="graphics/type_1_table.png" alt="Type 1 SCD" width="100%" />
<p class="caption">
Figure 7.5: Type 1 SCD
</p>
</div>
<p>A <strong>data mart</strong> is a subset of a DW designed to easily deliver specific information to a certain set of users on a particular subject or for a well-defined use case. For example, in a people analytics context a diversity data mart could be developed to better isolate and secure restricted data such as gender and ethnicity. This data may be used to support diversity descriptives and trends for a limited audience approved by Data Privacy and Employment Law counsel based on justified business needs.</p>
<p><strong>Modern Data Architecture</strong></p>
<p>Though a deep treatment of data architecture is beyond the scope of this book, it is important to acknowledge the significant advancements in infrastructure and computation since these complex SCD architectures were introduced by Kimball (1996). These developments have greatly improved the efficiency with which analysts can translate data into information and insight. The primitive systems in place decades ago required expensive <strong>ETL</strong> jobs to <strong>extract (E)</strong> data from source systems, <strong>transform (T)</strong> data using complex transformation rules, and <strong>load (L)</strong> the transformed data to relational tables – which then required complex queries to wrangle and analyze the data.</p>
<p>With modern cloud environments, the significant investment associated with humans designing, developing, and maintaining these complex architectures is often difficult to justify given how inexpensive storage and compute have become. Increasingly, the heavy computational tasks have migrated out of data pipelines and into the analytics layer wherein analytics teams have more flexibility and control. Today, daily snapshots containing <em>all</em> current and historical records can be copied and stored within partitioned DW tables for a negligible increase in storage costs, and this greatly simplifies data pipeline complexity and engineering support requirements. This changing dynamic has given rise to a new breed of data engineers focused on optimizing the heavy computation requirements of analytics teams.</p>
</div>
<div id="sql" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> SQL</h2>
<p><strong>Structured Query Language (SQL)</strong> is the most common language used to extract and wrangle data contained in a relational database. SQL is an essential skill for anyone working in analytics.</p>
<p>When working with large datasets, it is best to filter records on the database side to avoid reading superfluous records into an analytics tool such as R only to then filter data to the relevant subset. For example, if we are performing an analysis on employees in the Engineering department, we should ideally filter to this subset on the database side rather than loading into R data on the entire workforce before filtering down to the relevant records. Fewer records can help enhance the performance of R scripts – especially when R is running on a local machine, such as a laptop, rather than on a more powerful server.</p>
<p><strong>Basics</strong></p>
<p>There are three main <em>clauses</em> in a SQL query: (a) <code>SELECT</code>, (b) <code>FROM</code>, and (c) <code>WHERE</code>. The <code>SELECT</code> and <code>FROM</code> clauses are required, though the optional <code>WHERE</code> clause is frequently needed.</p>
<ul>
<li><strong>SELECT</strong>: Specifies the columns to include in the output</li>
<li><strong>FROM</strong>: Specifies the table(s) in which the relevant data are contained</li>
<li><strong>WHERE</strong>: Specifies the rows to search</li>
</ul>
<p>Despite the clauses being ordered as shown above (<code>SELECT</code> then <code>FROM</code> then <code>WHERE</code>), the <code>FROM</code> clause is the first to execute since we first need to identify the relevant table(s) before filtering rows and selecting columns. The <code>SELECT</code> clause is the last to execute.</p>
<p>Additional clauses are available for grouping and sorting data.</p>
<ul>
<li><strong>GROUP BY</strong>: Specifies the columns by which data should be grouped when using aggregate functions</li>
<li><strong>HAVING</strong>: Specifies conditions for filtering rows based on aggregate functions</li>
<li><strong>ORDER BY</strong>: Specifies how data should be sorted in the output</li>
</ul>
<p>When implementing aggregate functions in a <code>SELECT</code> clause, such as counting, summing, or averaging a numeric field, all other non-aggregated fields must be included in the <code>GROUP BY</code> clause.</p>
<p>Though it is important to execute SQL queries directly on the database to minimize the amount of data read into R, we will use the <code>sqldf</code> library within R to demonstrate the mechanics of a SQL query for easily replicable examples. The <code>sqldf</code> library allows us to write SQL to query a data frame in R in lieu of a database. While the syntax of SQL may vary by database, the core structure of queries is universal.</p>
<p>First, let’s load the data sets:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="data-wrangl.html#cb200-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets</span></span>
<span id="cb200-2"><a href="data-wrangl.html#cb200-2" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/employees.csv&quot;</span>)</span>
<span id="cb200-3"><a href="data-wrangl.html#cb200-3" aria-hidden="true" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/status.csv&quot;</span>)</span>
<span id="cb200-4"><a href="data-wrangl.html#cb200-4" aria-hidden="true" tabindex="-1"></a>benefits <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/benefits.csv&quot;</span>)</span>
<span id="cb200-5"><a href="data-wrangl.html#cb200-5" aria-hidden="true" tabindex="-1"></a>demographics <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/demographics.csv&quot;</span>)</span>
<span id="cb200-6"><a href="data-wrangl.html#cb200-6" aria-hidden="true" tabindex="-1"></a>job <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/job.csv&quot;</span>)</span>
<span id="cb200-7"><a href="data-wrangl.html#cb200-7" aria-hidden="true" tabindex="-1"></a>payroll <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/payroll.csv&quot;</span>)</span>
<span id="cb200-8"><a href="data-wrangl.html#cb200-8" aria-hidden="true" tabindex="-1"></a>performance <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/performance.csv&quot;</span>)</span>
<span id="cb200-9"><a href="data-wrangl.html#cb200-9" aria-hidden="true" tabindex="-1"></a>prior_employment <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/prior_employment.csv&quot;</span>)</span>
<span id="cb200-10"><a href="data-wrangl.html#cb200-10" aria-hidden="true" tabindex="-1"></a>survey_response <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/survey_response.csv&quot;</span>)</span>
<span id="cb200-11"><a href="data-wrangl.html#cb200-11" aria-hidden="true" tabindex="-1"></a>tenure <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/tenure.csv&quot;</span>)</span>
<span id="cb200-12"><a href="data-wrangl.html#cb200-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-13"><a href="data-wrangl.html#cb200-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Return row and column counts</span></span>
<span id="cb200-14"><a href="data-wrangl.html#cb200-14" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(employees)</span></code></pre></div>
<pre><code>## [1] 1470   36</code></pre>
<p>Next, we will apply the <code>sqldf()</code> function to our data frame to extract specific rows and columns. In addition to the <code>SELECT</code>, <code>FROM</code>, and <code>WHERE</code> clauses, we will use the <code>LIMIT</code> clause to limit the number of rows that are displayed given the data frame’s size (<span class="math inline">\(n = 1,470\)</span>). In a practical setting, the <code>LIMIT</code> clause is only used for efficient data profiling and troubleshooting, as we would not want to arbitrarily truncate a data set used for analysis.</p>
<p>A best practice in writing SQL is to capitalize the names of clauses and functions and to use separate lines and indentation to make the SQL statements more readable:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="data-wrangl.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load SQL library</span></span>
<span id="cb202-2"><a href="data-wrangl.html#cb202-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sqldf)</span>
<span id="cb202-3"><a href="data-wrangl.html#cb202-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb202-4"><a href="data-wrangl.html#cb202-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string using the paste() function</span></span>
<span id="cb202-5"><a href="data-wrangl.html#cb202-5" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb202-6"><a href="data-wrangl.html#cb202-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      employee_id</span></span>
<span id="cb202-7"><a href="data-wrangl.html#cb202-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb202-8"><a href="data-wrangl.html#cb202-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb202-9"><a href="data-wrangl.html#cb202-9" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb202-10"><a href="data-wrangl.html#cb202-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb202-11"><a href="data-wrangl.html#cb202-11" aria-hidden="true" tabindex="-1"></a><span class="st">                    LIMIT 10&quot;</span>)</span>
<span id="cb202-12"><a href="data-wrangl.html#cb202-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb202-13"><a href="data-wrangl.html#cb202-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb202-14"><a href="data-wrangl.html#cb202-14" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##    employee_id
## 1         1002
## 2         1003
## 3         1004
## 4         1005
## 5         1006
## 6         1007
## 7         1008
## 8         1009
## 9         1010
## 10        1011</code></pre>
<p>This query returned a list of employee ids for employees in the Research &amp; Development department.</p>
<p>To optimize query performance, it is important to order conditions in the <code>WHERE</code> clause beginning with the condition that will exclude the largest number of records. Conditions are executed sequentially, and each subsequent condition must evaluate all records that remain following any preceding filtering. Limiting the number of records that must be searched when evaluating each condition will reduce the time it takes the query to return results. For example, if two conditions are needed and one excludes 5,000 records while the other excludes 10, the condition that excludes 5,000 records should be listed first in the <code>WHERE</code> clause.</p>
<p><strong>Aggregate Functions</strong></p>
<p>Next, let’s take a look at average organization tenure by job for those in the Research &amp; Development department:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="data-wrangl.html#cb204-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb204-2"><a href="data-wrangl.html#cb204-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb204-3"><a href="data-wrangl.html#cb204-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb204-4"><a href="data-wrangl.html#cb204-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      AVG(org_tenure)</span></span>
<span id="cb204-5"><a href="data-wrangl.html#cb204-5" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb204-6"><a href="data-wrangl.html#cb204-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb204-7"><a href="data-wrangl.html#cb204-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb204-8"><a href="data-wrangl.html#cb204-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb204-9"><a href="data-wrangl.html#cb204-9" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb204-10"><a href="data-wrangl.html#cb204-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb204-11"><a href="data-wrangl.html#cb204-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb204-12"><a href="data-wrangl.html#cb204-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb204-13"><a href="data-wrangl.html#cb204-13" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title AVG(org_tenure)
## 1 Healthcare Representative        8.618321
## 2     Laboratory Technician        5.019305
## 3                   Manager       13.673077
## 4    Manufacturing Director        7.600000
## 5         Research Director       10.937500
## 6        Research Scientist        5.113014
## 7            Vice President        9.500000</code></pre>
<p>There are 7 distinct job titles among employees in the Research &amp; Development department, and the average organization tenure for these ranges from <code>5</code> to <code>13.7</code> years.</p>
<p>Since there could be a small number of employees in certain jobs, in which case average organization tenure may not be as meaningful, we can use the <code>COUNT(*)</code> function to count the number of rows for each group. In this case, <code>COUNT(*)</code> will return the number of employees in each job in the Research &amp; Development department. We will also apply column aliases via <code>AS</code> in the <code>SELECT</code> clause to assign different names to the output fields:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="data-wrangl.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb206-2"><a href="data-wrangl.html#cb206-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb206-3"><a href="data-wrangl.html#cb206-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb206-4"><a href="data-wrangl.html#cb206-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb206-5"><a href="data-wrangl.html#cb206-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      AVG(org_tenure) AS avg_org_tenure</span></span>
<span id="cb206-6"><a href="data-wrangl.html#cb206-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb206-7"><a href="data-wrangl.html#cb206-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb206-8"><a href="data-wrangl.html#cb206-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb206-9"><a href="data-wrangl.html#cb206-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb206-10"><a href="data-wrangl.html#cb206-10" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb206-11"><a href="data-wrangl.html#cb206-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb206-12"><a href="data-wrangl.html#cb206-12" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb206-13"><a href="data-wrangl.html#cb206-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb206-14"><a href="data-wrangl.html#cb206-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb206-15"><a href="data-wrangl.html#cb206-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb206-16"><a href="data-wrangl.html#cb206-16" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure
## 1 Healthcare Representative          131       8.618321
## 2     Laboratory Technician          259       5.019305
## 3                   Manager           52      13.673077
## 4    Manufacturing Director          145       7.600000
## 5         Research Director           80      10.937500
## 6        Research Scientist          292       5.113014
## 7            Vice President            2       9.500000</code></pre>
<p>The output shows that there are only 2 Vice Presidents in the Research &amp; Development department, while other job titles are much more prevalent.</p>
<p>Since relatively few employees are Vice Presidents, let’s use the <code>HAVING</code> clause to only show average organization tenure for Research &amp; Development department jobs with more than 10 employees. We can also use the <code>ROUND()</code> function to truncate average organization tenure to one significant digit:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="data-wrangl.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb208-2"><a href="data-wrangl.html#cb208-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb208-3"><a href="data-wrangl.html#cb208-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb208-4"><a href="data-wrangl.html#cb208-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb208-5"><a href="data-wrangl.html#cb208-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure</span></span>
<span id="cb208-6"><a href="data-wrangl.html#cb208-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb208-7"><a href="data-wrangl.html#cb208-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      employees</span></span>
<span id="cb208-8"><a href="data-wrangl.html#cb208-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb208-9"><a href="data-wrangl.html#cb208-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb208-10"><a href="data-wrangl.html#cb208-10" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb208-11"><a href="data-wrangl.html#cb208-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb208-12"><a href="data-wrangl.html#cb208-12" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb208-13"><a href="data-wrangl.html#cb208-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb208-14"><a href="data-wrangl.html#cb208-14" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb208-15"><a href="data-wrangl.html#cb208-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb208-16"><a href="data-wrangl.html#cb208-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb208-17"><a href="data-wrangl.html#cb208-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb208-18"><a href="data-wrangl.html#cb208-18" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure
## 1 Healthcare Representative          131            8.6
## 2     Laboratory Technician          259            5.0
## 3                   Manager           52           13.7
## 4    Manufacturing Director          145            7.6
## 5         Research Director           80           10.9
## 6        Research Scientist          292            5.1</code></pre>
<p><strong>Joins</strong></p>
<p>In a practical setting, the required data are rarely contained within a single table. Therefore, we must query multiple tables and join them together. Figure <a href="data-wrangl.html#fig:sql-joins">7.6</a> illustrates SQL join types using Venn diagrams:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sql-joins"></span>
<img src="graphics/sql_joins.png" alt="Types of SQL Joins" width="100%" />
<p class="caption">
Figure 7.6: Types of SQL Joins
</p>
</div>
<p>The structure of SQL queries containing each type of join is represented below:</p>
<p><strong>LEFT INCLUSIVE</strong></p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="data-wrangl.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb210-2"><a href="data-wrangl.html#cb210-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb210-3"><a href="data-wrangl.html#cb210-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb210-4"><a href="data-wrangl.html#cb210-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>LEFT EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="data-wrangl.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb211-2"><a href="data-wrangl.html#cb211-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb211-3"><a href="data-wrangl.html#cb211-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb211-4"><a href="data-wrangl.html#cb211-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb211-5"><a href="data-wrangl.html#cb211-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE B.Key IS NULL</span></span></code></pre></div>
<p><strong>FULL OUTER INCLUSIVE</strong></p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="data-wrangl.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb212-2"><a href="data-wrangl.html#cb212-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb212-3"><a href="data-wrangl.html#cb212-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  FULL OUTER JOIN B</span></span>
<span id="cb212-4"><a href="data-wrangl.html#cb212-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>FULL OUTER EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="data-wrangl.html#cb213-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb213-2"><a href="data-wrangl.html#cb213-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb213-3"><a href="data-wrangl.html#cb213-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  FULL OUTER JOIN B</span></span>
<span id="cb213-4"><a href="data-wrangl.html#cb213-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb213-5"><a href="data-wrangl.html#cb213-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE A.Key IS NULL OR B.Key IS NULL  </span></span></code></pre></div>
<p><strong>RIGHT INCLUSIVE</strong></p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="data-wrangl.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb214-2"><a href="data-wrangl.html#cb214-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb214-3"><a href="data-wrangl.html#cb214-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  RIGHT OUTER JOIN B</span></span>
<span id="cb214-4"><a href="data-wrangl.html#cb214-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p><strong>RIGHT EXCLUSIVE</strong></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="data-wrangl.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb215-2"><a href="data-wrangl.html#cb215-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb215-3"><a href="data-wrangl.html#cb215-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  LEFT OUTER JOIN B</span></span>
<span id="cb215-4"><a href="data-wrangl.html#cb215-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span>
<span id="cb215-5"><a href="data-wrangl.html#cb215-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  WHERE A.Key IS NULL</span></span></code></pre></div>
<p><strong>INNER JOIN</strong></p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="data-wrangl.html#cb216-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  SELECT [Output Field List]</span></span>
<span id="cb216-2"><a href="data-wrangl.html#cb216-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  FROM A </span></span>
<span id="cb216-3"><a href="data-wrangl.html#cb216-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  INNER JOIN B</span></span>
<span id="cb216-4"><a href="data-wrangl.html#cb216-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  ON A.Key = B.Key</span></span></code></pre></div>
<p>To illustrate how SQL joins work, we will leverage three of the data sets used to produce the consolidated <code>employees</code> data set we have been using: <code>job</code>, <code>tenure</code>, and <code>demographics</code>. For many people analytics projects, employee id is the PK since this identifier for one employee should not be assigned to another employee – past, present, or future. Email or network id may also be a suitable PK. We will use the <code>employee_id</code> column in each of the three data frames to facilitate joins:</p>
<p>Next, we will query these data frames to return the average organization tenure and average commute distance for employees in the Research &amp; Development department, grouped by jobs with more than 10 employees. For this, we will leverage an <code>INNER JOIN</code>, which will return records only for employee ids which are present in all three data frames. For example, if a record exists in <code>demographics</code> and <code>tenure</code> for a particular employee id, but there is no corresponding record in <code>job</code>, that employee id would not be included in the output.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="data-wrangl.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb217-2"><a href="data-wrangl.html#cb217-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb217-3"><a href="data-wrangl.html#cb217-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb217-4"><a href="data-wrangl.html#cb217-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb217-5"><a href="data-wrangl.html#cb217-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure,</span></span>
<span id="cb217-6"><a href="data-wrangl.html#cb217-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb217-7"><a href="data-wrangl.html#cb217-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb217-8"><a href="data-wrangl.html#cb217-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb217-9"><a href="data-wrangl.html#cb217-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb217-10"><a href="data-wrangl.html#cb217-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        tenure</span></span>
<span id="cb217-11"><a href="data-wrangl.html#cb217-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb217-12"><a href="data-wrangl.html#cb217-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = tenure.employee_id</span></span>
<span id="cb217-13"><a href="data-wrangl.html#cb217-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb217-14"><a href="data-wrangl.html#cb217-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb217-15"><a href="data-wrangl.html#cb217-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb217-16"><a href="data-wrangl.html#cb217-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb217-17"><a href="data-wrangl.html#cb217-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb217-18"><a href="data-wrangl.html#cb217-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb217-19"><a href="data-wrangl.html#cb217-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb217-20"><a href="data-wrangl.html#cb217-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb217-21"><a href="data-wrangl.html#cb217-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb217-22"><a href="data-wrangl.html#cb217-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb217-23"><a href="data-wrangl.html#cb217-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb217-24"><a href="data-wrangl.html#cb217-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb217-25"><a href="data-wrangl.html#cb217-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb217-26"><a href="data-wrangl.html#cb217-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb217-27"><a href="data-wrangl.html#cb217-27" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure avg_commute_dist
## 1 Healthcare Representative          131            8.6              9.8
## 2     Laboratory Technician          259            5.0              9.4
## 3                   Manager           52           13.7              7.2
## 4    Manufacturing Director          145            7.6              9.5
## 5         Research Director           80           10.9              8.4
## 6        Research Scientist          292            5.1              9.0</code></pre>
<p>Note that the <code>INNER JOIN</code> in this SQL query was structured such that both <code>tenure</code> and <code>job</code> were joined to <code>demographics</code> via the <code>employee_id</code> column. We could have instead joined <code>job</code> to <code>tenure</code> since we joined <code>tenure</code> to <code>demographics</code>; this would have achieved the same result since all employee ids exist in each of the three data frames.</p>
<p>If it were possible for all employee ids to exist in <code>demographics</code> but not in either <code>tenure</code> or <code>job</code>, we could leverage a <code>LEFT JOIN</code> to ensure all records from <code>demographics</code> are included in the output irrespective of whether they have matches in <code>tenure</code> or <code>job</code>:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="data-wrangl.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb219-2"><a href="data-wrangl.html#cb219-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb219-3"><a href="data-wrangl.html#cb219-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb219-4"><a href="data-wrangl.html#cb219-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb219-5"><a href="data-wrangl.html#cb219-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(org_tenure), 1) AS avg_org_tenure,</span></span>
<span id="cb219-6"><a href="data-wrangl.html#cb219-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb219-7"><a href="data-wrangl.html#cb219-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb219-8"><a href="data-wrangl.html#cb219-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb219-9"><a href="data-wrangl.html#cb219-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb219-10"><a href="data-wrangl.html#cb219-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        tenure</span></span>
<span id="cb219-11"><a href="data-wrangl.html#cb219-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb219-12"><a href="data-wrangl.html#cb219-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = tenure.employee_id</span></span>
<span id="cb219-13"><a href="data-wrangl.html#cb219-13" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb219-14"><a href="data-wrangl.html#cb219-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb219-15"><a href="data-wrangl.html#cb219-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb219-16"><a href="data-wrangl.html#cb219-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb219-17"><a href="data-wrangl.html#cb219-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb219-18"><a href="data-wrangl.html#cb219-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb219-19"><a href="data-wrangl.html#cb219-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb219-20"><a href="data-wrangl.html#cb219-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb219-21"><a href="data-wrangl.html#cb219-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb219-22"><a href="data-wrangl.html#cb219-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb219-23"><a href="data-wrangl.html#cb219-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb219-24"><a href="data-wrangl.html#cb219-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb219-25"><a href="data-wrangl.html#cb219-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-26"><a href="data-wrangl.html#cb219-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb219-27"><a href="data-wrangl.html#cb219-27" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_org_tenure avg_commute_dist
## 1 Healthcare Representative          131            8.6              9.8
## 2     Laboratory Technician          259            5.0              9.4
## 3                   Manager           52           13.7              7.2
## 4    Manufacturing Director          145            7.6              9.5
## 5         Research Director           80           10.9              8.4
## 6        Research Scientist          292            5.1              9.0</code></pre>
<p>In this case, if demographics is the base data set which contains all employee ids (i.e., the ‘LEFT’ dataset), it is important for <code>tenure</code> and <code>job</code> to be joined to it. Joining <code>job</code> to <code>tenure</code> may result in information loss if an employee id exists in <code>demographics</code> and <code>job</code> but not in the intermediate <code>tenure</code> data set.</p>
<p>When integrating data within R, the <code>tidyverse</code> provides a more efficient and parsimonious method of joining many data sets using various join types. Within this framework, components are chained together via the package-specific <code>%&gt;%</code> operator. The example below joins nine data sets into a single <code>employees</code> data frame using a left join on the <code>employee_id</code> column:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="data-wrangl.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load tidyverse</span></span>
<span id="cb221-2"><a href="data-wrangl.html#cb221-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb221-3"><a href="data-wrangl.html#cb221-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb221-4"><a href="data-wrangl.html#cb221-4" aria-hidden="true" tabindex="-1"></a>employees <span class="ot">&lt;-</span> <span class="fu">list</span>(demographics,</span>
<span id="cb221-5"><a href="data-wrangl.html#cb221-5" aria-hidden="true" tabindex="-1"></a>                  status,</span>
<span id="cb221-6"><a href="data-wrangl.html#cb221-6" aria-hidden="true" tabindex="-1"></a>                  benefits,</span>
<span id="cb221-7"><a href="data-wrangl.html#cb221-7" aria-hidden="true" tabindex="-1"></a>                  job,</span>
<span id="cb221-8"><a href="data-wrangl.html#cb221-8" aria-hidden="true" tabindex="-1"></a>                  payroll,</span>
<span id="cb221-9"><a href="data-wrangl.html#cb221-9" aria-hidden="true" tabindex="-1"></a>                  performance,</span>
<span id="cb221-10"><a href="data-wrangl.html#cb221-10" aria-hidden="true" tabindex="-1"></a>                  prior_employment,</span>
<span id="cb221-11"><a href="data-wrangl.html#cb221-11" aria-hidden="true" tabindex="-1"></a>                  survey_response,</span>
<span id="cb221-12"><a href="data-wrangl.html#cb221-12" aria-hidden="true" tabindex="-1"></a>                  tenure) <span class="sc">%&gt;%</span></span>
<span id="cb221-13"><a href="data-wrangl.html#cb221-13" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">reduce</span>(left_join, <span class="at">by =</span> <span class="st">&quot;employee_id&quot;</span>)</span></code></pre></div>
<p><strong>Subqueries</strong></p>
<p><strong>Subqueries</strong> are queries nested within other queries. Subqueries are often referred to as <strong>inner queries</strong>, while the main queries are referred to as <strong>outer queries</strong>.</p>
<p>For example, if we are interested in performing an analysis on employees with more than a year of organization tenure, we can use a subquery to pass a list of employee ids that meet this criterion into the outer query for filtering. In this case, we would not need to include <code>tenure</code> in the join conditions of our main query:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="data-wrangl.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb222-2"><a href="data-wrangl.html#cb222-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: Since employee_id exists in multiple data sets, we must name a specific data set when referencing it</span></span>
<span id="cb222-3"><a href="data-wrangl.html#cb222-3" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb222-4"><a href="data-wrangl.html#cb222-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb222-5"><a href="data-wrangl.html#cb222-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb222-6"><a href="data-wrangl.html#cb222-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb222-7"><a href="data-wrangl.html#cb222-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb222-8"><a href="data-wrangl.html#cb222-8" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb222-9"><a href="data-wrangl.html#cb222-9" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb222-10"><a href="data-wrangl.html#cb222-10" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb222-11"><a href="data-wrangl.html#cb222-11" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb222-12"><a href="data-wrangl.html#cb222-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb222-13"><a href="data-wrangl.html#cb222-13" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb222-14"><a href="data-wrangl.html#cb222-14" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id IN (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1)</span></span>
<span id="cb222-15"><a href="data-wrangl.html#cb222-15" aria-hidden="true" tabindex="-1"></a><span class="st">                      AND </span></span>
<span id="cb222-16"><a href="data-wrangl.html#cb222-16" aria-hidden="true" tabindex="-1"></a><span class="st">                        dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb222-17"><a href="data-wrangl.html#cb222-17" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb222-18"><a href="data-wrangl.html#cb222-18" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb222-19"><a href="data-wrangl.html#cb222-19" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb222-20"><a href="data-wrangl.html#cb222-20" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb222-21"><a href="data-wrangl.html#cb222-21" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb222-22"><a href="data-wrangl.html#cb222-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb222-23"><a href="data-wrangl.html#cb222-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-24"><a href="data-wrangl.html#cb222-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb222-25"><a href="data-wrangl.html#cb222-25" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_commute_dist
## 1 Healthcare Representative          118              9.7
## 2     Laboratory Technician          198              9.6
## 3                   Manager           49              6.9
## 4    Manufacturing Director          133              9.7
## 5         Research Director           74              8.3
## 6        Research Scientist          238              9.2</code></pre>
<p><strong>Virtual Tables</strong></p>
<p>An alternative to a subquery is creating a <strong>virtual table</strong> in the <code>FROM</code> clause. When using an <code>INNER JOIN</code> to connect <code>demographics</code> to the virtual table <code>ids</code>, which provides a list of employee ids for those with more than a year of organization tenure, any records in <code>demographics</code> or <code>job</code> that do not relate to employees with at least a year of organization tenure will be dropped. This is true even though a <code>LEFT JOIN</code> is used to join <code>job</code> to <code>demographics</code> since records in <code>demographics</code> will be filtered based on <code>employee_id</code> matches in the virtual table. With this approach, our <code>WHERE</code> clause is limited to the <code>department = 'Research &amp; Development'</code> condition:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="data-wrangl.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb224-2"><a href="data-wrangl.html#cb224-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb224-3"><a href="data-wrangl.html#cb224-3" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb224-4"><a href="data-wrangl.html#cb224-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) AS employee_cnt,</span></span>
<span id="cb224-5"><a href="data-wrangl.html#cb224-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      ROUND(AVG(commute_dist), 1) AS avg_commute_dist</span></span>
<span id="cb224-6"><a href="data-wrangl.html#cb224-6" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb224-7"><a href="data-wrangl.html#cb224-7" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb224-8"><a href="data-wrangl.html#cb224-8" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb224-9"><a href="data-wrangl.html#cb224-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb224-10"><a href="data-wrangl.html#cb224-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb224-11"><a href="data-wrangl.html#cb224-11" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb224-12"><a href="data-wrangl.html#cb224-12" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb224-13"><a href="data-wrangl.html#cb224-13" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb224-14"><a href="data-wrangl.html#cb224-14" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb224-15"><a href="data-wrangl.html#cb224-15" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = ids.employee_id</span></span>
<span id="cb224-16"><a href="data-wrangl.html#cb224-16" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb224-17"><a href="data-wrangl.html#cb224-17" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb224-18"><a href="data-wrangl.html#cb224-18" aria-hidden="true" tabindex="-1"></a><span class="st">                    GROUP BY</span></span>
<span id="cb224-19"><a href="data-wrangl.html#cb224-19" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title</span></span>
<span id="cb224-20"><a href="data-wrangl.html#cb224-20" aria-hidden="true" tabindex="-1"></a><span class="st">                    HAVING</span></span>
<span id="cb224-21"><a href="data-wrangl.html#cb224-21" aria-hidden="true" tabindex="-1"></a><span class="st">                      COUNT(*) &gt; 10</span></span>
<span id="cb224-22"><a href="data-wrangl.html#cb224-22" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb224-23"><a href="data-wrangl.html#cb224-23" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title&quot;</span>)</span>
<span id="cb224-24"><a href="data-wrangl.html#cb224-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb224-25"><a href="data-wrangl.html#cb224-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb224-26"><a href="data-wrangl.html#cb224-26" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_cnt avg_commute_dist
## 1 Healthcare Representative          118              9.7
## 2     Laboratory Technician          198              9.6
## 3                   Manager           49              6.9
## 4    Manufacturing Director          133              9.7
## 5         Research Director           74              8.3
## 6        Research Scientist          238              9.2</code></pre>
<p>As you can see, the output of the query using a virtual table matches the results from the preceding approach that utilized a subquery.</p>
<p><strong>Window Functions</strong></p>
<p><strong>Window functions</strong> are used for performing calculations over a set of rows without collapsing the records. Unlike the aggregate functions we’ve covered, window functions do not collapse rows into a single value; the calculated value is returned for each of the rows over which the calculation is performed.</p>
<p>For example, we can assign an organization tenure rank by Research &amp; Development job using the <code>RANK()</code> and <code>OVER()</code> functions in the <code>SELECT</code> clause. The <code>PARTITION BY</code> argument functions like a <code>GROUP BY</code> clause but without collapsing rows, while the <code>ORDER BY</code> argument sorts the records in ascending (<code>ASC</code>) or descending (<code>DESC</code>) order for proper ranking:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="data-wrangl.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb226-2"><a href="data-wrangl.html#cb226-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Limit output to 10 records since query does not collapse records</span></span>
<span id="cb226-3"><a href="data-wrangl.html#cb226-3" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb226-4"><a href="data-wrangl.html#cb226-4" aria-hidden="true" tabindex="-1"></a><span class="st">                      demographics.employee_id,</span></span>
<span id="cb226-5"><a href="data-wrangl.html#cb226-5" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb226-6"><a href="data-wrangl.html#cb226-6" aria-hidden="true" tabindex="-1"></a><span class="st">                      commute_dist,</span></span>
<span id="cb226-7"><a href="data-wrangl.html#cb226-7" aria-hidden="true" tabindex="-1"></a><span class="st">                      RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb226-8"><a href="data-wrangl.html#cb226-8" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM</span></span>
<span id="cb226-9"><a href="data-wrangl.html#cb226-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics</span></span>
<span id="cb226-10"><a href="data-wrangl.html#cb226-10" aria-hidden="true" tabindex="-1"></a><span class="st">                      LEFT JOIN</span></span>
<span id="cb226-11"><a href="data-wrangl.html#cb226-11" aria-hidden="true" tabindex="-1"></a><span class="st">                        job</span></span>
<span id="cb226-12"><a href="data-wrangl.html#cb226-12" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb226-13"><a href="data-wrangl.html#cb226-13" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = job.employee_id</span></span>
<span id="cb226-14"><a href="data-wrangl.html#cb226-14" aria-hidden="true" tabindex="-1"></a><span class="st">                      INNER JOIN</span></span>
<span id="cb226-15"><a href="data-wrangl.html#cb226-15" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb226-16"><a href="data-wrangl.html#cb226-16" aria-hidden="true" tabindex="-1"></a><span class="st">                      ON</span></span>
<span id="cb226-17"><a href="data-wrangl.html#cb226-17" aria-hidden="true" tabindex="-1"></a><span class="st">                        demographics.employee_id = ids.employee_id</span></span>
<span id="cb226-18"><a href="data-wrangl.html#cb226-18" aria-hidden="true" tabindex="-1"></a><span class="st">                    WHERE</span></span>
<span id="cb226-19"><a href="data-wrangl.html#cb226-19" aria-hidden="true" tabindex="-1"></a><span class="st">                      dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb226-20"><a href="data-wrangl.html#cb226-20" aria-hidden="true" tabindex="-1"></a><span class="st">                    ORDER BY</span></span>
<span id="cb226-21"><a href="data-wrangl.html#cb226-21" aria-hidden="true" tabindex="-1"></a><span class="st">                      job_title,</span></span>
<span id="cb226-22"><a href="data-wrangl.html#cb226-22" aria-hidden="true" tabindex="-1"></a><span class="st">                      commute_dist_rank</span></span>
<span id="cb226-23"><a href="data-wrangl.html#cb226-23" aria-hidden="true" tabindex="-1"></a><span class="st">                    LIMIT 10&quot;</span>)</span>
<span id="cb226-24"><a href="data-wrangl.html#cb226-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb226-25"><a href="data-wrangl.html#cb226-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb226-26"><a href="data-wrangl.html#cb226-26" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##    employee_id                 job_title commute_dist commute_dist_rank
## 1         2325 Healthcare Representative           29                 1
## 2         1414 Healthcare Representative           28                 2
## 3         1010 Healthcare Representative           27                 3
## 4         1573 Healthcare Representative           27                 3
## 5         2200 Healthcare Representative           26                 5
## 6         1730 Healthcare Representative           25                 6
## 7         1833 Healthcare Representative           25                 6
## 8         1993 Healthcare Representative           25                 6
## 9         2415 Healthcare Representative           25                 6
## 10        1164 Healthcare Representative           24                10</code></pre>
<p>Notice that in the case of commute distance ties, the <code>RANK()</code> function assigns the same rank and then adds the number of ties to that rank to determine the rank for the next highest value of commute distance.</p>
<p>We can also treat this query as a virtual table, and then filter on the derived <code>commute_dist_rank</code> field to return the highest commute distance for each job. We can add a <code>DISTINCT()</code> function in the <code>SELECT</code> clause to collapse jobs for which there are more than one employee with the max commute distance, and display the number of ties for each using the <code>COUNT(*)</code> function:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="data-wrangl.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb228-2"><a href="data-wrangl.html#cb228-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT</span></span>
<span id="cb228-3"><a href="data-wrangl.html#cb228-3" aria-hidden="true" tabindex="-1"></a><span class="st">                        DISTINCT(job_title) AS job_title,</span></span>
<span id="cb228-4"><a href="data-wrangl.html#cb228-4" aria-hidden="true" tabindex="-1"></a><span class="st">                        COUNT(*) AS employee_count,</span></span>
<span id="cb228-5"><a href="data-wrangl.html#cb228-5" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist</span></span>
<span id="cb228-6"><a href="data-wrangl.html#cb228-6" aria-hidden="true" tabindex="-1"></a><span class="st">                     FROM</span></span>
<span id="cb228-7"><a href="data-wrangl.html#cb228-7" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT</span></span>
<span id="cb228-8"><a href="data-wrangl.html#cb228-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          demographics.employee_id,</span></span>
<span id="cb228-9"><a href="data-wrangl.html#cb228-9" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb228-10"><a href="data-wrangl.html#cb228-10" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist,</span></span>
<span id="cb228-11"><a href="data-wrangl.html#cb228-11" aria-hidden="true" tabindex="-1"></a><span class="st">                          RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb228-12"><a href="data-wrangl.html#cb228-12" aria-hidden="true" tabindex="-1"></a><span class="st">                        FROM</span></span>
<span id="cb228-13"><a href="data-wrangl.html#cb228-13" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics</span></span>
<span id="cb228-14"><a href="data-wrangl.html#cb228-14" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN</span></span>
<span id="cb228-15"><a href="data-wrangl.html#cb228-15" aria-hidden="true" tabindex="-1"></a><span class="st">                            job</span></span>
<span id="cb228-16"><a href="data-wrangl.html#cb228-16" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb228-17"><a href="data-wrangl.html#cb228-17" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = job.employee_id</span></span>
<span id="cb228-18"><a href="data-wrangl.html#cb228-18" aria-hidden="true" tabindex="-1"></a><span class="st">                          INNER JOIN</span></span>
<span id="cb228-19"><a href="data-wrangl.html#cb228-19" aria-hidden="true" tabindex="-1"></a><span class="st">                            (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb228-20"><a href="data-wrangl.html#cb228-20" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb228-21"><a href="data-wrangl.html#cb228-21" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = ids.employee_id</span></span>
<span id="cb228-22"><a href="data-wrangl.html#cb228-22" aria-hidden="true" tabindex="-1"></a><span class="st">                        WHERE</span></span>
<span id="cb228-23"><a href="data-wrangl.html#cb228-23" aria-hidden="true" tabindex="-1"></a><span class="st">                          dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb228-24"><a href="data-wrangl.html#cb228-24" aria-hidden="true" tabindex="-1"></a><span class="st">                        ORDER BY</span></span>
<span id="cb228-25"><a href="data-wrangl.html#cb228-25" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb228-26"><a href="data-wrangl.html#cb228-26" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist_rank) tbl</span></span>
<span id="cb228-27"><a href="data-wrangl.html#cb228-27" aria-hidden="true" tabindex="-1"></a><span class="st">                      WHERE</span></span>
<span id="cb228-28"><a href="data-wrangl.html#cb228-28" aria-hidden="true" tabindex="-1"></a><span class="st">                        tbl.commute_dist_rank = 1</span></span>
<span id="cb228-29"><a href="data-wrangl.html#cb228-29" aria-hidden="true" tabindex="-1"></a><span class="st">                      GROUP BY</span></span>
<span id="cb228-30"><a href="data-wrangl.html#cb228-30" aria-hidden="true" tabindex="-1"></a><span class="st">                        job_title&quot;</span>)</span>
<span id="cb228-31"><a href="data-wrangl.html#cb228-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb228-32"><a href="data-wrangl.html#cb228-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb228-33"><a href="data-wrangl.html#cb228-33" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_count commute_dist
## 1 Healthcare Representative              1           29
## 2     Laboratory Technician              6           29
## 3                   Manager              2           29
## 4    Manufacturing Director              4           29
## 5         Research Director              3           28
## 6        Research Scientist              4           29
## 7            Vice President              1            8</code></pre>
<p>An alternative approach is to use a <strong>common table expression (CTE)</strong>, which is the result set of a query that exists temporarily and only for use in a larger query. Like the virtual table example, CTEs do not persist data in objects or tables; the data exist only for the duration of the query.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="data-wrangl.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store SQL query as a character string</span></span>
<span id="cb230-2"><a href="data-wrangl.html#cb230-2" aria-hidden="true" tabindex="-1"></a>sql_string <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;WITH max_commute_job</span></span>
<span id="cb230-3"><a href="data-wrangl.html#cb230-3" aria-hidden="true" tabindex="-1"></a><span class="st">                     AS</span></span>
<span id="cb230-4"><a href="data-wrangl.html#cb230-4" aria-hidden="true" tabindex="-1"></a><span class="st">                        (SELECT</span></span>
<span id="cb230-5"><a href="data-wrangl.html#cb230-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          demographics.employee_id,</span></span>
<span id="cb230-6"><a href="data-wrangl.html#cb230-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb230-7"><a href="data-wrangl.html#cb230-7" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist,</span></span>
<span id="cb230-8"><a href="data-wrangl.html#cb230-8" aria-hidden="true" tabindex="-1"></a><span class="st">                          RANK () OVER (PARTITION BY job_title ORDER BY commute_dist DESC) AS commute_dist_rank</span></span>
<span id="cb230-9"><a href="data-wrangl.html#cb230-9" aria-hidden="true" tabindex="-1"></a><span class="st">                        FROM</span></span>
<span id="cb230-10"><a href="data-wrangl.html#cb230-10" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics</span></span>
<span id="cb230-11"><a href="data-wrangl.html#cb230-11" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN</span></span>
<span id="cb230-12"><a href="data-wrangl.html#cb230-12" aria-hidden="true" tabindex="-1"></a><span class="st">                            job</span></span>
<span id="cb230-13"><a href="data-wrangl.html#cb230-13" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb230-14"><a href="data-wrangl.html#cb230-14" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = job.employee_id</span></span>
<span id="cb230-15"><a href="data-wrangl.html#cb230-15" aria-hidden="true" tabindex="-1"></a><span class="st">                          INNER JOIN</span></span>
<span id="cb230-16"><a href="data-wrangl.html#cb230-16" aria-hidden="true" tabindex="-1"></a><span class="st">                            (SELECT employee_id FROM tenure WHERE org_tenure &gt; 1) ids</span></span>
<span id="cb230-17"><a href="data-wrangl.html#cb230-17" aria-hidden="true" tabindex="-1"></a><span class="st">                          ON</span></span>
<span id="cb230-18"><a href="data-wrangl.html#cb230-18" aria-hidden="true" tabindex="-1"></a><span class="st">                            demographics.employee_id = ids.employee_id</span></span>
<span id="cb230-19"><a href="data-wrangl.html#cb230-19" aria-hidden="true" tabindex="-1"></a><span class="st">                        WHERE</span></span>
<span id="cb230-20"><a href="data-wrangl.html#cb230-20" aria-hidden="true" tabindex="-1"></a><span class="st">                          dept = &#39;Research &amp; Development&#39;</span></span>
<span id="cb230-21"><a href="data-wrangl.html#cb230-21" aria-hidden="true" tabindex="-1"></a><span class="st">                        ORDER BY</span></span>
<span id="cb230-22"><a href="data-wrangl.html#cb230-22" aria-hidden="true" tabindex="-1"></a><span class="st">                          job_title,</span></span>
<span id="cb230-23"><a href="data-wrangl.html#cb230-23" aria-hidden="true" tabindex="-1"></a><span class="st">                          commute_dist_rank)</span></span>
<span id="cb230-24"><a href="data-wrangl.html#cb230-24" aria-hidden="true" tabindex="-1"></a><span class="st">                      </span></span>
<span id="cb230-25"><a href="data-wrangl.html#cb230-25" aria-hidden="true" tabindex="-1"></a><span class="st">                      SELECT</span></span>
<span id="cb230-26"><a href="data-wrangl.html#cb230-26" aria-hidden="true" tabindex="-1"></a><span class="st">                        DISTINCT(job_title) AS job_title,</span></span>
<span id="cb230-27"><a href="data-wrangl.html#cb230-27" aria-hidden="true" tabindex="-1"></a><span class="st">                        COUNT(*) AS employee_count,</span></span>
<span id="cb230-28"><a href="data-wrangl.html#cb230-28" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist</span></span>
<span id="cb230-29"><a href="data-wrangl.html#cb230-29" aria-hidden="true" tabindex="-1"></a><span class="st">                     FROM</span></span>
<span id="cb230-30"><a href="data-wrangl.html#cb230-30" aria-hidden="true" tabindex="-1"></a><span class="st">                        max_commute_job</span></span>
<span id="cb230-31"><a href="data-wrangl.html#cb230-31" aria-hidden="true" tabindex="-1"></a><span class="st">                      WHERE</span></span>
<span id="cb230-32"><a href="data-wrangl.html#cb230-32" aria-hidden="true" tabindex="-1"></a><span class="st">                        commute_dist_rank = 1</span></span>
<span id="cb230-33"><a href="data-wrangl.html#cb230-33" aria-hidden="true" tabindex="-1"></a><span class="st">                      GROUP BY</span></span>
<span id="cb230-34"><a href="data-wrangl.html#cb230-34" aria-hidden="true" tabindex="-1"></a><span class="st">                        job_title&quot;</span>)</span>
<span id="cb230-35"><a href="data-wrangl.html#cb230-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb230-36"><a href="data-wrangl.html#cb230-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Execute SQL query</span></span>
<span id="cb230-37"><a href="data-wrangl.html#cb230-37" aria-hidden="true" tabindex="-1"></a>sqldf<span class="sc">::</span><span class="fu">sqldf</span>(sql_string)</span></code></pre></div>
<pre><code>##                   job_title employee_count commute_dist
## 1 Healthcare Representative              1           29
## 2     Laboratory Technician              6           29
## 3                   Manager              2           29
## 4    Manufacturing Director              4           29
## 5         Research Director              3           28
## 6        Research Scientist              4           29
## 7            Vice President              1            8</code></pre>
</div>
<div id="review-questions-5" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Review Questions</h2>
<ol style="list-style-type: decimal">
<li><p>What are the differences between data lakes, data warehouses, and data marts?</p></li>
<li><p>What is the difference between a Type 1 and Type 2 table in a DW?</p></li>
<li><p>In what ways has modern cloud computing influenced data architecture?</p></li>
<li><p>What two clauses must always be present in a SQL query?</p></li>
<li><p>What SQL clause is executed first at run time?</p></li>
<li><p>To optimize the performance of a SQL query, how should conditions in the WHERE clause be ordered?</p></li>
<li><p>How do aggregate functions differ from window functions in SQL?</p></li>
<li><p>What is a subquery?</p></li>
<li><p>What is the difference between an INNER JOIN and LEFT JOIN?</p></li>
<li><p>What is the purpose of a common table expression (CTE)?</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inf-stats.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-prep.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["People_Analytics_Lifecycle.pdf", "People_Analytics_Lifecycle.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
