<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12 Logistic Regression | The Fundamentals of People Analytics: With Applications in R</title>
  <meta name="description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="12 Logistic Regression | The Fundamentals of People Analytics: With Applications in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="github-repo" content="crstarbuck/peopleanalytics-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12 Logistic Regression | The Fundamentals of People Analytics: With Applications in R" />
  
  <meta name="twitter:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  

<meta name="author" content="Craig Starbuck" />


<meta name="date" content="2022-11-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lme.html"/>
<link rel="next" href="pred-mod.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.9/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Fundamentals of People Analytics: With Applications in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#guiding-principles"><i class="fa fa-check"></i><b>1.1</b> Guiding Principles</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="getting-started.html"><a href="getting-started.html#pro-employee-thinking"><i class="fa fa-check"></i><b>1.1.1</b> Pro-Employee Thinking</a></li>
<li class="chapter" data-level="1.1.2" data-path="getting-started.html"><a href="getting-started.html#quality"><i class="fa fa-check"></i><b>1.1.2</b> Quality</a></li>
<li class="chapter" data-level="1.1.3" data-path="getting-started.html"><a href="getting-started.html#prioritization"><i class="fa fa-check"></i><b>1.1.3</b> Prioritization</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#tooling"><i class="fa fa-check"></i><b>1.2</b> Tooling</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#data-sets"><i class="fa fa-check"></i><b>1.3</b> Data Sets</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="getting-started.html"><a href="getting-started.html#employees"><i class="fa fa-check"></i><b>1.3.1</b> Employees</a></li>
<li class="chapter" data-level="1.3.2" data-path="getting-started.html"><a href="getting-started.html#turnover-trends"><i class="fa fa-check"></i><b>1.3.2</b> Turnover Trends</a></li>
<li class="chapter" data-level="1.3.3" data-path="getting-started.html"><a href="getting-started.html#survey-responses"><i class="fa fa-check"></i><b>1.3.3</b> Survey Responses</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#d-framework"><i class="fa fa-check"></i><b>1.4</b> 4D Framework</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-intro.html"><a href="r-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-intro.html"><a href="r-intro.html#getting-started-1"><i class="fa fa-check"></i><b>2.1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="r-intro.html"><a href="r-intro.html#installing-r"><i class="fa fa-check"></i><b>2.1.1</b> Installing R</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-intro.html"><a href="r-intro.html#installing-r-studio"><i class="fa fa-check"></i><b>2.1.2</b> Installing R Studio</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-intro.html"><a href="r-intro.html#installing-packages"><i class="fa fa-check"></i><b>2.1.3</b> Installing Packages</a></li>
<li class="chapter" data-level="2.1.4" data-path="r-intro.html"><a href="r-intro.html#loading-data"><i class="fa fa-check"></i><b>2.1.4</b> Loading data</a></li>
<li class="chapter" data-level="2.1.5" data-path="r-intro.html"><a href="r-intro.html#case-sensitivity"><i class="fa fa-check"></i><b>2.1.5</b> Case Sensitivity</a></li>
<li class="chapter" data-level="2.1.6" data-path="r-intro.html"><a href="r-intro.html#help"><i class="fa fa-check"></i><b>2.1.6</b> Help</a></li>
<li class="chapter" data-level="2.1.7" data-path="r-intro.html"><a href="r-intro.html#objects"><i class="fa fa-check"></i><b>2.1.7</b> Objects</a></li>
<li class="chapter" data-level="2.1.8" data-path="r-intro.html"><a href="r-intro.html#comments"><i class="fa fa-check"></i><b>2.1.8</b> Comments</a></li>
<li class="chapter" data-level="2.1.9" data-path="r-intro.html"><a href="r-intro.html#testing-early-and-often"><i class="fa fa-check"></i><b>2.1.9</b> Testing Early and Often</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-intro.html"><a href="r-intro.html#vectors"><i class="fa fa-check"></i><b>2.2</b> Vectors</a></li>
<li class="chapter" data-level="2.3" data-path="r-intro.html"><a href="r-intro.html#matrices"><i class="fa fa-check"></i><b>2.3</b> Matrices</a></li>
<li class="chapter" data-level="2.4" data-path="r-intro.html"><a href="r-intro.html#factors"><i class="fa fa-check"></i><b>2.4</b> Factors</a></li>
<li class="chapter" data-level="2.5" data-path="r-intro.html"><a href="r-intro.html#data-frames"><i class="fa fa-check"></i><b>2.5</b> Data Frames</a></li>
<li class="chapter" data-level="2.6" data-path="r-intro.html"><a href="r-intro.html#lists"><i class="fa fa-check"></i><b>2.6</b> Lists</a></li>
<li class="chapter" data-level="2.7" data-path="r-intro.html"><a href="r-intro.html#loops"><i class="fa fa-check"></i><b>2.7</b> Loops</a></li>
<li class="chapter" data-level="2.8" data-path="r-intro.html"><a href="r-intro.html#user-defined-functions-udfs"><i class="fa fa-check"></i><b>2.8</b> User-Defined Functions (UDFs)</a></li>
<li class="chapter" data-level="2.9" data-path="r-intro.html"><a href="r-intro.html#graphics"><i class="fa fa-check"></i><b>2.9</b> Graphics</a></li>
<li class="chapter" data-level="2.10" data-path="r-intro.html"><a href="r-intro.html#review-questions"><i class="fa fa-check"></i><b>2.10</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sql-intro.html"><a href="sql-intro.html"><i class="fa fa-check"></i><b>3</b> Introduction to SQL</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sql-intro.html"><a href="sql-intro.html#basics"><i class="fa fa-check"></i><b>3.1</b> Basics</a></li>
<li class="chapter" data-level="3.2" data-path="sql-intro.html"><a href="sql-intro.html#aggregate-functions"><i class="fa fa-check"></i><b>3.2</b> Aggregate Functions</a></li>
<li class="chapter" data-level="3.3" data-path="sql-intro.html"><a href="sql-intro.html#joins"><i class="fa fa-check"></i><b>3.3</b> Joins</a></li>
<li class="chapter" data-level="3.4" data-path="sql-intro.html"><a href="sql-intro.html#subqueries"><i class="fa fa-check"></i><b>3.4</b> Subqueries</a></li>
<li class="chapter" data-level="3.5" data-path="sql-intro.html"><a href="sql-intro.html#virtual-tables"><i class="fa fa-check"></i><b>3.5</b> Virtual Tables</a></li>
<li class="chapter" data-level="3.6" data-path="sql-intro.html"><a href="sql-intro.html#window-functions"><i class="fa fa-check"></i><b>3.6</b> Window Functions</a></li>
<li class="chapter" data-level="3.7" data-path="sql-intro.html"><a href="sql-intro.html#common-table-expressions-ctes"><i class="fa fa-check"></i><b>3.7</b> Common Table Expressions (CTEs)</a></li>
<li class="chapter" data-level="3.8" data-path="sql-intro.html"><a href="sql-intro.html#review-questions-1"><i class="fa fa-check"></i><b>3.8</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="research.html"><a href="research.html"><i class="fa fa-check"></i><b>4</b> Research Design</a>
<ul>
<li class="chapter" data-level="4.1" data-path="research.html"><a href="research.html#research-questions"><i class="fa fa-check"></i><b>4.1</b> Research Questions</a></li>
<li class="chapter" data-level="4.2" data-path="research.html"><a href="research.html#research-hypotheses"><i class="fa fa-check"></i><b>4.2</b> Research Hypotheses</a></li>
<li class="chapter" data-level="4.3" data-path="research.html"><a href="research.html#internal-and-external-validity"><i class="fa fa-check"></i><b>4.3</b> Internal and External Validity</a></li>
<li class="chapter" data-level="4.4" data-path="research.html"><a href="research.html#research-methods"><i class="fa fa-check"></i><b>4.4</b> Research Methods</a></li>
<li class="chapter" data-level="4.5" data-path="research.html"><a href="research.html#research-designs"><i class="fa fa-check"></i><b>4.5</b> Research Designs</a></li>
<li class="chapter" data-level="4.6" data-path="research.html"><a href="research.html#review-questions-2"><i class="fa fa-check"></i><b>4.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="measure-sampl.html"><a href="measure-sampl.html"><i class="fa fa-check"></i><b>5</b> Measurement &amp; Sampling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="measure-sampl.html"><a href="measure-sampl.html#variable-types"><i class="fa fa-check"></i><b>5.1</b> Variable Types</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="measure-sampl.html"><a href="measure-sampl.html#independent-variables-iv"><i class="fa fa-check"></i><b>5.1.1</b> Independent Variables (IV)</a></li>
<li class="chapter" data-level="5.1.2" data-path="measure-sampl.html"><a href="measure-sampl.html#dependent-variables-dv"><i class="fa fa-check"></i><b>5.1.2</b> Dependent Variables (DV)</a></li>
<li class="chapter" data-level="5.1.3" data-path="measure-sampl.html"><a href="measure-sampl.html#control-variables-cv"><i class="fa fa-check"></i><b>5.1.3</b> Control Variables (CV)</a></li>
<li class="chapter" data-level="5.1.4" data-path="measure-sampl.html"><a href="measure-sampl.html#moderating-variables"><i class="fa fa-check"></i><b>5.1.4</b> Moderating Variables</a></li>
<li class="chapter" data-level="5.1.5" data-path="measure-sampl.html"><a href="measure-sampl.html#mediating-variables"><i class="fa fa-check"></i><b>5.1.5</b> Mediating Variables</a></li>
<li class="chapter" data-level="5.1.6" data-path="measure-sampl.html"><a href="measure-sampl.html#endogenous-vs.-exogenous-variables"><i class="fa fa-check"></i><b>5.1.6</b> Endogenous vs. Exogenous Variables</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="measure-sampl.html"><a href="measure-sampl.html#measurement-scales"><i class="fa fa-check"></i><b>5.2</b> Measurement Scales</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="measure-sampl.html"><a href="measure-sampl.html#discrete-variables"><i class="fa fa-check"></i><b>5.2.1</b> Discrete Variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="measure-sampl.html"><a href="measure-sampl.html#continuous-variables"><i class="fa fa-check"></i><b>5.2.2</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-methods"><i class="fa fa-check"></i><b>5.3</b> Sampling Methods</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#probability-sampling"><i class="fa fa-check"></i><b>5.3.1</b> Probability Sampling</a></li>
<li class="chapter" data-level="5.3.2" data-path="measure-sampl.html"><a href="measure-sampl.html#non-probability-sampling"><i class="fa fa-check"></i><b>5.3.2</b> Non-Probability Sampling</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-nonsampling-error"><i class="fa fa-check"></i><b>5.4</b> Sampling &amp; Nonsampling Error</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-error"><i class="fa fa-check"></i><b>5.4.1</b> Sampling Error</a></li>
<li class="chapter" data-level="5.4.2" data-path="measure-sampl.html"><a href="measure-sampl.html#nonsampling-error"><i class="fa fa-check"></i><b>5.4.2</b> Nonsampling Error</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="measure-sampl.html"><a href="measure-sampl.html#scale-reliability-and-validity"><i class="fa fa-check"></i><b>5.5</b> Scale Reliability and Validity</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="measure-sampl.html"><a href="measure-sampl.html#reliability"><i class="fa fa-check"></i><b>5.5.1</b> Reliability</a></li>
<li class="chapter" data-level="5.5.2" data-path="measure-sampl.html"><a href="measure-sampl.html#validity"><i class="fa fa-check"></i><b>5.5.2</b> Validity</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="measure-sampl.html"><a href="measure-sampl.html#review-questions-3"><i class="fa fa-check"></i><b>5.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-prep.html"><a href="data-prep.html"><i class="fa fa-check"></i><b>6</b> Data Preparation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-prep.html"><a href="data-prep.html#data-extraction"><i class="fa fa-check"></i><b>6.1</b> Data Extraction</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="data-prep.html"><a href="data-prep.html#data-architecture"><i class="fa fa-check"></i><b>6.1.1</b> Data Architecture</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="data-prep.html"><a href="data-prep.html#data-screening-cleaning"><i class="fa fa-check"></i><b>6.2</b> Data Screening &amp; Cleaning</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="data-prep.html"><a href="data-prep.html#missingness"><i class="fa fa-check"></i><b>6.2.1</b> Missingness</a></li>
<li class="chapter" data-level="6.2.2" data-path="data-prep.html"><a href="data-prep.html#outliers"><i class="fa fa-check"></i><b>6.2.2</b> Outliers</a></li>
<li class="chapter" data-level="6.2.3" data-path="data-prep.html"><a href="data-prep.html#low-variability"><i class="fa fa-check"></i><b>6.2.3</b> Low Variability</a></li>
<li class="chapter" data-level="6.2.4" data-path="data-prep.html"><a href="data-prep.html#inconsistent-categories"><i class="fa fa-check"></i><b>6.2.4</b> Inconsistent Categories</a></li>
<li class="chapter" data-level="6.2.5" data-path="data-prep.html"><a href="data-prep.html#data-binning"><i class="fa fa-check"></i><b>6.2.5</b> Data Binning</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="data-prep.html"><a href="data-prep.html#one-hot-encoding"><i class="fa fa-check"></i><b>6.3</b> One-Hot Encoding</a></li>
<li class="chapter" data-level="6.4" data-path="data-prep.html"><a href="data-prep.html#feature-engineering"><i class="fa fa-check"></i><b>6.4</b> Feature Engineering</a></li>
<li class="chapter" data-level="6.5" data-path="data-prep.html"><a href="data-prep.html#review-questions-4"><i class="fa fa-check"></i><b>6.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="desc-stats.html"><a href="desc-stats.html"><i class="fa fa-check"></i><b>7</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="desc-stats.html"><a href="desc-stats.html#univariate-analysis"><i class="fa fa-check"></i><b>7.1</b> Univariate Analysis</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.1.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="7.1.2" data-path="desc-stats.html"><a href="desc-stats.html#measures-of-spread"><i class="fa fa-check"></i><b>7.1.2</b> Measures of Spread</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="desc-stats.html"><a href="desc-stats.html#bivariate-analysis"><i class="fa fa-check"></i><b>7.2</b> Bivariate Analysis</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="desc-stats.html"><a href="desc-stats.html#covariance"><i class="fa fa-check"></i><b>7.2.1</b> Covariance</a></li>
<li class="chapter" data-level="7.2.2" data-path="desc-stats.html"><a href="desc-stats.html#correlation"><i class="fa fa-check"></i><b>7.2.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="desc-stats.html"><a href="desc-stats.html#review-questions-5"><i class="fa fa-check"></i><b>7.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inf-stats.html"><a href="inf-stats.html"><i class="fa fa-check"></i><b>8</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="8.1" data-path="inf-stats.html"><a href="inf-stats.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="inf-stats.html"><a href="inf-stats.html#probability-distributions"><i class="fa fa-check"></i><b>8.1.1</b> Probability Distributions</a></li>
<li class="chapter" data-level="8.1.2" data-path="inf-stats.html"><a href="inf-stats.html#conditional-probability"><i class="fa fa-check"></i><b>8.1.2</b> Conditional Probability</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inf-stats.html"><a href="inf-stats.html#central-limit-theorem"><i class="fa fa-check"></i><b>8.2</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="8.3" data-path="inf-stats.html"><a href="inf-stats.html#confidence-intervals"><i class="fa fa-check"></i><b>8.3</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="inf-stats.html"><a href="inf-stats.html#hypothesis-testing"><i class="fa fa-check"></i><b>8.3.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="8.3.2" data-path="inf-stats.html"><a href="inf-stats.html#alpha"><i class="fa fa-check"></i><b>8.3.2</b> Alpha</a></li>
<li class="chapter" data-level="8.3.3" data-path="inf-stats.html"><a href="inf-stats.html#type-i-ii-errors"><i class="fa fa-check"></i><b>8.3.3</b> Type I &amp; II Errors</a></li>
<li class="chapter" data-level="8.3.4" data-path="inf-stats.html"><a href="inf-stats.html#textbf-p-values"><i class="fa fa-check"></i><b>8.3.4</b> <span class="math inline">\(\textbf p\)</span>-Values</a></li>
<li class="chapter" data-level="8.3.5" data-path="inf-stats.html"><a href="inf-stats.html#bonferroni-correction"><i class="fa fa-check"></i><b>8.3.5</b> Bonferroni Correction</a></li>
<li class="chapter" data-level="8.3.6" data-path="inf-stats.html"><a href="inf-stats.html#statistical-power"><i class="fa fa-check"></i><b>8.3.6</b> Statistical Power</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="inf-stats.html"><a href="inf-stats.html#review-questions-6"><i class="fa fa-check"></i><b>8.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="aod.html"><a href="aod.html"><i class="fa fa-check"></i><b>9</b> Analysis of Differences</a>
<ul>
<li class="chapter" data-level="9.1" data-path="aod.html"><a href="aod.html#parametric-vs.-nonparametric-tests"><i class="fa fa-check"></i><b>9.1</b> Parametric vs. Nonparametric Tests</a></li>
<li class="chapter" data-level="9.2" data-path="aod.html"><a href="aod.html#differences-in-discrete-data"><i class="fa fa-check"></i><b>9.2</b> Differences in Discrete Data</a></li>
<li class="chapter" data-level="9.3" data-path="aod.html"><a href="aod.html#differences-in-continuous-data"><i class="fa fa-check"></i><b>9.3</b> Differences in Continuous Data</a></li>
<li class="chapter" data-level="9.4" data-path="aod.html"><a href="aod.html#review-questions-7"><i class="fa fa-check"></i><b>9.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lm.html"><a href="lm.html"><i class="fa fa-check"></i><b>10</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="lm.html"><a href="lm.html#sample-size"><i class="fa fa-check"></i><b>10.1</b> Sample Size</a></li>
<li class="chapter" data-level="10.2" data-path="lm.html"><a href="lm.html#simple-linear-regression"><i class="fa fa-check"></i><b>10.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="10.3" data-path="lm.html"><a href="lm.html#multiple-linear-regression"><i class="fa fa-check"></i><b>10.3</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="10.4" data-path="lm.html"><a href="lm.html#moderation"><i class="fa fa-check"></i><b>10.4</b> Moderation</a></li>
<li class="chapter" data-level="10.5" data-path="lm.html"><a href="lm.html#mediation"><i class="fa fa-check"></i><b>10.5</b> Mediation</a></li>
<li class="chapter" data-level="10.6" data-path="lm.html"><a href="lm.html#review-questions-8"><i class="fa fa-check"></i><b>10.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="lme.html"><a href="lme.html"><i class="fa fa-check"></i><b>11</b> Linear Model Extensions</a>
<ul>
<li class="chapter" data-level="11.1" data-path="lme.html"><a href="lme.html#model-comparisons"><i class="fa fa-check"></i><b>11.1</b> Model Comparisons</a></li>
<li class="chapter" data-level="11.2" data-path="lme.html"><a href="lme.html#hierarchical-regression"><i class="fa fa-check"></i><b>11.2</b> Hierarchical Regression</a></li>
<li class="chapter" data-level="11.3" data-path="lme.html"><a href="lme.html#multilevel-models"><i class="fa fa-check"></i><b>11.3</b> Multilevel Models</a></li>
<li class="chapter" data-level="11.4" data-path="lme.html"><a href="lme.html#polynomial-regression"><i class="fa fa-check"></i><b>11.4</b> Polynomial Regression</a></li>
<li class="chapter" data-level="11.5" data-path="lme.html"><a href="lme.html#review-questions-9"><i class="fa fa-check"></i><b>11.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="log.html"><a href="log.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="log.html"><a href="log.html#binomial-logistic-regression"><i class="fa fa-check"></i><b>12.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="12.2" data-path="log.html"><a href="log.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>12.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="12.3" data-path="log.html"><a href="log.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>12.3</b> Ordinal Logistic Regression</a></li>
<li class="chapter" data-level="12.4" data-path="log.html"><a href="log.html#review-questions-10"><i class="fa fa-check"></i><b>12.4</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="pred-mod.html"><a href="pred-mod.html"><i class="fa fa-check"></i><b>13</b> Predictive Modeling</a>
<ul>
<li class="chapter" data-level="13.1" data-path="pred-mod.html"><a href="pred-mod.html#cross-validation"><i class="fa fa-check"></i><b>13.1</b> Cross-Validation</a></li>
<li class="chapter" data-level="13.2" data-path="pred-mod.html"><a href="pred-mod.html#model-performance"><i class="fa fa-check"></i><b>13.2</b> Model Performance</a></li>
<li class="chapter" data-level="13.3" data-path="pred-mod.html"><a href="pred-mod.html#bias-variance-tradeoff"><i class="fa fa-check"></i><b>13.3</b> Bias-Variance Tradeoff</a></li>
<li class="chapter" data-level="13.4" data-path="pred-mod.html"><a href="pred-mod.html#tree-based-algorithms"><i class="fa fa-check"></i><b>13.4</b> Tree-Based Algorithms</a></li>
<li class="chapter" data-level="13.5" data-path="pred-mod.html"><a href="pred-mod.html#predictive-modeling"><i class="fa fa-check"></i><b>13.5</b> Predictive Modeling</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="pred-mod.html"><a href="pred-mod.html#classification"><i class="fa fa-check"></i><b>13.5.1</b> Classification</a></li>
<li class="chapter" data-level="13.5.2" data-path="pred-mod.html"><a href="pred-mod.html#forecasting"><i class="fa fa-check"></i><b>13.5.2</b> Forecasting</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="pred-mod.html"><a href="pred-mod.html#review-questions-11"><i class="fa fa-check"></i><b>13.6</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="unsup-lrn.html"><a href="unsup-lrn.html"><i class="fa fa-check"></i><b>14</b> Unsupervised Learning</a>
<ul>
<li class="chapter" data-level="14.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#factor-analysis"><i class="fa fa-check"></i><b>14.1</b> Factor Analysis</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#exploratory-factor-analysis-efa"><i class="fa fa-check"></i><b>14.1.1</b> Exploratory Factor Analysis (EFA)</a></li>
<li class="chapter" data-level="14.1.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#confirmatory-factor-analysis-cfa"><i class="fa fa-check"></i><b>14.1.2</b> Confirmatory Factor Analysis (CFA)</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#clustering"><i class="fa fa-check"></i><b>14.2</b> Clustering</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#k-means-clustering"><i class="fa fa-check"></i><b>14.2.1</b> <span class="math inline">\(K\)</span>-Means Clustering</a></li>
<li class="chapter" data-level="14.2.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#hierarchical-clustering"><i class="fa fa-check"></i><b>14.2.2</b> Hierarchical Clustering</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="unsup-lrn.html"><a href="unsup-lrn.html#review-questions-12"><i class="fa fa-check"></i><b>14.3</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="data-viz.html"><a href="data-viz.html"><i class="fa fa-check"></i><b>15</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="15.1" data-path="data-viz.html"><a href="data-viz.html#best-practices"><i class="fa fa-check"></i><b>15.1</b> Best Practices</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="data-viz.html"><a href="data-viz.html#color-palette"><i class="fa fa-check"></i><b>15.1.1</b> Color Palette</a></li>
<li class="chapter" data-level="15.1.2" data-path="data-viz.html"><a href="data-viz.html#chart-borders"><i class="fa fa-check"></i><b>15.1.2</b> Chart Borders</a></li>
<li class="chapter" data-level="15.1.3" data-path="data-viz.html"><a href="data-viz.html#zero-baseline"><i class="fa fa-check"></i><b>15.1.3</b> Zero Baseline</a></li>
<li class="chapter" data-level="15.1.4" data-path="data-viz.html"><a href="data-viz.html#intuitive-layout"><i class="fa fa-check"></i><b>15.1.4</b> Intuitive Layout</a></li>
<li class="chapter" data-level="15.1.5" data-path="data-viz.html"><a href="data-viz.html#preattentive-attributes"><i class="fa fa-check"></i><b>15.1.5</b> Preattentive Attributes</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="data-viz.html"><a href="data-viz.html#step-by-step-visual-upgrade"><i class="fa fa-check"></i><b>15.2</b> Step-by-Step Visual Upgrade</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="data-viz.html"><a href="data-viz.html#step-1-build-bar-chart-with-defaults"><i class="fa fa-check"></i><b>15.2.1</b> Step 1: Build Bar Chart with Defaults</a></li>
<li class="chapter" data-level="15.2.2" data-path="data-viz.html"><a href="data-viz.html#step-2-remove-legend"><i class="fa fa-check"></i><b>15.2.2</b> Step 2: Remove Legend</a></li>
<li class="chapter" data-level="15.2.3" data-path="data-viz.html"><a href="data-viz.html#step-3-assign-colors-strategically"><i class="fa fa-check"></i><b>15.2.3</b> Step 3: Assign Colors Strategically</a></li>
<li class="chapter" data-level="15.2.4" data-path="data-viz.html"><a href="data-viz.html#step-4-add-axis-titles-and-margins"><i class="fa fa-check"></i><b>15.2.4</b> Step 4: Add Axis Titles and Margins</a></li>
<li class="chapter" data-level="15.2.5" data-path="data-viz.html"><a href="data-viz.html#step-5-add-left-justified-title"><i class="fa fa-check"></i><b>15.2.5</b> Step 5: Add Left-Justified Title</a></li>
<li class="chapter" data-level="15.2.6" data-path="data-viz.html"><a href="data-viz.html#step-6-remove-background"><i class="fa fa-check"></i><b>15.2.6</b> Step 6: Remove Background</a></li>
<li class="chapter" data-level="15.2.7" data-path="data-viz.html"><a href="data-viz.html#step-7-remove-axis-ticks"><i class="fa fa-check"></i><b>15.2.7</b> Step 7: Remove Axis Ticks</a></li>
<li class="chapter" data-level="15.2.8" data-path="data-viz.html"><a href="data-viz.html#step-8-mute-titles"><i class="fa fa-check"></i><b>15.2.8</b> Step 8: Mute Titles</a></li>
<li class="chapter" data-level="15.2.9" data-path="data-viz.html"><a href="data-viz.html#step-9-flip-axes"><i class="fa fa-check"></i><b>15.2.9</b> Step 9: Flip Axes</a></li>
<li class="chapter" data-level="15.2.10" data-path="data-viz.html"><a href="data-viz.html#step-10-sort-data"><i class="fa fa-check"></i><b>15.2.10</b> Step 10: Sort Data</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="data-viz.html"><a href="data-viz.html#visualization-types"><i class="fa fa-check"></i><b>15.3</b> Visualization Types</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="data-viz.html"><a href="data-viz.html#tables"><i class="fa fa-check"></i><b>15.3.1</b> Tables</a></li>
<li class="chapter" data-level="15.3.2" data-path="data-viz.html"><a href="data-viz.html#heatmaps"><i class="fa fa-check"></i><b>15.3.2</b> Heatmaps</a></li>
<li class="chapter" data-level="15.3.3" data-path="data-viz.html"><a href="data-viz.html#scatterplots"><i class="fa fa-check"></i><b>15.3.3</b> Scatterplots</a></li>
<li class="chapter" data-level="15.3.4" data-path="data-viz.html"><a href="data-viz.html#line-graphs"><i class="fa fa-check"></i><b>15.3.4</b> Line Graphs</a></li>
<li class="chapter" data-level="15.3.5" data-path="data-viz.html"><a href="data-viz.html#slopegraphs"><i class="fa fa-check"></i><b>15.3.5</b> Slopegraphs</a></li>
<li class="chapter" data-level="15.3.6" data-path="data-viz.html"><a href="data-viz.html#bar-charts"><i class="fa fa-check"></i><b>15.3.6</b> Bar Charts</a></li>
<li class="chapter" data-level="15.3.7" data-path="data-viz.html"><a href="data-viz.html#combination-charts"><i class="fa fa-check"></i><b>15.3.7</b> Combination Charts</a></li>
<li class="chapter" data-level="15.3.8" data-path="data-viz.html"><a href="data-viz.html#waterfall-charts"><i class="fa fa-check"></i><b>15.3.8</b> Waterfall Charts</a></li>
<li class="chapter" data-level="15.3.9" data-path="data-viz.html"><a href="data-viz.html#waffle-charts"><i class="fa fa-check"></i><b>15.3.9</b> Waffle Charts</a></li>
<li class="chapter" data-level="15.3.10" data-path="data-viz.html"><a href="data-viz.html#sankey-diagrams"><i class="fa fa-check"></i><b>15.3.10</b> Sankey Diagrams</a></li>
<li class="chapter" data-level="15.3.11" data-path="data-viz.html"><a href="data-viz.html#pie-charts"><i class="fa fa-check"></i><b>15.3.11</b> Pie Charts</a></li>
<li class="chapter" data-level="15.3.12" data-path="data-viz.html"><a href="data-viz.html#d-visuals"><i class="fa fa-check"></i><b>15.3.12</b> 3D Visuals</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="data-viz.html"><a href="data-viz.html#elegant-data-visualization"><i class="fa fa-check"></i><b>15.4</b> Elegant Data Visualization</a></li>
<li class="chapter" data-level="15.5" data-path="data-viz.html"><a href="data-viz.html#review-questions-13"><i class="fa fa-check"></i><b>15.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="storytelling.html"><a href="storytelling.html"><i class="fa fa-check"></i><b>16</b> Data Storytelling</a>
<ul>
<li class="chapter" data-level="16.1" data-path="storytelling.html"><a href="storytelling.html#know-your-audience"><i class="fa fa-check"></i><b>16.1</b> Know Your Audience</a></li>
<li class="chapter" data-level="16.2" data-path="storytelling.html"><a href="storytelling.html#production-status"><i class="fa fa-check"></i><b>16.2</b> Production Status</a></li>
<li class="chapter" data-level="16.3" data-path="storytelling.html"><a href="storytelling.html#structural-elements"><i class="fa fa-check"></i><b>16.3</b> Structural Elements</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="storytelling.html"><a href="storytelling.html#tldr"><i class="fa fa-check"></i><b>16.3.1</b> TL;DR</a></li>
<li class="chapter" data-level="16.3.2" data-path="storytelling.html"><a href="storytelling.html#purpose"><i class="fa fa-check"></i><b>16.3.2</b> Purpose</a></li>
<li class="chapter" data-level="16.3.3" data-path="storytelling.html"><a href="storytelling.html#methodology"><i class="fa fa-check"></i><b>16.3.3</b> Methodology</a></li>
<li class="chapter" data-level="16.3.4" data-path="storytelling.html"><a href="storytelling.html#results"><i class="fa fa-check"></i><b>16.3.4</b> Results</a></li>
<li class="chapter" data-level="16.3.5" data-path="storytelling.html"><a href="storytelling.html#limitations"><i class="fa fa-check"></i><b>16.3.5</b> Limitations</a></li>
<li class="chapter" data-level="16.3.6" data-path="storytelling.html"><a href="storytelling.html#next-steps"><i class="fa fa-check"></i><b>16.3.6</b> Next Steps</a></li>
<li class="chapter" data-level="16.3.7" data-path="storytelling.html"><a href="storytelling.html#appendix"><i class="fa fa-check"></i><b>16.3.7</b> Appendix</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="storytelling.html"><a href="storytelling.html#qa"><i class="fa fa-check"></i><b>16.4</b> Q&amp;A</a></li>
<li class="chapter" data-level="16.5" data-path="storytelling.html"><a href="storytelling.html#review-questions-14"><i class="fa fa-check"></i><b>16.5</b> Review Questions</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="bibli.html"><a href="bibli.html"><i class="fa fa-check"></i><b>17</b> Bibliography</a></li>
<li class="chapter" data-level="18" data-path="storytelling.html"><a href="storytelling.html#appendix"><i class="fa fa-check"></i><b>18</b> Appendix</a>
<ul>
<li class="chapter" data-level="18.1" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>18.1</b> 4D Framework</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="appendix.html"><a href="appendix.html#discover"><i class="fa fa-check"></i><b>18.1.1</b> Discover</a></li>
<li class="chapter" data-level="18.1.2" data-path="appendix.html"><a href="appendix.html#design"><i class="fa fa-check"></i><b>18.1.2</b> Design</a></li>
<li class="chapter" data-level="18.1.3" data-path="appendix.html"><a href="appendix.html#develop"><i class="fa fa-check"></i><b>18.1.3</b> Develop</a></li>
<li class="chapter" data-level="18.1.4" data-path="appendix.html"><a href="appendix.html#deliver"><i class="fa fa-check"></i><b>18.1.4</b> Deliver</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="appendix.html"><a href="appendix.html#data-visualization"><i class="fa fa-check"></i><b>18.2</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="appendix.html"><a href="appendix.html#step-by-step-visual-upgrade-1"><i class="fa fa-check"></i><b>18.2.1</b> Step-by-Step Visual Upgrade</a></li>
<li class="chapter" data-level="18.2.2" data-path="appendix.html"><a href="appendix.html#tables-1"><i class="fa fa-check"></i><b>18.2.2</b> Tables</a></li>
<li class="chapter" data-level="18.2.3" data-path="appendix.html"><a href="appendix.html#heatmaps-1"><i class="fa fa-check"></i><b>18.2.3</b> Heatmaps</a></li>
<li class="chapter" data-level="18.2.4" data-path="appendix.html"><a href="appendix.html#scatterplots-1"><i class="fa fa-check"></i><b>18.2.4</b> Scatterplots</a></li>
<li class="chapter" data-level="18.2.5" data-path="appendix.html"><a href="appendix.html#line-charts"><i class="fa fa-check"></i><b>18.2.5</b> Line Charts</a></li>
<li class="chapter" data-level="18.2.6" data-path="appendix.html"><a href="appendix.html#slopegraphs-1"><i class="fa fa-check"></i><b>18.2.6</b> Slopegraphs</a></li>
<li class="chapter" data-level="18.2.7" data-path="appendix.html"><a href="appendix.html#bar-charts-1"><i class="fa fa-check"></i><b>18.2.7</b> Bar Charts</a></li>
<li class="chapter" data-level="18.2.8" data-path="appendix.html"><a href="appendix.html#combination-charts-1"><i class="fa fa-check"></i><b>18.2.8</b> Combination Charts</a></li>
<li class="chapter" data-level="18.2.9" data-path="appendix.html"><a href="appendix.html#waterfall-charts-1"><i class="fa fa-check"></i><b>18.2.9</b> Waterfall Charts</a></li>
<li class="chapter" data-level="18.2.10" data-path="appendix.html"><a href="appendix.html#waffle-charts-1"><i class="fa fa-check"></i><b>18.2.10</b> Waffle Charts</a></li>
<li class="chapter" data-level="18.2.11" data-path="appendix.html"><a href="appendix.html#sankey-diagrams-1"><i class="fa fa-check"></i><b>18.2.11</b> Sankey Diagrams</a></li>
<li class="chapter" data-level="18.2.12" data-path="appendix.html"><a href="appendix.html#pie-charts-1"><i class="fa fa-check"></i><b>18.2.12</b> Pie Charts</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Fundamentals of People Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="log" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">12</span> Logistic Regression<a href="log.html#log" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Logistic regression</strong> is a type of <strong>generalized linear model</strong>, which is a family of models for which key linear assumptions are relaxed. Logistic regression is an excellent tool for modeling relationships with outcomes that are not measured on a continuous scale (a key requirement for linear regression). Logistic regression is often leveraged to model the probability of observations belonging to different classes of a categorical outcome, and this type of modeling is known as <strong>classification</strong>. The context for classification can be binomial for two classes (e.g., active/inactive, promoted/not promoted), multinomial for multiple unordered classes (e.g., job family, location), or ordinal for multiple ordered classes (e.g., survey items measured on a Likert scale, performance level, education level). Regardless of the outcome variable’s classes, logistic regression is in fact a type of <em>regression</em> analysis, which by definition returns a numeric outcome – and probabilities are numeric! Logistic regression accomplishes this by using a link function to generalize the linear model for non-continuous outcomes.</p>
<p>You may be wondering why linear regression cannot be implemented when the categorical outcome is dummy coded as outlined in Chapter <a href="data-prep.html#data-prep">6</a>. In a binary case, in which the categorical response has been coded as 1/0, least squares regression would produce an estimate for <span class="math inline">\(\hat\beta X\)</span> that represents the estimated probability of the outcome coded as 1 given <span class="math inline">\(X\)</span>. For example, if attrition is the binary outcome and <span class="math inline">\(Y = 1\)</span> for employees who left and <span class="math inline">\(Y = 0\)</span> for employees who stayed, <span class="math inline">\(\hat Y &gt; .5\)</span> could lend to a termination prediction assuming this is an appropriate probability threshold. Linear regression may produce estimates lower than 0 and higher than 1, however, which complicates the interpretation of estimates as probabilities.</p>
<p>This issue is not limited to binary categorical outcomes. Response variables with more than 2 categories cannot naturally be converted into quantitative values that are appropriate for linear regression. Instead of modeling the response directly as in linear regression, logistic regression models the probability of an outcome’s class given values for one or more predictors. For example, we can leverage our <code>employees</code> dataset to model the probability of <code>active</code> given a value for <code>interview_rating</code>, which would be written as <span class="math inline">\(Pr\)</span>(<code>active</code> = Yes | <code>interview_rating</code>) or simply, <span class="math inline">\(p\)</span>(<code>inteview_rating</code>). A probability of <code>active</code> = Yes will be estimated for a given value of <code>interview_rating</code>, and the probability threshold for determining the predicted class needs to be defined based on the business context. If we want to minimize false positives (i.e., incorrectly flagging at-risk employees who do not actually leave), we may set the threshold to something north of .5 (e.g., .7) to gain more confidence that those classified into the termination class are highly likely to exit.</p>
<div id="binomial-logistic-regression" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Binomial Logistic Regression<a href="log.html#binomial-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Since estimating a binary outcome using linear regression can result in <span class="math inline">\(p(X)\)</span> &lt; 0 for some values of <span class="math inline">\(X\)</span> and <span class="math inline">\(p\)</span>(<span class="math inline">\(X\)</span>) &gt; 1 for others, we need a function that constrains the output to a [0,1] interval. For logistic regression, the <em>logistic</em> function is used. This function converts the linear model, <span class="math inline">\(p(X) = \beta_0 + \beta_1 X\)</span>, to the following form:</p>
<p><span class="math display">\[ p(X) = \frac{e^{\beta_0 + \beta_1 X}}{1+e^{\beta_0 + \beta_1 X}} \]</span></p>
<p>Irrespective of the value of <span class="math inline">\(X\)</span>, the logistic function will always produce a sigmoidal (<em>S-shaped</em>) curve.</p>
<p>Taking the ratio of <span class="math inline">\(\frac {p(X)}{1 - p(X)}\)</span> will give the odds of the outcome, which ranges between 0 (very low) and <span class="math inline">\(\infty\)</span> (very high). The logarithm of this ratio, <span class="math inline">\(\log(\frac {p(X)}{1 - p(X)})\)</span>, is known as the <em>log odds</em> or <em>logit</em>, and is fundamental to logistic regression. Log odds is a <em>monotonic transformation</em>, meaning the greater the odds, the greater the log of odds (and vice versa).</p>
<p>Recall that in linear regression, the coefficient <span class="math inline">\(\beta\)</span> on a predictor is interpreted as the average change in <span class="math inline">\(Y\)</span> for a one-unit increase in the respective predictor’s value. In logistic regression, the interpretation is similar but rather than <span class="math inline">\(\beta\)</span> representing the average change in <span class="math inline">\(Y\)</span>, it represents the average unit change in the <em>log of the odds</em> for a one-unit increase in the predictor’s value.</p>
<p>In R, the <code>glm()</code> function is used in conjunction with the <code>family = binomial</code> argument to fit a logistic regression model. As we covered in Chapter <a href="inf-stats.html#inf-stats">8</a>, discrete probability distributions can be leveraged to model different types of nominal variables, and the binomial distribution is appropriate for a sequence of independent observations with only two outcomes – such as our <code>active</code> variable featuring only <em>yes</em> and <em>no</em> values. Therefore, we need to pass the <code>family = binomial</code> argument into the <code>glm()</code> function. The formula passed into the function is structured consistent with the <code>lm()</code> function used for linear regression: <code>glm(y ~ x, data)</code>.</p>
<pre><code>## 
## Call:
## glm(formula = active ~ interview_rating, family = &quot;binomial&quot;, 
##     data = employees)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -3.03045   0.00000   0.00002   0.00531   2.06562  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)       -74.486     10.333  -7.208 5.67e-13 ***
## interview_rating   21.963      2.997   7.329 2.32e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1298.58  on 1469  degrees of freedom
## Residual deviance:  103.27  on 1468  degrees of freedom
## AIC: 107.27
## 
## Number of Fisher Scoring iterations: 11</code></pre>
<p>The output shown in Figure <a href="#fig:glm-rating"><strong>??</strong></a> has some differences relative to the output of a linear regression model.</p>
<ul>
<li><code>Estimate</code>: Average change in the log of odds for each one-unit increase in the value of the predictor</li>
<li><code>z value</code>: Ratio of <code>Estimate</code> / <code>Standard Error</code>. Assuming <span class="math inline">\(\alpha\)</span> = .05, a <span class="math inline">\(|z\)</span>-value<span class="math inline">\(|\)</span> &gt;= 2 (2<span class="math inline">\(s\)</span> of the mean) is a good rule of thumb for achieving statistical significance per the properties of the normal distribution.</li>
<li><code>Null deviance</code>: Measure of how well the response can be predicted by a model with only an intercept term; the lower the number, the better the fit.</li>
<li><code>Residual deviance</code>: Measure of how well the response can be predicted by a model with <span class="math inline">\(p\)</span> predictors; the lower the number, the better the fit. The larger the delta between residual and null deviance, the better the model with <span class="math inline">\(p\)</span> predictors relative to the intercept-only model.</li>
</ul>
<p>Given the positive coefficient on <code>interview_rating</code>, we can interpret this to mean that for each one-unit increase in the average interviewer rating during the onsite stage of the employee’s recruiting process, the log of the odds of the employee staying with the organization (<code>active</code> status of <code>Yes</code> coded as <span class="math inline">\(1\)</span>) increases by 21.96.</p>
<p>To illustrate why the logistic function is necessary, let’s demonstrate differences in applying linear and logistic regression models by regressing a binary outcome <code>active</code> onto <code>interview_rating</code>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:lm-glm-compare"></span>
<img src="The_Fundamentals_of_People_Analytics_files/figure-html/lm-glm-compare-1.png" alt="Linear (left) and logistic (right) functions applied to models regressing active status (1/0) onto median interviewer rating" width="100%" />
<p class="caption">
Figure 12.1: Linear (left) and logistic (right) functions applied to models regressing active status (1/0) onto median interviewer rating
</p>
</div>
<p>Figure <a href="log.html#fig:lm-glm-compare">12.1</a> illustrates that for high values of <code>interview_rating</code>, a linear model would estimate probabilities for <code>active</code> that are greater than 1. Since probabilities range from 0 (impossible) to 1 (certain), anything outside the [0,1] interval does not make sense. On the other hand, the logistic function produces the <em>S-shaped</em> curve described previously. Using the logistic function, the probabilities are constrained to the [0,1] interval, and the visual reflects the fact that <code>active</code> can be perfectly predicted for low and high values of <code>interview_rating</code> but it is a mixed bag for values in the middle of the range (3.3 - 3.6).</p>
<p>It is often helpful to explain the relationship between a predictor and binary outcome in terms of a percentage increase or decrease. When <span class="math inline">\(\beta = 1\)</span>, this indicates that the likelihood of the outcome is identical between the two groups of the predictor. If we exponentiate the coefficients, we can convert the log odds into odds ratios to facilitate a more intuitive interpretation. Therefore, <span class="math inline">\((exp(\beta) - 1) * 100\)</span> will provide the percentage increase or decrease in the odds of the <em>included</em> group relative to the <em>omitted</em> group.</p>
<p>For example, Figure <a href="#fig:glm-ot-lvl"><strong>??</strong></a> provides the log odds for <code>active</code> regressed onto two binary predictors: <code>overtime</code> and <code>job_lvl2plus</code>.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="log.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy-coded variable for job level 2+</span></span>
<span id="cb389-2"><a href="log.html#cb389-2" aria-hidden="true" tabindex="-1"></a>employees<span class="sc">$</span>job_lvl2plus <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(employees<span class="sc">$</span>job_lvl <span class="sc">&gt;</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb389-3"><a href="log.html#cb389-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb389-4"><a href="log.html#cb389-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a logistic regression model</span></span>
<span id="cb389-5"><a href="log.html#cb389-5" aria-hidden="true" tabindex="-1"></a>glm.fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(active <span class="sc">~</span> overtime <span class="sc">+</span> job_lvl2plus, <span class="at">data =</span> employees, <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb389-6"><a href="log.html#cb389-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb389-7"><a href="log.html#cb389-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce model summary</span></span>
<span id="cb389-8"><a href="log.html#cb389-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = active ~ overtime + job_lvl2plus, family = &quot;binomial&quot;, 
##     data = employees)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3688   0.3532   0.3532   0.6300   1.1270  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    1.5163     0.1192  12.718  &lt; 2e-16 ***
## overtimeYes   -1.3965     0.1522  -9.176  &lt; 2e-16 ***
## job_lvl2plus   1.2270     0.1523   8.055 7.93e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1298.6  on 1469  degrees of freedom
## Residual deviance: 1149.8  on 1467  degrees of freedom
## AIC: 1155.8
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We can convert these coefficients into odds ratios by exponentiating the coefficients:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="log.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return exponentiated coefficients</span></span>
<span id="cb391-2"><a href="log.html#cb391-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(glm.fit))</span></code></pre></div>
<pre><code>##  (Intercept)  overtimeYes job_lvl2plus 
##    4.5551147    0.2474668    3.4108303</code></pre>
<p>The exponentiated coefficient on <code>overtime</code> is <span class="math inline">\(exp(\beta) = .25\)</span>, so there is a <span class="math inline">\((1 - .25) * 100 = 75%\)</span> percent <em>decrease</em> in the odds of being active for employees who work overtime (since <code>overtime = Yes</code> is the included group) relative to those who do not work overtime. The exponentiated coefficient on <code>job_lvl2plus</code> is <span class="math inline">\(exp(\beta) = 3.41\)</span>, so there is a <span class="math inline">\((3.41 - 1) * 100 = 241%\)</span> percent <em>increase</em> in the odds of being active for those with a job level of 2 or greater relative to those with a job level of 1 (i.e., attrition is a larger concern for level 1 employees).</p>
<p>Generalized linear mixed models can be fitted using the <code>glmer()</code> function from the <code>lme4</code> library. The syntax is identical to the illustration of <code>lmer()</code> for multilevel linear models in Chapter <a href="lm.html#lm">10</a> with the exception of needing to define <code>family</code> as an additional argument.</p>
<p>A juxtaposition of <code>glm()</code> and <code>glmer()</code> fits for logistic regression is shown in the following block of code. The mixed model example features an additional random (group-level) effect on <code>business_travel</code> via <code>1 | business_travel</code>, and fixed (observation-level) effects on remaining predictors which are consistent with the standard logistic regression model:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="log.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb393-2"><a href="log.html#cb393-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb393-3"><a href="log.html#cb393-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb393-4"><a href="log.html#cb393-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic model</span></span>
<span id="cb393-5"><a href="log.html#cb393-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(active <span class="sc">~</span> overtime <span class="sc">+</span> job_lvl2plus, <span class="at">data =</span> employees, <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>)</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = active ~ overtime + job_lvl2plus, family = &quot;binomial&quot;, 
##     data = employees)
## 
## Coefficients:
##  (Intercept)   overtimeYes  job_lvl2plus  
##        1.516        -1.396         1.227  
## 
## Degrees of Freedom: 1469 Total (i.e. Null);  1467 Residual
## Null Deviance:       1299 
## Residual Deviance: 1150  AIC: 1156</code></pre>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="log.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic mixed model</span></span>
<span id="cb395-2"><a href="log.html#cb395-2" aria-hidden="true" tabindex="-1"></a>lme4<span class="sc">::</span><span class="fu">glmer</span>(active <span class="sc">~</span> overtime <span class="sc">+</span> job_lvl2plus <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> business_travel), <span class="at">data =</span> employees, <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>)</span></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: active ~ overtime + job_lvl2plus + (1 | business_travel)
##    Data: employees
##       AIC       BIC    logLik  deviance  df.resid 
## 1148.0596 1169.2317 -570.0298 1140.0596      1466 
## Random effects:
##  Groups          Name        Std.Dev.
##  business_travel (Intercept) 0.4351  
## Number of obs: 1470, groups:  business_travel, 3
## Fixed Effects:
##  (Intercept)   overtimeYes  job_lvl2plus  
##        1.546        -1.382         1.223</code></pre>
</div>
<div id="multinomial-logistic-regression" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Multinomial Logistic Regression<a href="log.html#multinomial-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Multinomial logistic regression</strong> is used to estimate the probability of an unordered categorical response with <span class="math inline">\(K&gt;2\)</span> classes. With an understanding of binomial logistic regression, extending the binomial model to a multinomial logistic regression model should be relatively intuitive.</p>
<p>To extend the binomial model to a multinomial context, we need to first identify a reference level. This decision may be arbitrary or guided by the research question or hypothesis, but the decision is nonetheless important as it impacts how the model coefficients are interpreted – always relative to the reference level. With the reference level defined, we can then express the multinomial logistic regression model as:</p>
<p><span class="math display">\[ Pr(Y = k | X = x) = \frac{e^{\beta_{k0} + \beta_{k1} x_1 + ... + \beta_{kp} x_p}}{1+ \displaystyle\sum_{j=1}^{K-1} e^{\beta_{j0} + \beta_{j1} x_1 + ... + \beta_{jp} x_p}}, \]</span></p>
<p>where <span class="math inline">\(K\)</span> is the reference class, <span class="math inline">\(j\)</span> is a <span class="math inline">\(K-1\)</span> non-reference level, and <span class="math inline">\(k\)</span> is the specified class for which the probability is being estimated on the basis of values for one or more <span class="math inline">\(X\)</span> predictors.</p>
<p>Consider <code>dept</code> from our <code>employees</code> data, which has values of <code>Research &amp; Development</code>, <code>Sales</code>, and <code>Human Resources</code>. This is a nominal variable because differences in these levels are not ordered in the same way job levels ranging from 1 to 10 or Likert scales ranging from 1 to 5 are. Employees in the Sales department may be greater in number relative to employees in the Human Resources department, for example, but it would not be appropriate to assign to the Sales department a numeric value that indicates it is <em>higher</em> or <em>better</em> relative to the Human Resources department.</p>
<p>Multinomial models are essentially a collection of binomial models which compare the log-odds of each non-reference category to the specified reference category. If the Human Resources department is identified as the reference category <span class="math inline">\(K\)</span>, then <span class="math inline">\(\beta_{k0}\)</span> for <span class="math inline">\(k = Sales\)</span> can be interpreted as the log odds of Sales department membership relative to Human Resources department membership in the following equation:</p>
<p><span class="math display">\[ log(\frac{Pr(Y = k | X = x)} {Pr(Y = K | X = x)}) = \beta_{k0} + \beta_{k1}x_1 + ... + \beta_{xp}x_p \]</span></p>
<p>Depending on the research objective, it may be appropriate to compute the odds of one category relative to all other categories. This can actually be accomplished using binomial regression if the category of interest is coded as 1 and all other categories are coded as 0. In this case, the reference for the binomial model is a <em>collection</em> of <span class="math inline">\(K-1\)</span> categories. If understanding the odds of <em>each category</em> relative to a reference category is more appropriate based on the research objective, multinomial logistic regression is the proper model.</p>
<p>Let’s illustrate how to implement multinomial logistic regression by determining how variables in the <code>employees</code> dataset help in classifying employees into departments. To build this model in R, we will use the <code>multinom</code> function from the <code>nnet</code> package. It is important that the nominal response variable is defined as a factor before implementing multinomial logistic regression, so we will first convert the data type of <code>dept</code> from its native character type to a factor. We also need to identify the reference department against which the probability of each of the other departments will be evaluated; we will define this using the <code>ref</code> argument within the <code>relevel()</code> function:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="log.html#cb397-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb397-2"><a href="log.html#cb397-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb397-3"><a href="log.html#cb397-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-4"><a href="log.html#cb397-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert dept to factor</span></span>
<span id="cb397-5"><a href="log.html#cb397-5" aria-hidden="true" tabindex="-1"></a>employees<span class="sc">$</span>dept <span class="ot">&lt;-</span> <span class="fu">factor</span>(employees<span class="sc">$</span>dept)</span>
<span id="cb397-6"><a href="log.html#cb397-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-7"><a href="log.html#cb397-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify reference level</span></span>
<span id="cb397-8"><a href="log.html#cb397-8" aria-hidden="true" tabindex="-1"></a>employees<span class="sc">$</span>dept <span class="ot">&lt;-</span> <span class="fu">relevel</span>(employees<span class="sc">$</span>dept, <span class="at">ref =</span> <span class="st">&quot;Human Resources&quot;</span>)</span>
<span id="cb397-9"><a href="log.html#cb397-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-10"><a href="log.html#cb397-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multinomial logistic regression model</span></span>
<span id="cb397-11"><a href="log.html#cb397-11" aria-hidden="true" tabindex="-1"></a><span class="co"># An omitted group for categorical variables is defined by default</span></span>
<span id="cb397-12"><a href="log.html#cb397-12" aria-hidden="true" tabindex="-1"></a>multinom.fit <span class="ot">&lt;-</span> nnet<span class="sc">::</span><span class="fu">multinom</span>(dept <span class="sc">~</span> overtime <span class="sc">+</span> ed_field, <span class="at">data =</span> employees)</span></code></pre></div>
<pre><code>## # weights:  24 (14 variable)
## initial  value 1614.960064 
## iter  10 value 887.448722
## iter  20 value 833.883230
## iter  30 value 833.513790
## final  value 833.513639 
## converged</code></pre>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="log.html#cb399-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize results from model object</span></span>
<span id="cb399-2"><a href="log.html#cb399-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinom.fit)</span></code></pre></div>
<pre><code>## Call:
## nnet::multinom(formula = dept ~ overtime + ed_field, data = employees)
## 
## Coefficients:
##                        (Intercept) overtimeYes ed_fieldLife Sciences
## Research &amp; Development   -18.92857   0.1674815              22.19842
## Sales                    -19.40948   0.1602262              21.60505
##                        ed_fieldMarketing ed_fieldMedical ed_fieldOther
## Research &amp; Development          25.72879        22.21217      21.93577
## Sales                           37.42515        21.27842      20.96823
##                        ed_fieldTechnical Degree
## Research &amp; Development                  22.0455
## Sales                                   21.5113
## 
## Std. Errors:
##                        (Intercept) overtimeYes ed_fieldLife Sciences
## Research &amp; Development    1.808496   0.3917603              1.817514
## Sales                     1.810390   0.4071887              1.819982
##                        ed_fieldMarketing ed_fieldMedical ed_fieldOther
## Research &amp; Development          8.991934        1.820007      1.864206
## Sales                           8.996707        1.823207      1.874536
##                        ed_fieldTechnical Degree
## Research &amp; Development                  1.84963
## Sales                                   1.85451
## 
## Residual Deviance: 1667.027 
## AIC: 1695.027</code></pre>
<p>Notice the output from the <code>multinom()</code> function is quite limited relative to <code>glm()</code> and <code>lm()</code>. Coefficients and standard errors are provided, but <span class="math inline">\(p\)</span>-values are not available in the output so we will need to calculate them separately.</p>
<p>A new statistical measure is included in the output of this model, <strong>Akaike Information Criterion (AIC)</strong>, which is a score that is helpful for model selection. AIC is calculated by:</p>
<p><span class="math display">\[ AIC = -2\frac{\ell}{n} + 2\frac{k}{n}, \]</span>
where <span class="math inline">\(n\)</span> is the number of observations, <span class="math inline">\(k\)</span> is the number of parameters (predictors + intercept), and <span class="math inline">\(\ell\)</span> is the log likelihood function where:</p>
<p><span class="math display">\[ \ell = -\frac{n}{2}(1 + ln(2\pi) + ln(\frac{1}{n} \displaystyle\sum_{i=1}^{n}(y_i - \hat{y}_i)^2))  \]</span></p>
<p>Just as we compared <span class="math inline">\(R^2\)</span> across linear regression models in Chapter <a href="lm.html#lm">10</a>, AIC can be compared across models to determine which one is a better fit to the data; lower AIC values indicate better fit. Consistent with how the Adjusted <span class="math inline">\(R^2\)</span> statistic adjusts for variables that do not provide information, AIC penalizes models that use more parameters. Therefore, if two models explain the same amount of variance in the response, the model with fewer parameters will achieve a lower AIC score.</p>
<p>To determine whether the coefficients are statistically significant, we need to perform an additional step to compute <span class="math inline">\(p\)</span>-values using <span class="math inline">\(z\)</span> scores:</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="log.html#cb401-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate z-scores</span></span>
<span id="cb401-2"><a href="log.html#cb401-2" aria-hidden="true" tabindex="-1"></a>z_scores <span class="ot">&lt;-</span> <span class="fu">summary</span>(multinom.fit)<span class="sc">$</span>coefficients <span class="sc">/</span> <span class="fu">summary</span>(multinom.fit)<span class="sc">$</span>standard.errors</span>
<span id="cb401-3"><a href="log.html#cb401-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb401-4"><a href="log.html#cb401-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce p-values</span></span>
<span id="cb401-5"><a href="log.html#cb401-5" aria-hidden="true" tabindex="-1"></a>p_values <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_scores))) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb401-6"><a href="log.html#cb401-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb401-7"><a href="log.html#cb401-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Transpose and display rounded p-values </span></span>
<span id="cb401-8"><a href="log.html#cb401-8" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">t</span>(<span class="fu">round</span>(p_values, <span class="dv">3</span>)))</span></code></pre></div>
<pre><code>##                          Research...Development Sales
## (Intercept)                               0.000 0.000
## overtimeYes                               0.669 0.694
## ed_fieldLife Sciences                     0.000 0.000
## ed_fieldMarketing                         0.004 0.000
## ed_fieldMedical                           0.000 0.000
## ed_fieldOther                             0.000 0.000
## ed_fieldTechnical Degree                  0.000 0.000</code></pre>
<p>These <span class="math inline">\(p\)</span>-values indicate that those who work overtime are not significantly more likely to work in either the Research &amp; Development or Sales departments relative to the Human Resources department. In other words, a considerable portion of employees in all three departments work overtime, so this variable is not helpful in classifying employees into their correct departments. This is evident in Figure <a href="log.html#fig:ot-dept">12.2</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ot-dept"></span>
<img src="The_Fundamentals_of_People_Analytics_files/figure-html/ot-dept-1.png" alt="Overtime by department" width="100%" />
<p class="caption">
Figure 12.2: Overtime by department
</p>
</div>
<p>The <span class="math inline">\(p\)</span>-values indicate that educational background is a strong predictor of department. This is evidenced in Figure <a href="log.html#fig:ed-field-dept">12.3</a>, which shows that each educational field is generally dominated by a single department. This means that we can achieve strong departmental <em>purity</em> on the basis of <code>ed_field</code> alone. All employees who studied Marketing work in Sales and all employees who studied HR work in the HR department. However, those who work in R&amp;D have a variety of educational backgrounds, so the signal is not as clear for these cases and additional variables would be needed to more accurately assign these employees to the correct departments.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ed-field-dept"></span>
<img src="The_Fundamentals_of_People_Analytics_files/figure-html/ed-field-dept-1.png" alt="Department distribution by educational field" width="100%" />
<p class="caption">
Figure 12.3: Department distribution by educational field
</p>
</div>
<p>As we did for binomial logistic regression, we can compute the exponential of model coefficients for the multinomial logistic regression model to convert the log-odds to more intuitive odds ratios:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="log.html#cb403-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Return exponentiated coefficients from model object</span></span>
<span id="cb403-2"><a href="log.html#cb403-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Transpose rows to columns for improved readability</span></span>
<span id="cb403-3"><a href="log.html#cb403-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">t</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(multinom.fit))))</span></code></pre></div>
<pre><code>##                          Research...Development        Sales
## (Intercept)                        6.017654e-09 3.720234e-09
## overtimeYes                        1.182323e+00 1.173776e+00
## ed_fieldLife Sciences              4.371726e+09 2.415207e+09
## ed_fieldMarketing                  1.492349e+11 1.792819e+16
## ed_fieldMedical                    4.432226e+09 1.742213e+09
## ed_fieldOther                      3.361886e+09 1.277572e+09
## ed_fieldTechnical Degree           3.751786e+09 2.199075e+09</code></pre>
<p>Consistent with our approach for binomial logistic regression, we can interpret these exponentiated coefficients in terms of having greater or lesser odds. Importantly, in the multinomial context the odds are <em>relative to the reference category</em> – the Human Resources department in this case.</p>
<p>For example, the odds ratio associated with a Medical educational field is <span class="math inline">\(exp(\beta) = 4.43\)</span> for Research &amp; Development and <span class="math inline">\(exp(\beta) = 1.74\)</span> for Sales. Therefore, those with a Medical education have <span class="math inline">\((4.43 - 1) * 100 = 343%\)</span> greater odds of being in the Research &amp; Development department and <span class="math inline">\((1.74 - 1) * 100 = 74%\)</span> greater odds of being in the Sales department relative to the Human Resources department. We can ignore the odds ratios associated with <code>overtime</code> since this variable does not provide significant information.</p>
</div>
<div id="ordinal-logistic-regression" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Ordinal Logistic Regression<a href="log.html#ordinal-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Many projects in people analytics involve understanding how variables influence ordinal outcomes, such as performance ratings or survey items measured on a Likert scale. Stepwise changes in the levels of ordinal outcomes may or may not be consistent. For example, it may be easy for one to be promoted from job level 1 to 2 but relatively difficult to progress from 5 to 6. Linear regression should not be used in these settings, as linear assumptions are designed for data measured on a continuous scale and will not hold for ordinal data. This section will cover <strong>ordinal logistic regression</strong>, which is a modeling technique designed for understanding how variables influence stepwise changes in a multi-class ordinal outcome.</p>
<p>Beyond the universal data screening procedures we have covered, such as ensuring problematic collinearity is not present, ordinal logistic regression features a unique <strong>proportional odds assumption</strong> that must be satisfied. This assumption, also known as the <strong>parallel regression assumption</strong>, requires that each independent variable has an equal effect at each level of the ordinal outcome. If the effect varies across levels of the outcome, separate models are needed to accurately reflect the associations with each pair of levels.</p>
<p>Though other approaches exist for modeling ordinal outcomes, the proportional-odds model based on cumulative distribution probabilities is the most common. Its intercepts are dependent on the <span class="math inline">\(j\)</span> levels but slopes are equal as defined by:</p>
<p><span class="math display">\[ log(\frac{Pr(Y \le j)} {Pr(Y &gt; j)}) = \beta_{j0} - \displaystyle\sum_{i=1}^{n} \beta_{1i} x_{1i} + ... + \beta_{pi} x_{pi} \]</span></p>
<p>The implementation of ordinal logistic regression will be demonstrated by evaluating the statistical drivers of engagement. First, we need to define <code>engagement</code> as an ordered factor:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="log.html#cb405-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define ordered factor</span></span>
<span id="cb405-2"><a href="log.html#cb405-2" aria-hidden="true" tabindex="-1"></a>employees<span class="sc">$</span>engagement <span class="ot">&lt;-</span> <span class="fu">ordered</span>(employees<span class="sc">$</span>engagement, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>))</span>
<span id="cb405-3"><a href="log.html#cb405-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb405-4"><a href="log.html#cb405-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify structure of engagement variable</span></span>
<span id="cb405-5"><a href="log.html#cb405-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(employees<span class="sc">$</span>engagement)</span></code></pre></div>
<pre><code>##  Ord.factor w/ 5 levels &quot;1&quot;&lt;&quot;2&quot;&lt;&quot;3&quot;&lt;&quot;4&quot;&lt;..: 3 2 2 3 3 3 4 3 2 3 ...</code></pre>
<p>Next, the proportional odds assumption will be checked using the <strong>Brant test</strong>. The Brant test is a set of comparisons of the separate binary logistic models underlying the overall model (Brant, 1990). This test evaluates whether <span class="math inline">\(\beta_{j1}\)</span> through <span class="math inline">\(\beta_{jp}\)</span> are consistent across each of the <span class="math inline">\(j\)</span> levels. This is done via a <span class="math inline">\(\chi^2\)</span> test to compare coefficients and determine whether observed differences are larger departures from what we would expect by chance. The null hypothesis states that coefficients are not statistically different across the <span class="math inline">\(j\)</span> levels; therefore, <span class="math inline">\(p\)</span> &lt; .05 indicates that significant differences in effects are present across the <span class="math inline">\(j\)</span> levels and, thus, the proportional odds assumption is violated.</p>
<p>We can leverage the <code>brant</code> package in R for this, which is compatible with the <code>polr()</code> function from the <code>MASS</code> package that will be used to perform ordinal logistic regression. Since we will be evaluating model statistics, rather than merely using the model for prediction (the subject of Chapter <a href="pred-mod.html#pred-mod">13</a>), we need to specify the <code>Hess = TRUE</code> argument in the <code>polr()</code> function to include the <em>Hessian matrix</em> (observed information matrix) in the output.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="log.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb407-2"><a href="log.html#cb407-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb407-3"><a href="log.html#cb407-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brant)</span>
<span id="cb407-4"><a href="log.html#cb407-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb407-5"><a href="log.html#cb407-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a ordinal logistic regression model</span></span>
<span id="cb407-6"><a href="log.html#cb407-6" aria-hidden="true" tabindex="-1"></a>ord.fit <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">polr</span>(engagement <span class="sc">~</span> org_tenure, <span class="at">data =</span> employees, <span class="at">Hess =</span> <span class="cn">TRUE</span>)</span>
<span id="cb407-7"><a href="log.html#cb407-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb407-8"><a href="log.html#cb407-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Test proportional odds assumption using the Brant test</span></span>
<span id="cb407-9"><a href="log.html#cb407-9" aria-hidden="true" tabindex="-1"></a>brant<span class="sc">::</span><span class="fu">brant</span>(ord.fit)</span></code></pre></div>
<pre><code>## -------------------------------------------- 
## Test for X2  df  probability 
## -------------------------------------------- 
## Omnibus      0.39    2   0.82
## org_tenure   0.39    2   0.82
## -------------------------------------------- 
## 
## H0: Parallel Regression Assumption holds</code></pre>
<p>Notice the line in the output for the omnibus test, which shows an identical <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(df\)</span>, and <span class="math inline">\(p\)</span>-value to the line associated with <code>org_tenure</code>. <strong>Omnibus tests</strong> are statistical tests which test for the significance of several parameters in a model at once. For example, a one-way ANOVA evaluating differences in mean commute time across three locations is an omnibus test since it has more than two parameters. As we covered in Chapter <a href="aod.html#aod">9</a>, the null hypothesis is rejected in the context of ANOVA if there is at least <em>one</em> difference in complex contrasts – even if the mean commute time is not significantly different between <em>all</em> groups. Test statistics are identical for this ordinal logistic regression model because there is a single predictor, but Brant’s omnibus test investigates equality of coefficients for all predictors jointly in the case of more than two parameters (Martin, 2022). The null and alternative hypotheses for Brant’s omnibus test are:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The odds are proportional for all predictors in the model.</li>
<li><span class="math inline">\(H_A\)</span>: The odds are non-proportional for at least one predictor.</li>
</ul>
<p>The results of Brant’s test indicate that we fail to reject <span class="math inline">\(H_0\)</span> since <span class="math inline">\(p\)</span> = .82 for the omnibus test, so the proportional odds assumption holds for these data. If the model featured more than one predictor, we could also evaluate the statistics on individual predictors – but only to determine for which predictor(s) the proportional odds assumption is violated <em>if</em> <span class="math inline">\(p\)</span> &lt; .05 for the omnibus test. As the number of variables and tests increases, so too does our risk of incorrectly rejecting the proportional odds assumption; therefore, decisions regarding the proportional odds assumption should not be based on statistics for individual predictors alone. Even if the odds are truly proportional for each predictor independently, with 20 predictors we would expect to find one by chance for which <span class="math inline">\(p\)</span> &lt; .05 since our tolerance for a Type I error is 1 in 20 with <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>Since the proportional odds assumption holds, let’s review the model output:</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="log.html#cb409-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize ordinal logistic regression model</span></span>
<span id="cb409-2"><a href="log.html#cb409-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ord.fit)</span></code></pre></div>
<pre><code>## Call:
## MASS::polr(formula = engagement ~ org_tenure, data = employees, 
##     Hess = TRUE)
## 
## Coefficients:
##                Value Std. Error t value
## org_tenure -0.006965   0.008032 -0.8671
## 
## Intercepts:
##     Value      Std. Error t value   
## 1|2    -2.8661     0.1271   -22.5423
## 2|3    -0.8419     0.0804   -10.4703
## 3|4     2.1711     0.1036    20.9479
## 4|5  4122.5567     0.1036 39776.9095
## 
## Residual Deviance: 3084.592 
## AIC: 3094.592</code></pre>
<p>The output provides the average effect of a one-unit increase in <code>org_tenure</code> (Coefficients section) as well as intercepts on each pair of levels for <code>engagement</code> (Intercepts section). The effect of a one-unit increase in <code>org_tenure</code> in moving <code>engagement</code> from one ordinal level to the next is quite small (<span class="math inline">\(\beta = -.007\)</span>). The intercepts are often referred to as cutpoints and can be roughly translated as thresholds. While the intercepts for each cutpoint vary, note that the single coefficient on <code>org_tenure</code> is only possible because our proportional odds assumption holds and the effect is consistent (proportional) across levels of our ordered factor, <code>engagement</code>.</p>
<p>Consistent with the default output from the <code>multinom()</code> function used for multinomial logistic regression, <span class="math inline">\(p\)</span>-values are not provided in the standard output from the <code>polr()</code> function. However, we can calculate them for reasonably large samples by comparing the <span class="math inline">\(t\)</span>-values against the standard normal distribution:</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="log.html#cb411-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store coefficients to df</span></span>
<span id="cb411-2"><a href="log.html#cb411-2" aria-hidden="true" tabindex="-1"></a>coef_df <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(ord.fit))</span>
<span id="cb411-3"><a href="log.html#cb411-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb411-4"><a href="log.html#cb411-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce p-values</span></span>
<span id="cb411-5"><a href="log.html#cb411-5" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(coef_df[, <span class="st">&quot;t value&quot;</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb411-6"><a href="log.html#cb411-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb411-7"><a href="log.html#cb411-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine p values with coefficients df</span></span>
<span id="cb411-8"><a href="log.html#cb411-8" aria-hidden="true" tabindex="-1"></a>coef_df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(coef_df, <span class="st">&quot;p value&quot;</span> <span class="ot">=</span> p)</span>
<span id="cb411-9"><a href="log.html#cb411-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb411-10"><a href="log.html#cb411-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display df contents</span></span>
<span id="cb411-11"><a href="log.html#cb411-11" aria-hidden="true" tabindex="-1"></a>coef_df</span></code></pre></div>
<pre><code>##                    Value  Std. Error      t value       p value
## org_tenure   -0.00696485 0.008032275    -0.867108  3.858828e-01
## 1|2          -2.86612408 0.127144280   -22.542297 1.598105e-112
## 2|3          -0.84185679 0.080404351   -10.470289  1.182814e-25
## 3|4           2.17107818 0.103641956    20.947870  1.962145e-97
## 4|5        4122.55669611 0.103641956 39776.909511  0.000000e+00</code></pre>
<p>We can now estimate the likelihood of a particular observation having a specified level of <span class="math inline">\(Y\)</span>, such as <span class="math inline">\(Y \le 3\)</span>, as follows:</p>
<p><span class="math display">\[ log(\frac{Pr(Y \le 3)} {Pr(Y &gt; 3)}) =  2.17 - .007 x_{orgtenure} \]</span></p>
</div>
<div id="review-questions-10" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Review Questions<a href="log.html#review-questions-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Why can’t linear regression be used when outcome variables are measured on a non-continuous scale?</p></li>
<li><p>What are some examples of hypotheses for which logistic regression would be an appropriate model?</p></li>
<li><p>Why is it helpful to calculate the exponential of log-odds in a logistic regression model?</p></li>
<li><p>What does an odds ratio of 1.25 indicate in a binomial context?</p></li>
<li><p>What does an odds ratio of 0.75 indicate in a multinomial context?</p></li>
<li><p>How does Akaike Information Criterion (AIC) compare to <span class="math inline">\(R^2\)</span> with respect to its purpose and function?</p></li>
<li><p>In what type of R object do ordinal data need to be stored in order to implement ordinal logistic regression?</p></li>
<li><p>Why can’t linear regression be used to understand associations of predictors with an ordinal outcome?</p></li>
<li><p>What does the proportional odds (or parallel regression) assumption assume about model coefficients?</p></li>
<li><p>Why is it important to evaluate Brant’s omnibus test – over the test statistics on independent predictors alone – when determining whether the proportional odds assumption for ordinal logistic regression holds?</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lme.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pred-mod.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["The_Fundamentals_of_People_Analytics.pdf", "The_Fundamentals_of_People_Analytics.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
