<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Univariate &amp; Bivariate Analysis | A Guide through the People Analytics Lifecycle: With Applications in R</title>
  <meta name="description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="generator" content="bookdown 0.24.4 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Univariate &amp; Bivariate Analysis | A Guide through the People Analytics Lifecycle: With Applications in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  <meta name="github-repo" content="crstarbuck/peopleanalytics-lifecycle-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Univariate &amp; Bivariate Analysis | A Guide through the People Analytics Lifecycle: With Applications in R" />
  
  <meta name="twitter:description" content="An end-to-end guide for successful analytics projects in the social sciences" />
  

<meta name="author" content="Craig Starbuck" />


<meta name="date" content="2022-02-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="measure-sampl.html"/>
<link rel="next" href="inf-stats.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Guide through the People Analytics Lifecycle: With Applications in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i><b>1</b> Foreword</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="get-started.html"><a href="get-started.html"><i class="fa fa-check"></i><b>3</b> Getting Started</a><ul>
<li class="chapter" data-level="3.1" data-path="get-started.html"><a href="get-started.html#guiding-principles"><i class="fa fa-check"></i><b>3.1</b> Guiding Principles</a><ul>
<li class="chapter" data-level="3.1.1" data-path="get-started.html"><a href="get-started.html#pro-employee-thinking"><i class="fa fa-check"></i><b>3.1.1</b> Pro Employee Thinking</a></li>
<li class="chapter" data-level="3.1.2" data-path="get-started.html"><a href="get-started.html#quality"><i class="fa fa-check"></i><b>3.1.2</b> Quality</a></li>
<li class="chapter" data-level="3.1.3" data-path="get-started.html"><a href="get-started.html#prioritization"><i class="fa fa-check"></i><b>3.1.3</b> Prioritization</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="get-started.html"><a href="get-started.html#tools"><i class="fa fa-check"></i><b>3.2</b> Tools</a><ul>
<li class="chapter" data-level="3.2.1" data-path="get-started.html"><a href="get-started.html#r"><i class="fa fa-check"></i><b>3.2.1</b> R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="get-started.html"><a href="get-started.html#d-framework"><i class="fa fa-check"></i><b>3.3</b> 4D Framework</a><ul>
<li class="chapter" data-level="3.3.1" data-path="get-started.html"><a href="get-started.html#discover"><i class="fa fa-check"></i><b>3.3.1</b> Discover</a></li>
<li class="chapter" data-level="3.3.2" data-path="get-started.html"><a href="get-started.html#design"><i class="fa fa-check"></i><b>3.3.2</b> Design</a></li>
<li class="chapter" data-level="3.3.3" data-path="get-started.html"><a href="get-started.html#develop"><i class="fa fa-check"></i><b>3.3.3</b> Develop</a></li>
<li class="chapter" data-level="3.3.4" data-path="get-started.html"><a href="get-started.html#deliver"><i class="fa fa-check"></i><b>3.3.4</b> Deliver</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="r-intro.html"><a href="r-intro.html"><i class="fa fa-check"></i><b>4</b> Introduction to R</a></li>
<li class="chapter" data-level="5" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>5</b> Research Methods</a><ul>
<li class="chapter" data-level="5.1" data-path="methods.html"><a href="methods.html#research-designs"><i class="fa fa-check"></i><b>5.1</b> Research Designs</a></li>
<li class="chapter" data-level="5.2" data-path="methods.html"><a href="methods.html#research-methods"><i class="fa fa-check"></i><b>5.2</b> Research Methods</a></li>
<li class="chapter" data-level="5.3" data-path="methods.html"><a href="methods.html#research-questions"><i class="fa fa-check"></i><b>5.3</b> Research Questions</a></li>
<li class="chapter" data-level="5.4" data-path="methods.html"><a href="methods.html#research-hypotheses"><i class="fa fa-check"></i><b>5.4</b> Research Hypotheses</a></li>
<li class="chapter" data-level="5.5" data-path="methods.html"><a href="methods.html#internal-vs.external-validity"><i class="fa fa-check"></i><b>5.5</b> Internal vs. External Validity</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="measure-sampl.html"><a href="measure-sampl.html"><i class="fa fa-check"></i><b>6</b> Measurement &amp; Sampling</a><ul>
<li class="chapter" data-level="6.1" data-path="measure-sampl.html"><a href="measure-sampl.html#variable-types"><i class="fa fa-check"></i><b>6.1</b> Variable Types</a><ul>
<li class="chapter" data-level="6.1.1" data-path="measure-sampl.html"><a href="measure-sampl.html#independent-variables-iv"><i class="fa fa-check"></i><b>6.1.1</b> Independent Variables (IV)</a></li>
<li class="chapter" data-level="6.1.2" data-path="measure-sampl.html"><a href="measure-sampl.html#dependent-variables-dv"><i class="fa fa-check"></i><b>6.1.2</b> Dependent Variables (DV)</a></li>
<li class="chapter" data-level="6.1.3" data-path="measure-sampl.html"><a href="measure-sampl.html#control-variables-cv"><i class="fa fa-check"></i><b>6.1.3</b> Control Variables (CV)</a></li>
<li class="chapter" data-level="6.1.4" data-path="measure-sampl.html"><a href="measure-sampl.html#moderating-variables"><i class="fa fa-check"></i><b>6.1.4</b> Moderating Variables</a></li>
<li class="chapter" data-level="6.1.5" data-path="measure-sampl.html"><a href="measure-sampl.html#mediating-variables"><i class="fa fa-check"></i><b>6.1.5</b> Mediating Variables</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="measure-sampl.html"><a href="measure-sampl.html#measurement-scales"><i class="fa fa-check"></i><b>6.2</b> Measurement Scales</a><ul>
<li class="chapter" data-level="6.2.1" data-path="measure-sampl.html"><a href="measure-sampl.html#discrete-variables"><i class="fa fa-check"></i><b>6.2.1</b> Discrete Variables</a></li>
<li class="chapter" data-level="6.2.2" data-path="measure-sampl.html"><a href="measure-sampl.html#continuous-variables"><i class="fa fa-check"></i><b>6.2.2</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling"><i class="fa fa-check"></i><b>6.3</b> Sampling</a><ul>
<li class="chapter" data-level="6.3.1" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-nonsampling-error"><i class="fa fa-check"></i><b>6.3.1</b> Sampling &amp; Nonsampling Error</a></li>
<li class="chapter" data-level="6.3.2" data-path="measure-sampl.html"><a href="measure-sampl.html#sampling-methods"><i class="fa fa-check"></i><b>6.3.2</b> Sampling Methods</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="measure-sampl.html"><a href="measure-sampl.html#exercises"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html"><i class="fa fa-check"></i><b>7</b> Univariate &amp; Bivariate Analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#univariate-analysis"><i class="fa fa-check"></i><b>7.1</b> Univariate Analysis</a><ul>
<li class="chapter" data-level="7.1.1" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>7.1.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="7.1.2" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#measures-of-spread"><i class="fa fa-check"></i><b>7.1.2</b> Measures of Spread</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#bivariate-analysis"><i class="fa fa-check"></i><b>7.2</b> Bivariate Analysis</a><ul>
<li class="chapter" data-level="7.2.1" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#covariance"><i class="fa fa-check"></i><b>7.2.1</b> Covariance</a></li>
<li class="chapter" data-level="7.2.2" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#correlation"><i class="fa fa-check"></i><b>7.2.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="uni-bi-stats.html"><a href="uni-bi-stats.html#exercises-1"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inf-stats.html"><a href="inf-stats.html"><i class="fa fa-check"></i><b>8</b> Inferential Statistics</a><ul>
<li class="chapter" data-level="8.1" data-path="inf-stats.html"><a href="inf-stats.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a><ul>
<li class="chapter" data-level="8.1.1" data-path="inf-stats.html"><a href="inf-stats.html#probability-distributions"><i class="fa fa-check"></i><b>8.1.1</b> Probability Distributions</a></li>
<li class="chapter" data-level="8.1.2" data-path="inf-stats.html"><a href="inf-stats.html#conditional-probability"><i class="fa fa-check"></i><b>8.1.2</b> Conditional Probability</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inf-stats.html"><a href="inf-stats.html#central-limit-theorem"><i class="fa fa-check"></i><b>8.2</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="8.3" data-path="inf-stats.html"><a href="inf-stats.html#confidence-intervals"><i class="fa fa-check"></i><b>8.3</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="8.3.1" data-path="inf-stats.html"><a href="inf-stats.html#hypothesis-testing"><i class="fa fa-check"></i><b>8.3.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="8.3.2" data-path="inf-stats.html"><a href="inf-stats.html#alpha"><i class="fa fa-check"></i><b>8.3.2</b> Alpha</a></li>
<li class="chapter" data-level="8.3.3" data-path="inf-stats.html"><a href="inf-stats.html#beta"><i class="fa fa-check"></i><b>8.3.3</b> Beta</a></li>
<li class="chapter" data-level="8.3.4" data-path="inf-stats.html"><a href="inf-stats.html#type-i-ii-errors"><i class="fa fa-check"></i><b>8.3.4</b> Type I &amp; II Errors</a></li>
<li class="chapter" data-level="8.3.5" data-path="inf-stats.html"><a href="inf-stats.html#p-values"><i class="fa fa-check"></i><b>8.3.5</b> P-Values</a></li>
<li class="chapter" data-level="8.3.6" data-path="inf-stats.html"><a href="inf-stats.html#bonferroni-correction"><i class="fa fa-check"></i><b>8.3.6</b> Bonferroni Correction</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="inf-stats.html"><a href="inf-stats.html#parametric-vs.nonparametric-tests"><i class="fa fa-check"></i><b>8.4</b> Parametric vs. Nonparametric Tests</a></li>
<li class="chapter" data-level="8.5" data-path="inf-stats.html"><a href="inf-stats.html#exercises-2"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="data-prep.html"><a href="data-prep.html"><i class="fa fa-check"></i><b>9</b> Data Preparation</a><ul>
<li class="chapter" data-level="9.1" data-path="data-prep.html"><a href="data-prep.html#data-wrangling"><i class="fa fa-check"></i><b>9.1</b> Data Wrangling</a></li>
<li class="chapter" data-level="9.2" data-path="data-prep.html"><a href="data-prep.html#feature-engineering"><i class="fa fa-check"></i><b>9.2</b> Feature Engineering</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="aod.html"><a href="aod.html"><i class="fa fa-check"></i><b>10</b> Analysis of Differences</a><ul>
<li class="chapter" data-level="10.1" data-path="aod.html"><a href="aod.html#comparing-2-distributions"><i class="fa fa-check"></i><b>10.1</b> Comparing 2 Distributions</a></li>
<li class="chapter" data-level="10.2" data-path="aod.html"><a href="aod.html#comparing-3-distributions"><i class="fa fa-check"></i><b>10.2</b> Comparing 3+ Distributions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="lm.html"><a href="lm.html"><i class="fa fa-check"></i><b>11</b> Linear Regression</a><ul>
<li class="chapter" data-level="11.1" data-path="lm.html"><a href="lm.html#simple-linear-regression"><i class="fa fa-check"></i><b>11.1</b> Simple Linear Regression</a><ul>
<li class="chapter" data-level="11.1.1" data-path="lm.html"><a href="lm.html#parameter-estimation"><i class="fa fa-check"></i><b>11.1.1</b> Parameter Estimation</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="lm.html"><a href="lm.html#multiple-linear-regression"><i class="fa fa-check"></i><b>11.2</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="11.2.1" data-path="lm.html"><a href="lm.html#moderation"><i class="fa fa-check"></i><b>11.2.1</b> Moderation</a></li>
<li class="chapter" data-level="11.2.2" data-path="lm.html"><a href="lm.html#mediation"><i class="fa fa-check"></i><b>11.2.2</b> Mediation</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="lm.html"><a href="lm.html#polynomial-regression"><i class="fa fa-check"></i><b>11.3</b> Polynomial Regression</a></li>
<li class="chapter" data-level="11.4" data-path="lm.html"><a href="lm.html#hierarchical-models"><i class="fa fa-check"></i><b>11.4</b> Hierarchical Models</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>12</b> Generalized Linear Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="glm.html"><a href="glm.html#logistic-regression"><i class="fa fa-check"></i><b>12.1</b> Logistic Regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="glm.html"><a href="glm.html#binomial-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> Binomial Logistic Regression</a></li>
<li class="chapter" data-level="12.1.2" data-path="glm.html"><a href="glm.html#multinomial-logistic-regression"><i class="fa fa-check"></i><b>12.1.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="12.1.3" data-path="glm.html"><a href="glm.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>12.1.3</b> Ordinal Logistic Regression</a></li>
<li class="chapter" data-level="12.1.4" data-path="glm.html"><a href="glm.html#proportional-odds-logistic-regression"><i class="fa fa-check"></i><b>12.1.4</b> Proportional Odds Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="glm.html"><a href="glm.html#poisson-regression"><i class="fa fa-check"></i><b>12.2</b> Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="surv-anal.html"><a href="surv-anal.html"><i class="fa fa-check"></i><b>13</b> Survival Analysis</a></li>
<li class="chapter" data-level="14" data-path="pred-mod.html"><a href="pred-mod.html"><i class="fa fa-check"></i><b>14</b> Predictive Models</a><ul>
<li class="chapter" data-level="14.1" data-path="pred-mod.html"><a href="pred-mod.html#bias-variance-trade-off"><i class="fa fa-check"></i><b>14.1</b> Bias-Variance Trade-Off</a></li>
<li class="chapter" data-level="14.2" data-path="pred-mod.html"><a href="pred-mod.html#cross-validation"><i class="fa fa-check"></i><b>14.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="14.3" data-path="pred-mod.html"><a href="pred-mod.html#balancing-classes"><i class="fa fa-check"></i><b>14.3</b> Balancing Classes</a></li>
<li class="chapter" data-level="14.4" data-path="pred-mod.html"><a href="pred-mod.html#model-performance"><i class="fa fa-check"></i><b>14.4</b> Model Performance</a></li>
<li class="chapter" data-level="14.5" data-path="pred-mod.html"><a href="pred-mod.html#automated-machine-learning-automl"><i class="fa fa-check"></i><b>14.5</b> Automated Machine Learning (AutoML)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="unsup-lrn.html"><a href="unsup-lrn.html"><i class="fa fa-check"></i><b>15</b> Unsupervised Learning</a><ul>
<li class="chapter" data-level="15.1" data-path="unsup-lrn.html"><a href="unsup-lrn.html#factor-analysis"><i class="fa fa-check"></i><b>15.1</b> Factor Analysis</a></li>
<li class="chapter" data-level="15.2" data-path="unsup-lrn.html"><a href="unsup-lrn.html#clustering"><i class="fa fa-check"></i><b>15.2</b> Clustering</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="net-anal.html"><a href="net-anal.html"><i class="fa fa-check"></i><b>16</b> Network Analysis</a></li>
<li class="chapter" data-level="17" data-path="data-viz.html"><a href="data-viz.html"><i class="fa fa-check"></i><b>17</b> Data Visualization</a></li>
<li class="chapter" data-level="18" data-path="storytelling.html"><a href="storytelling.html"><i class="fa fa-check"></i><b>18</b> Data Storytelling</a></li>
<li class="chapter" data-level="19" data-path="bibli.html"><a href="bibli.html"><i class="fa fa-check"></i><b>19</b> Bibliography</a></li>
<li class="chapter" data-level="20" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>20</b> Appendix</a><ul>
<li class="chapter" data-level="20.1" data-path="appendix.html"><a href="appendix.html#solutions"><i class="fa fa-check"></i><b>20.1</b> Exercise Solutions</a><ul>
<li class="chapter" data-level="20.1.1" data-path="appendix.html"><a href="appendix.html#measurement-sampling"><i class="fa fa-check"></i><b>20.1.1</b> Measurement &amp; Sampling</a></li>
<li class="chapter" data-level="20.1.2" data-path="appendix.html"><a href="appendix.html#univariate-bivariate-analysis"><i class="fa fa-check"></i><b>20.1.2</b> Univariate &amp; Bivariate Analysis</a></li>
<li class="chapter" data-level="20.1.3" data-path="appendix.html"><a href="appendix.html#inferential-statistics"><i class="fa fa-check"></i><b>20.1.3</b> Inferential Statistics</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="appendix.html"><a href="appendix.html#d-framework-4d-chklst"><i class="fa fa-check"></i><b>20.2</b> 4D Framework {#4d-chklst}</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Guide through the People Analytics Lifecycle</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="uni-bi-stats" class="section level1">
<h1><span class="header-section-number">7</span> Univariate &amp; Bivariate Analysis</h1>
<p>This chapter reviews essential univariate and bivariate analysis concepts that underpin the more complex multivariate approaches in subsequent chapters of this book.</p>
<div id="univariate-analysis" class="section level2">
<h2><span class="header-section-number">7.1</span> Univariate Analysis</h2>
<p><strong>Descriptive statistics</strong> are rudimentary analysis techniques that help describe and summarize data in a meaningful way. Descriptive statistics do not allow us to draw any conclusions beyond the available data but are helpful in interpreting the data at hand.</p>
<p>There are two categories of descriptive statistics: (a) <strong>measures of central tendency</strong> describe the central position in a set of data; and (b) <strong>measures of spread</strong> describe how dispersed the data are.</p>
<div id="measures-of-central-tendency" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Measures of Central Tendency</h3>
<p><strong>Mean</strong></p>
<p>Perhaps the most intuitive measure of central tendency is the <strong>mean</strong>, which is often referred to as the average. The mean of a sample is denoted by <span class="math inline">\(\bar{x}\)</span> and is defined by:</p>
<p><span class="math display">\[ \bar{x} = \frac{\displaystyle\sum_{i=1}^{n} x_{i}}{n} \]</span></p>
<p>The population mean is denoted by <span class="math inline">\(\mu\)</span> and is defined by:</p>
<p><span class="math display">\[ \mu = \frac{\displaystyle\sum_{i=1}^{n} x_{i}}{N} \]</span></p>
<p>The mean of a set of numeric values can be calculated using the mean() function in R:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="co"># Fill vector x with integers</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">50</span>)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3"></a>
<a class="sourceLine" id="cb11-4" data-line-number="4"><span class="co"># Calculate average of vector x</span></a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] 6.9</code></pre>
<p><strong>Median</strong></p>
<p>The <strong>median</strong> represents the midpoint in a sorted vector of numbers. For vectors with an even number of values, the median is the average of the middle two numbers; it is simply the middle number for vectors with an odd number of values. When the distribution of data is skewed, or there is an extreme value like we observe in vector x, the median is a better measure of central tendency.</p>
<p>The median() function in R can be used to handle the sorting and midpoint selection:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="co"># Calculate median of vector x</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw">median</span>(x)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>In this example, the median is only 2 while the mean is 6.9 (which is not representative of any of the values in vector <span class="math inline">\(x\)</span>). Large deltas between mean and median values are evidence of outliers.</p>
<p><strong>Mode</strong></p>
<p>The <strong>mode</strong> is the most frequent number in a set of values.</p>
<p>While mean() and median() are standard functions in R, mode() returns the internal storage mode of the object rather than the statistical mode of the data. We can easily create a function to return the statistical mode(s):</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="co"># Create function to calculate statistical mode(s)</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2">stat.mode &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb15-3" data-line-number="3">  ux &lt;-<span class="st"> </span><span class="kw">unique</span>(x)</a>
<a class="sourceLine" id="cb15-4" data-line-number="4">  tab &lt;-<span class="st"> </span><span class="kw">tabulate</span>(<span class="kw">match</span>(x, ux))</a>
<a class="sourceLine" id="cb15-5" data-line-number="5">  ux[tab <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(tab)]</a>
<a class="sourceLine" id="cb15-6" data-line-number="6">}</a>
<a class="sourceLine" id="cb15-7" data-line-number="7"></a>
<a class="sourceLine" id="cb15-8" data-line-number="8"><span class="co"># Return mode(s) of vector x</span></a>
<a class="sourceLine" id="cb15-9" data-line-number="9"><span class="kw">stat.mode</span>(x)</a></code></pre></div>
<pre><code>## [1] 1 2</code></pre>
<p>In this case, we have a bimodal distribution since both 1 and 2 occur most frequently.</p>
<p><strong>Range</strong></p>
<p>The <strong>range</strong> is the difference between the maximum and minimum values in a set of numbers.</p>
<p>The range() function in R returns the minimum and maximum numbers:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="co"># Return lowest and highest values of vector x</span></a>
<a class="sourceLine" id="cb17-2" data-line-number="2"><span class="kw">range</span>(x)</a></code></pre></div>
<pre><code>## [1]  1 50</code></pre>
<p>We can leverage the max() and min() functions to calculate the difference between these values:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="co"># Calculate range of vector x</span></a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw">max</span>(x, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(x, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## [1] 49</code></pre>
<p>In people analytics, there are many conventional descriptive metrics – largely counts, percentages, and ratios cut by time series (day, month, quarter, year) and categorical dimensions (department, job, location, tenure band). Here is a sample of common measures:</p>
<ul>
<li>Time to Fill: average days between job requisition posting and offer acceptance</li>
<li>Offer Acceptance Rate: percent of offers extended to candidates that are accepted</li>
<li>Pass-Through Rate: percent of candidates in a particular stage of the recruiting process who passed through to the next stage</li>
<li>Progress to Goal: percent of approved positions that have been filled</li>
<li>cNPS/eNPS: candidate and employee NPS (-100 to 100)</li>
<li>Headcount: counts and percent of workforce across worker types (employee, intern, contingent)</li>
<li>Diversity: counts and percent of workforce across gender, ethnicity, and generational cohorts</li>
<li>Positions: count and percent of open, committed, and filled seats</li>
<li>Hires: counts and rates</li>
<li>Career Moves: counts and rates</li>
<li>Turnover: counts and rates (usually terms / average headcount over the period)</li>
<li>Workforce Growth: net changes over time, accounting for hires, internal transfers, and exits</li>
<li>Span of Control: ratio of people leaders to individual contributors</li>
<li>Layers/Tiers: average and median number of layers removed from CEO</li>
<li>Engagement: average score or top-box favorability score</li>
</ul>
</div>
<div id="measures-of-spread" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Measures of Spread</h3>
<p><strong>Variance</strong></p>
<p><strong>Variance</strong> is a measure of variability in the data. Variance is calculated using the average of squared differences – or deviations – from the mean.</p>
<p>Variance of a population is defined by:</p>
<p><span class="math display">\[ \sigma^{2} = \frac{\displaystyle\sum_{i=1}^{n} (x_{i}-\mu)^{2}}{N} \]</span></p>
<p>Variance of a sample is defined by:</p>
<p><span class="math display">\[ s^{2} = \frac{\displaystyle\sum_{i=1}^{n} (x_{i}-\bar{x})^{2}}{n-1} \]</span></p>
<p>It is important to note that since differences are squared, the variance is always non-negative. In addition, we cannot compare these squared differences to the arithmetic mean since the units are different. For example, if we calculate the variance of annual compensation measured in USD, variance should be expressed as USD squared while the mean exists in the original USD unit of measurement.</p>
<p>In R, the sample variance can be calculated using the var() function:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="co"># Load library for data wrangling</span></a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb21-3" data-line-number="3"></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="co"># Read employee demographics data</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5">demographics &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/crstarbuck/peopleanalytics_lifecycle_book/master/data/files/employee_demographics.csv&quot;</span>)</a>
<a class="sourceLine" id="cb21-6" data-line-number="6"></a>
<a class="sourceLine" id="cb21-7" data-line-number="7"><span class="co"># Calculate sample variance for annual compensation</span></a>
<a class="sourceLine" id="cb21-8" data-line-number="8"><span class="kw">var</span>(demographics<span class="op">$</span>annual_comp)</a></code></pre></div>
<pre><code>## [1] 1876688425</code></pre>
<p>Sample statistics are the default in R. Since the population variance differs from the sample variance by a factor of <span class="math inline">\(s^2 * (\frac{n - 1}{n})\)</span>, it is simple to convert output from var() to the population variance:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="co"># Store number of observations</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2">n =<span class="st"> </span><span class="kw">length</span>(demographics<span class="op">$</span>annual_comp)</a>
<a class="sourceLine" id="cb23-3" data-line-number="3"></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="co"># Calculate population variance for annual compensation</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="kw">var</span>(demographics<span class="op">$</span>annual_comp) <span class="op">*</span><span class="st"> </span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>n</a></code></pre></div>
<pre><code>## [1] 1876303464</code></pre>
<p><strong>Standard Deviation</strong></p>
<p>The <strong>standard deviation</strong> is simply the square root of the variance.</p>
<p>The standard deviation of a population is defined by:</p>
<p><span class="math display">\[ \sigma = \sqrt{\frac{\displaystyle\sum_{i=1}^{n} (x_{i} - \mu)^{2}}{N}} \]</span></p>
<p>The standard deviation of a sample is defined by:</p>
<p><span class="math display">\[ s = \sqrt{\frac{\displaystyle\sum_{i=1}^{n} (x_{i} - \bar{x})^{2}}{n - 1}} \]</span></p>
<p>Since a squared value can be converted back to its original units by taking its square root, the standard deviation expresses variability around the mean in the variable’s original units.</p>
<p>In R, the sample standard deviation can be calculated using the sd() function:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="co"># Calculate sample standard deviation for annual compensation</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="kw">sd</span>(demographics<span class="op">$</span>annual_comp)</a></code></pre></div>
<pre><code>## [1] 43320.76</code></pre>
<p>Since the population standard deviation differs from the sample standard deviation by a factor of <span class="math inline">\(s * \sqrt \frac{n - 1}{n}\)</span>, it is simple to convert output from sd() to the population standard deviation:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="co"># Calculate population standard deviation for annual compensation</span></a>
<a class="sourceLine" id="cb27-2" data-line-number="2"><span class="kw">sd</span>(demographics<span class="op">$</span>annual_comp) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>((n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>n)</a></code></pre></div>
<pre><code>## [1] 43316.32</code></pre>
<p><strong>Quartiles</strong></p>
<p><strong>Quartiles</strong> are a staple of exploratory data analysis (EDA). A quartile is a type of quantile that partitions data into four equally sized parts after ordering the data. Note that each partition is equally sized with respect to the number of data points – not the range of values in each. Quartiles are also related to <strong>percentiles</strong>. For example, Q1 is the 25th percentile – the value at or below which 25% of values lie. Percentiles are likely more familiar than quartiles, as percentiles show up in the height and weight measurements of babies, performance on standardized tests like the SAT and GRE, among other things.</p>
<p>The <strong>Interquartile Range (IQR)</strong> represents the difference between Q3 and Q1 cut point values (the middle two quartiles). The IQR is sometimes used to detect extreme values in a distribution; values less than <span class="math inline">\(Q1 - 1.5 * IQR\)</span> or greater than <span class="math inline">\(Q3 + 1.5 * IQR\)</span> are generally considered outliers.</p>
<p>In R, the quantile() function returns the values that bookend each quartile:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="co"># Return quartiles for annual compensation</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw">quantile</span>(demographics<span class="op">$</span>annual_comp)</a></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
##  50016.0  87946.0 125522.0 163262.5 199968.0</code></pre>
<p>Based on this output, we know that 25% of people in our data earn annual compensation of 87,946 USD or less, 125,522 USD is the median annual compensation, and 75% of people earn annual compensation of 163,263 USD or less.</p>
<p><strong>Boxplots</strong> are a common way to visualize the distribution of data by categorical and ordinal factors. Boxplots are not usually found in presentations to stakeholders, since they are a bit more technical and often require explanation, but these are very useful to analysts for understanding data distributions during the EDA phase. In R, the <code>ggplot2</code> library has robust and flexible data visualization capabilities which we will leverage throughout this book. Let’s visualize the spread of annual compensation by education level and gender using the ggplot() function:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="co"># Load library for data viz</span></a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw">library</span>(ggplot2)</a></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.0.2</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="co"># Produce boxplots to visualize compensation distribution by education and gender</span></a>
<a class="sourceLine" id="cb33-2" data-line-number="2"><span class="kw">ggplot</span>(demographics, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.factor</span>(education), <span class="dt">y =</span> annual_comp, <span class="dt">color =</span> gender)) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Education&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Annual Compensation&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb33-4" data-line-number="4"><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb33-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Boxplots can be interpreted as follows:
* Horizontal lines represent median compensation values.
* The box in the middle of each distribution represents the IQR.
* The end of the line above the IQR represents the threshold for outliers in the upper range: <span class="math inline">\(Q3 + 1.5 * IQR\)</span>.
* The end of the line below the IQR represents the threshold for outliers in the lower range: <span class="math inline">\(Q1 - 1.5 * IQR\)</span>.
* Data points represent outliers: <span class="math inline">\(x &gt; Q3 + 1.5 * IQR\)</span> or <span class="math inline">\(x &lt; Q1 - 1.5 * IQR\)</span>.</p>
<p>We can also return a specific percentile value using the <code>probs</code> argument in the quantile() function. For example, if we want to know the 80th percentile annual compensation value, we can execute the following:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="co"># Return 80th percentile annual compensation value</span></a>
<a class="sourceLine" id="cb34-2" data-line-number="2"><span class="kw">quantile</span>(demographics<span class="op">$</span>annual_comp, <span class="dt">probs =</span> <span class="fl">.8</span>)</a></code></pre></div>
<pre><code>##      80% 
## 170196.4</code></pre>
<p>In addition, the summary() function returns several common descriptive statistics for an object:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="co"># Return common descriptives</span></a>
<a class="sourceLine" id="cb36-2" data-line-number="2"><span class="kw">summary</span>(demographics<span class="op">$</span>annual_comp)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   50016   87946  125522  125369  163262  199968</code></pre>
<p><strong>Skewness</strong></p>
<p><strong>Skewness</strong> is a measure of the horizontal distance between the mode and mean – a representation of symmetric distortion. In most practical settings, data are not normally distributed. That is, the data are skewed either positively (right-tailed distribution) or negatively (left-tailed distribution). The coefficient of skewness is one of many ways in which we can asertain the degree of skew in the data. The skewness of sample data is defined as:</p>
<p><span class="math display">\[ Sk = \frac{1}{n} \frac{\displaystyle\sum_{i=1}^{n} (x_i-\bar{x})^3}{s^3} \]</span></p>
<p>A positive skewness coefficient indicates positive skew, while a negative coefficient indicates negative skew. The order of descriptive statistics can also be leveraged to ascertain the direction of skew in the data:</p>
<ul>
<li>Positive skewness: mode &lt; median &lt; mean</li>
<li>Negative skewness: mode &gt; median &gt; mean</li>
<li>Symmetrical distribution: mode = median = mean</li>
</ul>
<p>Figure <a href="uni-bi-stats.html#fig:skewness">7.1</a> illustrates the placement of these descriptive statistics in each of the three types of distributions:</p>
<p><br /></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:skewness"></span>
<img src="graphics/skewness.png" alt="Skewness" width="100%" />
<p class="caption">
Figure 7.1: Skewness
</p>
</div>
<p><br /></p>
<p>The magnitude of skewness can be determined by measuring the distance between the mode and mean relative to the variable’s scale. Alternatively, we can simply evaluate this using the coefficient of skewness:</p>
<ul>
<li>If skewness is between -0.5 - 0.5, the data are symmetrical.</li>
<li>If skewness is between -0.5 and -1 or 0.5 and 1, the data are moderately skewed.</li>
<li>If skewness is &lt; -1 or &gt; 1, the data are highly skewed.</li>
</ul>
<p>Since there is not a base R function for skewness, we can leverage the moments library to calculate skewness:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="co"># Load library</span></a>
<a class="sourceLine" id="cb38-2" data-line-number="2"><span class="kw">library</span>(moments)</a>
<a class="sourceLine" id="cb38-3" data-line-number="3"></a>
<a class="sourceLine" id="cb38-4" data-line-number="4"><span class="co"># Calculate skewness for org tenure, rounded to three significant figures</span></a>
<a class="sourceLine" id="cb38-5" data-line-number="5"><span class="kw">round</span>(<span class="kw">skewness</span>(demographics<span class="op">$</span>org_tenure), <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 0.562</code></pre>
<p><strong>Statistical Moments</strong>, after which this library was named, play an important role in specifying the appropriate probability distribution for a set of data. Moments are a set of statistical parameters used to describe the characteristics of a distribution. Skewness is the third statistical moment in the set; hence the sum of cubed differences and cubic polynomial in the denominator of the formula above. The complete set of moments comprises: (1) expected value or mean, (2) variance and standard deviation, (3) skewness, and (4) kurtosis.</p>
<p>We can verify that the skewness() function from the moments library returns the expected value (per the aforementioned formula) by validating against a manual calculation:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="co"># Store components of skewness calculation</span></a>
<a class="sourceLine" id="cb40-2" data-line-number="2">n =<span class="st"> </span><span class="kw">length</span>(demographics<span class="op">$</span>org_tenure)</a>
<a class="sourceLine" id="cb40-3" data-line-number="3">x =<span class="st"> </span>demographics<span class="op">$</span>org_tenure</a>
<a class="sourceLine" id="cb40-4" data-line-number="4">x_bar =<span class="st"> </span><span class="kw">mean</span>(demographics<span class="op">$</span>org_tenure)</a>
<a class="sourceLine" id="cb40-5" data-line-number="5">s =<span class="st"> </span><span class="kw">sd</span>(demographics<span class="op">$</span>org_tenure)</a>
<a class="sourceLine" id="cb40-6" data-line-number="6"></a>
<a class="sourceLine" id="cb40-7" data-line-number="7"><span class="co"># Calculate skewness manually, rounded to three significant figures</span></a>
<a class="sourceLine" id="cb40-8" data-line-number="8"><span class="kw">round</span>(<span class="dv">1</span><span class="op">/</span>n <span class="op">*</span><span class="st"> </span>(<span class="kw">sum</span>((x <span class="op">-</span><span class="st"> </span>x_bar)<span class="op">^</span><span class="dv">3</span>) <span class="op">/</span><span class="st"> </span>s<span class="op">^</span><span class="dv">3</span>), <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 0.562</code></pre>
<p>A skewness coefficient of .562 indicates that organization tenure is moderately and positively skewed. We can visualize the data to confirm the expected right-tailed distribution:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="co"># Produce histogram to visualize sample distribution</span></a>
<a class="sourceLine" id="cb42-2" data-line-number="2"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-3" data-line-number="3"><span class="st">  </span><span class="kw">aes</span>(demographics<span class="op">$</span>org_tenure) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Organization Tenure&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb42-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..), <span class="dt">fill =</span> <span class="st">&quot;#414141&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb42-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">fill =</span> <span class="st">&quot;#ADD8E6&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb42-7" data-line-number="7"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:org-tenure-distribution"></span>
<img src="_main_files/figure-html/org-tenure-distribution-1.png" alt="Organization Tenure Distribution" width="672" />
<p class="caption">
Figure 7.2: Organization Tenure Distribution
</p>
</div>
<p><strong>Kurtosis</strong></p>
<p>While skewness provides information on the symmetry of a distribution, <strong>kurtosis</strong> provides information on the heaviness of a distribution’s tails (“tailedness”). Kurtosis is the fourth statistical moment, defined by:</p>
<p><span class="math display">\[ K = \frac{1}{n} \frac{\displaystyle\sum_{i=1}^{n} (x_i-\bar{x})^4}{s^4} \]</span></p>
<p>Note that the quartic functions characteristic of the fourth statistical moment are the only differences from the skewness formula we reviewed in the prior section (which featured cubic functions).</p>
<p>The terms <strong>leptokurtic</strong> and <strong>platykurtic</strong> are often used to describe distributions with light and heavy tails, respectively. “Platy-” in platykurtic is the same root as “platypus”, and I’ve found it helpful to recall the characteristics of the flat platypus when characterizing frequency distributions as platkurtic (wide and flat) vs. its antithesis, leptokurtic (tall and skinny). The normal (or Gaussian) distribution is referred to as a <strong>mesokurtic</strong> distribution in the context of kurtosis.</p>
<p>Figure <a href="uni-bi-stats.html#fig:kurtosis">7.3</a> illustrates the three kurtosis categorizations:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kurtosis"></span>
<img src="graphics/kurtosis.jpg" alt="Kurtosis" width="75%" />
<p class="caption">
Figure 7.3: Kurtosis
</p>
</div>
<p>Kurtosis is measured relative to a normal distribution. Normal distributions have a kurtosis coefficient of 3. Therefore, the kurtosis coefficient is greater than 3 for leptokurtic distributions and less than 3 for platykurtic distributions.</p>
<p>The moments library can also be used to calculate kurtosis in R:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1"><span class="co"># Calculate kurtosis for org tenure, rounded to two significant figures</span></a>
<a class="sourceLine" id="cb43-2" data-line-number="2"><span class="kw">round</span>(<span class="kw">kurtosis</span>(demographics<span class="op">$</span>org_tenure), <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 2.26</code></pre>
<p>We can verify that the kurtosis() function returns the expected value (per the aforementioned formula) by validating against a manual calculation:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1"><span class="co"># Calculate kurtosis manually, rounded to two significant figures</span></a>
<a class="sourceLine" id="cb45-2" data-line-number="2"><span class="kw">round</span>(<span class="dv">1</span><span class="op">/</span>n <span class="op">*</span><span class="st"> </span>(<span class="kw">sum</span>((x <span class="op">-</span><span class="st"> </span>x_bar)<span class="op">^</span><span class="dv">4</span>) <span class="op">/</span><span class="st"> </span>s<span class="op">^</span><span class="dv">4</span>), <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 2.26</code></pre>
<p>As we saw in Figure <a href="uni-bi-stats.html#fig:org-tenure-distribution">7.2</a>, there is a long right tail about the organization tenure distribution. However, due to the moderate skew, there is no left tail. Therefore, our kurtosis coefficient is &lt; 3 since the presence of the right tail is offset by the lack of a left tail. This is why it is important not to characterize a distribution based on a single isolated metric; we need the complete set of statistical moments to fully understand the distribution of data.</p>
</div>
</div>
<div id="bivariate-analysis" class="section level2">
<h2><span class="header-section-number">7.2</span> Bivariate Analysis</h2>
<div id="covariance" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Covariance</h3>
<p>While variance provides an understanding of how values for a single variable vary, <strong>covariance</strong> is an unstandardized measure of how two variables vary together. Values can range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>, and these values can be used to understand the direction of the linear relationship between variables. Positive covariance values indicate that the variables vary in the same direction (e.g., tend to increase or decrease together), while negative covariance values indicate that the variables vary in opposite directions (e.g., when one increases, the other decreases, or vice versa).</p>
<p>Covariance of a sample is defined by:</p>
<p><span class="math display">\[ cov_{x,y} = \frac{\displaystyle\sum_{i=1}^{n} (x_{i}-\bar{x})(y_{i}-\bar{y})}{n-1} \]</span></p>
<p>It’s important to note that while covariance aids our understanding of the direction of the relationship between two variables, we cannot use it to understand the strength of the association since it is unstandardized. Due to differences in variables’ units of measurement, the strength of the relationship between two variables with large covariance could be weak, while the strength of the relationship between another pair of variables with small covariance could be strong.</p>
<p>In R, we can compute the covariance between a pair of numeric variables by passing the two vectors into the cov() function:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="co"># Calculate sample covariance between annual compensation and age using complete observations (missing values will cause issues if not addressed)</span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="kw">cov</span>(demographics<span class="op">$</span>annual_comp, demographics<span class="op">$</span>age, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 453179.1</code></pre>
<p>In this example, using the default Pearson method, the covariance between annual compensation and age is 453179.1. The positive value indicates that annual compensation is generally higher for older employees and lower for younger employees.</p>
<p>Just as we multiplied the sample variance by <span class="math inline">\((n - 1) / n\)</span> to obtain the population variance, we can apply the same approach to convert the sample covariance returned by cov() to the population covariance:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="co"># Calculate population covariance between annual compensation and age</span></a>
<a class="sourceLine" id="cb49-2" data-line-number="2"><span class="kw">cov</span>(demographics<span class="op">$</span>annual_comp, demographics<span class="op">$</span>age, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>) <span class="op">*</span><span class="st"> </span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span>n</a></code></pre></div>
<pre><code>## [1] 453086.1</code></pre>
<p>The examples thus far have only examined associations between two variables at a time. However, rather than looking at isolated pairwise relationships, we can produce a covariance matrix to surface associations among many variables by passing a dataframe or matrix object into the cov() function:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1"><span class="co"># Generate a correlation matrix among continuous variables</span></a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw">cov</span>(demographics[, <span class="kw">c</span>(<span class="st">&quot;annual_comp&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;org_tenure&quot;</span>, <span class="st">&quot;job_tenure&quot;</span>)], <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>##              annual_comp          age   org_tenure  job_tenure
## annual_comp 1.876688e+09 453179.07281 138551.67644 61576.73603
## age         4.531791e+05    168.38661     41.56006    17.96902
## org_tenure  1.385517e+05     41.56006     26.03270    11.04572
## job_tenure  6.157674e+04     17.96902     11.04572    13.29996</code></pre>
<p>Using the default Pearson method, the cov() function will return sample variances for each variable down the diagonal, since covariance is not applicable in the context of a variable with itself. We can confirm by producing the variance for age:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="co"># Return sample variance for age</span></a>
<a class="sourceLine" id="cb53-2" data-line-number="2"><span class="kw">var</span>(demographics<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 168.3866</code></pre>
<p>As expected, the variance for age (<span class="math inline">\(s^{2} = 168.39\)</span>) matches the value found in the age x age cell of the covariance matrix.</p>
</div>
<div id="correlation" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Correlation</h3>
<p><strong>Correlation</strong> is a scaled form of covariance. While covariance provides an unstandardized measure of the direction of a relationship between variables, correlation provides a standardized measure that can be used to quantify both the direction and strength of bivariate relationships. Correlation coefficients range from -1 to 1, where -1 indicates a perfectly negative association, 1 indicates a perfectly positive association, and 0 indicates the absence of an association. <strong>Pearson’s product-moment correlation coefficient</strong> <span class="math inline">\(r\)</span> is defined by:</p>
<p><span class="math display">\[ r_{x,y} = \frac{\displaystyle\sum_{i=1}^{n} (x_{i}-\bar{x})(y_{i}-\bar{y})}{\sqrt{\displaystyle\sum_{i=1}^{n} (x_{i}-\bar{x})^2 \displaystyle\sum_{i=1}^{n} (y_{i}-\bar{y})^2}} \]</span></p>
<p>In R, Pearson’s <span class="math inline">\(r\)</span> can be calculated using the cor() function:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1"><span class="co"># Calculate the correlation between annual compensation and age</span></a>
<a class="sourceLine" id="cb55-2" data-line-number="2"><span class="kw">cor</span>(demographics<span class="op">$</span>annual_comp, demographics<span class="op">$</span>age, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 0.8061577</code></pre>
<p>While we already know that the relationship between annual compensation and age is positive based on the positive covariance coefficient, Pearson’s <span class="math inline">\(r\)</span> of .81 indicates that the strength of the positive association is strong (<span class="math inline">\(r\)</span> = 1 is perfectly positive). Though there are no absolute rules for categorizing the strength of relationships, as thresholds often vary by domain, the following is a general rule of thumb for interpreting the strength of bivariate associations:</p>
<ul>
<li>Weak = Absolute value of correlation coefficients between 0 and .3</li>
<li>Moderate = Absolute value of correlation coefficients between .4 and .6</li>
<li>Strong = Absolute value of correlation coefficients between .7 and 1</li>
</ul>
<p>There are several correlation coefficients, and the measurement scale of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> determine the appropriate type:</p>
<p><br /></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:corr-table"></span>
<img src="graphics/correlation_table.png" alt="Proper Applications of Correlation Coefficients" width="75%" />
<p class="caption">
Figure 7.4: Proper Applications of Correlation Coefficients
</p>
</div>
<p><br /></p>
<p>Pearson’s <span class="math inline">\(r\)</span> can be used when both variables are measured on continuous scales or when one is continuous and the other is dichotomous (point-biserial correlation).</p>
<p>When one or both variables are ordinal, we can leverage <strong>Spearman’s</strong> <span class="math inline">\(\rho\)</span> or <strong>Kendall’s</strong> <span class="math inline">\(\tau\)</span>, which are both standardized nonparametric measures of the association between one or two rank-ordered variables. Let’s look at Spearman’s <span class="math inline">\(\rho\)</span>, which is defined as:</p>
<p><span class="math display">\[ \rho = 1 - {\frac {6 \sum d_i^2}{n(n^2 - 1)}} \]</span></p>
<p>We can override the default Pearson method in the cor() function to implement a specific form of rank correlation using the <code>method</code> argument:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1"><span class="co"># Calculate the correlation between job level and education level using Spearman&#39;s method</span></a>
<a class="sourceLine" id="cb57-2" data-line-number="2"><span class="kw">cor</span>(demographics<span class="op">$</span>job_level, demographics<span class="op">$</span>education, <span class="dt">method =</span> <span class="st">&quot;spearman&quot;</span>, <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 0.6749776</code></pre>
<p>The <span class="math inline">\(\rho\)</span> coefficient of .67 indicates that the positive association we observed between job level and education level is moderate-to-strong. We could also pass <code>method = &quot;kendall&quot;</code> to this cor() function to implement Kendall’s <span class="math inline">\(\tau\)</span>.</p>
<p>The <strong>Phi Coefficient</strong> (<span class="math inline">\(\phi\)</span>), sometimes referred to as the mean square contingency coefficient or Matthews correlation in ML, can be used to understand the association between two dichotomous variables. For a 2x2 table for two random variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:phi-tbl"></span>
<img src="graphics/phi_coefficient_formula.png" alt="2x2 Table for Random Variables x and y" width="50%" />
<p class="caption">
Figure 7.5: 2x2 Table for Random Variables x and y
</p>
</div>
<p>The <span class="math inline">\(\phi\)</span> coefficient is defined as:</p>
<p><span class="math display">\[ \phi = {\frac {(AD-BC)}{\sqrt{(A+B)(C+D)(A+C)(B+D)}}} \]</span></p>
<p>To illustrate, let’s examine whether there is a relationship between gender and performance after transforming performance from its ordinal form to a dichotomous variable (high vs. low performance). We can leverage the <code>psych</code> library to calculate <span class="math inline">\(\phi\)</span> in R:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1"><span class="co"># Load library for Phi Coefficient</span></a>
<a class="sourceLine" id="cb59-2" data-line-number="2"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb59-3" data-line-number="3"></a>
<a class="sourceLine" id="cb59-4" data-line-number="4"><span class="co"># Set females to 1 and everything else to 0</span></a>
<a class="sourceLine" id="cb59-5" data-line-number="5">demographics<span class="op">$</span>gender_code &lt;-<span class="st"> </span><span class="kw">ifelse</span>(demographics<span class="op">$</span>gender <span class="op">==</span><span class="st"> &#39;Female&#39;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb59-6" data-line-number="6"></a>
<a class="sourceLine" id="cb59-7" data-line-number="7"><span class="co"># Set high performers (3 and above) to 1 and everything else to 0</span></a>
<a class="sourceLine" id="cb59-8" data-line-number="8">demographics<span class="op">$</span>performance_code &lt;-<span class="st"> </span><span class="kw">ifelse</span>(demographics<span class="op">$</span>performance <span class="op">&lt;</span><span class="st"> </span><span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb59-9" data-line-number="9"></a>
<a class="sourceLine" id="cb59-10" data-line-number="10"><span class="co"># Create a 2x2 contingency table</span></a>
<a class="sourceLine" id="cb59-11" data-line-number="11">contingency_tbl &lt;-<span class="st"> </span><span class="kw">table</span>(demographics<span class="op">$</span>gender_code, demographics<span class="op">$</span>performance_code)</a>
<a class="sourceLine" id="cb59-12" data-line-number="12"></a>
<a class="sourceLine" id="cb59-13" data-line-number="13"><span class="co"># Calculate the Phi Coefficient between dichotomous variables</span></a>
<a class="sourceLine" id="cb59-14" data-line-number="14"><span class="kw">phi</span>(contingency_tbl)</a></code></pre></div>
<pre><code>## [1] 0.01</code></pre>
<p><span class="math inline">\(\phi\)</span> is essentially 0, which means performance ratings are distributed equitably across gender categories (good news!).</p>
<p>A correlation matrix can be produced to surface associations among many variables by passing a dataframe or matrix object into the cor() function:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1"><span class="co"># Generate a correlation matrix among continuous variables</span></a>
<a class="sourceLine" id="cb61-2" data-line-number="2"><span class="kw">cor</span>(demographics[, <span class="kw">c</span>(<span class="st">&quot;annual_comp&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;org_tenure&quot;</span>, <span class="st">&quot;job_tenure&quot;</span>)], <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a></code></pre></div>
<pre><code>##             annual_comp       age org_tenure job_tenure
## annual_comp   1.0000000 0.8061577  0.6268392  0.3897584
## age           0.8061577 1.0000000  0.6277154  0.3797042
## org_tenure    0.6268392 0.6277154  1.0000000  0.5936211
## job_tenure    0.3897584 0.3797042  0.5936211  1.0000000</code></pre>
<p>Based on this correlation matrix, there are several moderate and strong pairwise associations in the data. The values down the diagonal are 1 because these represent the correlation between each variable and itself. You may also notice that the information above and below the diagonal is identical and, therefore, redundant.</p>
<p>A great R library for visualizing correlation matrices is corrplot. Several arguments can be specified for various visual representations of the relationships among variables:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1"><span class="co"># Load library for correlation visuals</span></a>
<a class="sourceLine" id="cb63-2" data-line-number="2"><span class="kw">library</span>(corrplot)</a>
<a class="sourceLine" id="cb63-3" data-line-number="3"></a>
<a class="sourceLine" id="cb63-4" data-line-number="4"><span class="co"># Store correlation matrix to object M</span></a>
<a class="sourceLine" id="cb63-5" data-line-number="5">M &lt;-<span class="st"> </span><span class="kw">cor</span>(demographics[, <span class="kw">c</span>(<span class="st">&quot;annual_comp&quot;</span>, <span class="st">&quot;age&quot;</span>, <span class="st">&quot;org_tenure&quot;</span>, <span class="st">&quot;job_tenure&quot;</span>)], <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</a>
<a class="sourceLine" id="cb63-6" data-line-number="6"></a>
<a class="sourceLine" id="cb63-7" data-line-number="7"><span class="co"># Visualize correlation matrix</span></a>
<a class="sourceLine" id="cb63-8" data-line-number="8"><span class="kw">corrplot.mixed</span>(M, <span class="dt">order =</span> <span class="st">&#39;AOE&#39;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>It’s important to remember that correlation is not causation. Correlations can be spurious (variables related by chance), and drawing conclusions based on bivariate associations alone – especially in the absence of sound theoretical underpinnings – can be dangerous. Here are two examples of nearly perfect correlations between variables for which there is likely no true direct association:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:spur-corr-1"></span>
<img src="graphics/spurious_corr_maine_divorce.png" alt="Correlation between Maine Divorce Rate and Margarine Consumption (r = .99)" width="100%" />
<p class="caption">
Figure 7.6: Correlation between Maine Divorce Rate and Margarine Consumption (r = .99)
</p>
</div>
<p><br /></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:spur-corr-2"></span>
<img src="graphics/spurious_corr_mozzarella_cheese.png" alt="Correlation between Mozzarella Cheese Consumption and Civil Engineering Doctorate Conferrals (r = .96)" width="100%" />
<p class="caption">
Figure 7.7: Correlation between Mozzarella Cheese Consumption and Civil Engineering Doctorate Conferrals (r = .96)
</p>
</div>
<p>In addition, covariance and correlation alone are not sufficient for determining whether an observed association in sample data is also present in the population. To understand the likelihood that patterns observed in sample data are also present in the larger population of interest, we need to move beyond descriptive measures.</p>
</div>
</div>
<div id="exercises-1" class="section level2">
<h2><span class="header-section-number">7.3</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>Which of the following measures of central tendency is least sensitive to extreme values (outliers)?
<br />A. Median
<br />B. Mean
<br />C. Range</p></li>
<li><p>The standard deviation represents the ‘average’ amount by which <span class="math inline">\(x\)</span> values deviate (or vary) from the mean. A large standard deviation indicates there is considerable spread in the data, whereas a small standard deviation indicates the mean is fairly representative of the data.
<br />A. True
<br />B. False</p></li>
<li><p>A positively skewed distribution has its largest allocation to the left and a negative distribution to the right.
<br />A. True
<br />B. False</p></li>
<li><p>Large covariance coefficients always indicate strong bivariate associations.
<br />A. True
<br />B. False</p></li>
<li><p>Which of the following can be found in boxplots?
<br />A. Quartiles
<br />B. Median
<br />C. Mean
<br />D. IQR
<br />E. Outliers</p></li>
<li><p>The 3rd quartile (Q3) is equivalent to the 75th percentile.
<br />A. True
<br />B. False</p></li>
<li><p>Which of the following correlation coefficients can be used when evaluating the relationship between a pair of rank-ordered variables?
<br />A. Pearson’s Product Moment
<br />B. Spearman’s Rank
<br />C. Phi
<br />D. Point-Biserial
<br />E. Kendall’s Rank</p></li>
<li><p>Which of the following correlation coefficients can be used when evaluating the relationship between a pair of dichotomous variables?
<br />A. Pearson’s Product Moment
<br />B. Spearman’s Rank
<br />C. Phi
<br />D. Point-Biserial
<br />E. Kendall’s Rank</p></li>
<li><p>Platykurtic distributions are flat relative to mesokurtic distributions.
<br />A. True
<br />B. False</p></li>
<li><p>When using the Pearson method, values down the diagonal of a covariance matrix represent each variable’s variance.
<br />A. True
<br />B. False</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="measure-sampl.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inf-stats.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/r/05_univariate_bivariate_analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
