# Supervised Learning Models

It's important to begin this chapter by drawing a distinction between explanatory and predictive models. Explanatory models are highly interpretable and their utility is largely in understanding the nature and magnitude of the effect variables have on outcomes. Explanatory models also lend to quantifying the extent to which we can generalize the observed effects to the larger population from which the sample was drawn. The objective in predictive modeling is to also to learn from patterns in historical data but for the purpose of achieving the most accurate predictions of future events -- even at the expense of interpretability. To be clear, this isn't to say that predictive models cannot be interpreted -- they certainly can -- but I've seen relatively few applications for predictive modeling in people analytics because models generally need to be highly interpretable to support action planning. Therefore, the majority of this chapter will be devoted to explanatory models to support a working understanding of how to interpret model output and communicate clear, data-driven narratives that respect the nuance and noise characteristic of people data.

## Regression

Regression is perhaps the most important statistical learning technique for people analytics. If you have taken a statistics course at the undergraduate or graduate levels, you have surely already encountered it. Before diving into the math to understand the mechanics of regression, let's develop an intuitive understanding.

Imagine we are sitting at a large public park in NYC on a nice fall afternoon. If asked to estimate the annual compensation of the next person to walk by, in the absence of any additional information what would be the process by which you arrive at an answer? Most estimate the average annual compensation of everyone capable of walking by -- including residents and tourists -- which is of course a very large group of people! The obvious limitation with this approach is that among the large group of people capable of walking by, there is likely significant variability in annual compensation. Many walking by may be children, unemployed, or retirees who earn no annual compensation while others may be highly compensated senior executives at elite NYC firms. Since the range of annual compensation could be zero to billions of dollars, the average of such a large population is likely going to be highly inaccurate without more information on who may walk by.

Let's consider that we are sitting outside on a weekday afternoon. Should this influence our annual compensation estimate? It is likely that we can eliminate a large segment of those likely to walk by, as most children would be in school on a fall weekday afternoon. It's also unlikely that those who are employed and not on vacation will walk by on a fall weekday afternoon. Therefore, factoring in that it is a weekday will limit the population for which we estimate the average annual compensation, and this may reduce the amount of error in our estimate.

Let's now consider that the park is closed to invited guests for a symposium on people analytics. This information significantly reduces the population for which we estimate average annual compensation, which should in turn reduce the amount of error in our estimate. 

Furthermore, if we learn that the next person to walk by will be wearing a blue shirt, does this influence your estimate? Unless there is research to suggest shirt color and earnings are related, this information will likely not contribute any significant information to the model and should, therefore, not be considered.

You can probably think of many relevant variables that would help reduce the size of the population to achieve less variability around the average annual compensation estimates. These may include job, level, years of experience, education, location, among other factors. The main thing to understand is that for each group of observations with the same characteristics -- such as senior analysts with a graduate degree who reside in NYC -- there is a distribution of annual compensation. The goal is to limit the variability around the average for each group so that estimating the average value will generally be an accurate estimate for those in the larger population with the same characteristics. In our example, if we did not have access to information that helps us explain why people vary in the amount of annual compensation they earn, it would not be appropriate to estimate compensation with the average value since this is unlikely to be similar to the compensation most in the population earn. While we can generally improve our estimates with more relevant information (not shirt color in this case), it is important to understand that samples which are too small (n < 30) lend to anomalies; modeling noise in sparse data can result in models that are unlikely to generalize beyond the sample data (a phenomenon known as overfitting that will be covered later in this chapter).

## Simple Linear Regression




## Multiple Linear Regression



### Moderation



### Mediation



## Non-Linear Regression




## Logistic Regression




## Hierarchical Models


# Automated Machine Learning (AutoML)

