# Data Visualization {#data-viz}

## Design Guidelines

## Visualization Types


```{r, message = FALSE, warning = FALSE}

# Load library
library(dplyr)

# Load employee data
data <- read.csv("/Users/craig.starbuck/Library/Mobile Documents/com~apple~CloudDocs/Documents/People Analytics Book/GitHub/peopleanalytics_lifecycle_book/data/turnover_trends.csv")

```

### Tables


### Heatmaps


### Scatterplots


### Line Graphs

  **Single Series**

```{r single-line-graph, out.width = "100%", echo = FALSE, fig.cap = 'Single series line graph.', fig.align = 'center', message = FALSE, warning = FALSE}

library(ggplot2)

ggplot2::ggplot(subset(data, year == 3 & job == 'People Scientist' & level == 4 & remote == 'Yes'), aes(x = month, y = turnover_rate * .01)) + 
ggplot2::labs(title = "Trailing 12-Month (TTM) turnover for level 4 People Scientists \nhas trended up over the past year.", x = 'Month', y = 'Turnover Rate') + 
ggplot2::geom_line(col = "#0080FF", size = 1.5) +
ggplot2::scale_x_continuous(breaks = 1:12) +
ggplot2::scale_y_continuous(labels = scales::percent) +
ggplot2::theme(panel.background = element_blank(),
               axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(),
               plot.title = element_text(colour = "#404040"),
               axis.title.x = element_text(colour = "#404040"),
               axis.title.y = element_text(colour = "#404040"))


```
  
  **Two Series**
  
  **Multiple Series**
  
### Slopegraphs

### Bar Charts

  **Vertical**
  
  **Horizontal**
  
  **Stacked**
  
### Waterfall Charts


### Area Charts


### Pie Charts


## Review Questions



  
