# Data Visualization {#data-viz}

## Design Guidelines

## Visualization Types


```{r, message = FALSE, warning = FALSE}

# Load library
library(dplyr)

# Load employee data
data <- read.csv("https://raw.githubusercontent.com/crstarbuck/peopleanalytics_book/master/data/turnover_trends.csv")

```

### Tables


### Heatmaps


### Scatterplots


### Line Graphs

  **Single Series**

```{r single-line-graph, out.width = "100%", echo = FALSE, fig.cap = 'Single series line graph.', fig.align = 'center', message = FALSE, warning = FALSE}

library(ggplot2)

# Subset data
sl_data <- subset(data, year == 5 & job == 'People Scientist' & level == 4 & remote == 'Yes')

# Visualize data
ggplot2::ggplot(sl_data, aes(x = month, y = turnover_rate * .01)) + 
ggplot2::labs(title = "The trailing 12-month (TTM) turnover for level 4 People Scientists \nhas trended up over the past year.", x = 'Month', y = 'Turnover Rate') + 
ggplot2::geom_line(col = "#0080FF", size = 1.5) +
ggplot2::scale_x_continuous(breaks = 1:12) +
ggplot2::scale_y_continuous(labels = scales::percent) +
ggplot2::theme(panel.background = element_blank(),
               axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(),
               plot.title = element_text(colour = "#404040"),
               axis.title.x = element_text(colour = "#404040"),
               axis.title.y = element_text(colour = "#404040"))


```
  
  **Two Series**
  
```{r double-line-graph, out.width = "100%", echo = FALSE, fig.cap = 'Two series line graph.', fig.align = 'center', message = FALSE, warning = FALSE}

# Subset data
tl_data <- subset(data, year == 5 & job %in% c('People Scientist', 'Data Engineer') & level == 4 & remote == 'Yes')

# Ordered factor for consistent legend value sorting
tl_data$job <- factor(tl_data$job, levels = c("People Scientist", "Data Engineer"))

# Visualize data
ggplot2::ggplot(tl_data, aes(x = month, y = turnover_rate * .01, colour = job)) + 
ggplot2::labs(title = "The trailing 12-month (TTM) turnover trends for level 4 People Scientists \nand Data Engineers diverged over the past year.", x = 'Month', y = 'Turnover Rate') + 
ggplot2::geom_line(size = 1.5) +
ggplot2::scale_color_manual(values = c("#0080FF", "#B8BDBF")) +
ggplot2::scale_x_continuous(breaks = 1:12) +
ggplot2::scale_y_continuous(labels = scales::percent) +
ggplot2::theme(panel.background = element_blank(),
               axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(),
               plot.title = element_text(colour = "#404040"),
               axis.title.x = element_text(colour = "#404040"),
               axis.title.y = element_text(colour = "#404040"))


```
  
  **Multiple Series**
  
```{r multi-line-graph, out.width = "100%", echo = FALSE, fig.cap = 'Multiple series line graph.', fig.align = 'center', message = FALSE, warning = FALSE}

# Subset data
ml_data <- subset(data, year == 5 & job %in% c('People Scientist', 'Data Engineer', 'Insights Consultant') & level == 4 & remote == 'Yes')

# Ordered factor for consistent legend value sorting
ml_data$job <- factor(ml_data$job, levels = c("People Scientist", "Data Engineer", "Insights Consultant"))

# Visualize data
ggplot2::ggplot(ml_data, aes(x = month, y = turnover_rate * .01, colour = job)) + 
ggplot2::labs(title = "The trailing 12-month (TTM) turnover trend for level 4 People Scientists \ndiverged from Data Engineers and Insights Consultants over the past year.", x = 'Month', y = 'Turnover Rate') + 
ggplot2::geom_line(size = 1.5) +
ggplot2::scale_color_manual(values=c("#0080FF", "#B8BDBF", "#E2E5E5")) +
ggplot2::scale_x_continuous(breaks = 1:12) +
ggplot2::scale_y_continuous(labels = scales::percent) +
ggplot2::theme(panel.background = element_blank(),
               axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(),
               plot.title = element_text(colour = "#404040"),
               axis.title.x = element_text(colour = "#404040"),
               axis.title.y = element_text(colour = "#404040"))

```
  
### Slopegraphs

### Bar Charts

  **Vertical**
  
  **Horizontal**
  
  **Stacked**
  
### Waterfall Charts


### Area Charts


### Pie Charts


## Deceptive Visuals



## Review Questions

1. 

2. 

3. 

4. 

5. 

6. 

7. 

8. 

9. 

10. 


  
