# Data Storytelling {#storytelling}

  This chapter leans more *art* than *science* and covers strategies to translate results of analyses into compelling stories that have a high probability of landing effectively with target audiences. One may build an impressive set of complex models and perform robust analyses but unless the results and recommendations are clear to stakeholders, this but an exercise in futility. We need stories to distill analytical output down to a non-technical and logical organization of the most salient points and recommendations.
  
## Define Success

  There is perhaps no more important initial question to ask than: "What does a successful outcome look like?" If we cannot clearly articulate the answer to this question, the audience is also likely to be unclear about what we are asking them to do in response to the information we present. All content and messages should support what we want our audience to know or do; therefore, defining what success looks like is a prerequisite for outlining and structuring the presentation.

## Know Your Audience

  A unique challenge for People Analytics practitioners is that the audience is often non-technical folks in the People organization. The strategies needed to communicate effectively to this audience are quite different from those required to present an analysis to Finance, for example. Using technical jargon is a sure way to quickly lose a non-technical audience and sacrifice what could otherwise be a poignant and impactful call to action. Therefore, it is critically important to identify and understand the target audience before beginning to package and deliver results.
  
  Several contextual questions are important to consider in order to respect the unique dynamics influencing success:
  
  1. What essential background information does the audience already have, and what additional context needs to be shared?
  2. Does the audience already have access to any relevant data that would strengthen or hamstring the messages we need to convey?
  3. Does the audience or decision maker have a known perspective on the topic?
  4. How should the content be messaged to proactively appeal to potential risks or biases the audience may possess that could create resistance to the findings and/or recommendations?
  5. What is the audience's preferred format for sharing content (e.g., document vs. deck)?

## Elements of Good Stories

  Good stories share several essential elements, including characters, setting, plot, conflict, and resolution.
  
  Exposition

### Intro

  Studies show that our audience determines in 3-8 seconds whether or not to give us their attention based on what we have put in front of them (Knaflic, 2015). Therefore, it is crucial to let the audience know upfront what we are going to share with them and why it is worth their time and attention.
  
### Climax



### Conclusion



## Craft the Story

  Entrepreneurs pitching to VCs craft a concise *elevator pitch* that highlights the key features of their product or service complemented by data to support the unique value proposition and attractive upside of the business (e.g., market size and penetration, revenue growth trajectory). In the same way, a good early step in storytelling with data is drafting a short story and iterating on it until only the essential content remains and it requires no more than three minutes to read.

  Given the significant time required to wrangle, model, and analyze data, it is often tempting to include details associated with every aspect of an analytics project. However, such details will likely detract from the key messages we wish to convey. Including in the Appendix of a document or deck information that is superfluous to the main points ensures the details are available should they be needed in addressing the audience's questions whilst ensuring the audience is focused only on the material elements of the presentation.
  
  When preparing a presentation, never begin with slides. The aesthetics and effects are of secondary importance to the organization and sequencing of content. Begin by outlining the structure and organizing content and key messages in a way that supports and punctuates the key messages you wish to convey to the audience. The outline can then be translated into a presentation-ready deck or document, which will have a higher likelihood of logical and effective information flow.

## TL;DR

## Versioning

  Prior to final versions of documents or decks being circulated to the target audience, there are generally several revs to refine the content and storyline in partnership with various stakeholders. For this reason, it is important to define a versioning taxonomy to clarify when the content is production-ready.
  
  1. **Draft**: Working document/deck being prepared by the analytics team
  2. **Initial Review**: Document/deck suitable for initial input from stakeholders
  3. **Final Review**: Document/deck reflects feedback from initial review and ready for final review and sign off
  4. **Complete**: Document/deck complete and ready for delivery to target audience

## Telling the Story



## Reference Material



## Review Questions

1. 