# Appendix {#appendix}

  This appendix provides the code needed to reproduce visuals in Chapter \@ref(data-viz).

## Step-by-Step Visual Upgrade

```{r, eval = FALSE}

# Load libraries
library(dplyr)
library(ggplot2)

# Read employee data
employees <- read.csv("https://raw.githubusercontent.com/crstarbuck/peopleanalytics_book/master/data/employees.csv")

# Create data cube for active employees
smmry_ed_field <- employees %>%
                  dplyr::filter(active == 'Yes') %>%
                  dplyr::count(ed_field)

# Step 1: Build Bar Chart with Defaults
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") 

# Step 2: Remove Legend
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::theme(legend.position = "none")

# Step 3: Assign Colors Strategically
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none")

# Step 4: Add Axis Titles and Margins
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::labs(x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)))

# Step 5: Add Left-Justified Title
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               plot.title = ggplot2::element_text(hjust = 0),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)))

# Step 6: Remove Background
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)))

# Step 7: Remove Axis Ticks
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0)),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

# Step 8: Mute Titles
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

# Step 9: Flip Axes
ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::coord_flip() +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

# Step 10: Sort Data
ggplot2::ggplot(smmry_ed_field, aes(x = reorder(ed_field, n), y = n, fill = as.factor(ed_field))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::coord_flip() +
ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                      "Life Sciences" = "#0070C0", 
                                      "Marketing" = "#BFBFBF", 
                                      "Medical" = "#BFBFBF",
                                      "Other" = "#BFBFBF",
                                      "Technical Degree" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

# Pre/post viz comparison
viz_pre <- ggplot2::ggplot(smmry_ed_field, aes(x = ed_field, y = n, fill = as.factor(ed_field))) +
           ggplot2::geom_bar(stat = "identity") 

viz_post <- ggplot2::ggplot(smmry_ed_field, aes(x = reorder(ed_field, n), y = n, fill = as.factor(ed_field))) +
            ggplot2::geom_bar(stat = "identity") +
            ggplot2::coord_flip() +
            ggplot2::labs(title = 'Life Sciences is the most common education field \npursued by active employees.', x = 'Education Field', y = 'Headcount') +
            ggplot2::scale_fill_manual(values = c("Human Resources" = "#BFBFBF", 
                                                  "Life Sciences" = "#0070C0", 
                                                  "Marketing" = "#BFBFBF", 
                                                  "Medical" = "#BFBFBF",
                                                  "Other" = "#BFBFBF",
                                                  "Technical Degree" = "#BFBFBF")) +
              ggplot2::theme(legend.position = "none",
                             panel.background = ggplot2::element_blank(),
                             axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
                             axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
                             plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
                             axis.ticks.x = ggplot2::element_blank(),
                             axis.ticks.y = ggplot2::element_blank())
  
# Display pre/post visualizations side-by-side
ggpubr::ggarrange(viz_post, viz_pre, ncol = 1, nrow = 2)

```

## Tables

```{r, eval = FALSE}

### Data Prep ###

# Load library
library(dplyr)

# Read employee data
employees <- read.csv("https://raw.githubusercontent.com/crstarbuck/peopleanalytics_book/master/data/employees.csv")

# Append new tenure band column
employees$tenure_band <- dplyr::case_when(
  employees$org_tenure < 1 ~ "Under 1 Year",
  employees$org_tenure < 2.5 ~ "1-2 Years",
  employees$org_tenure < 5.5 ~ "3-5 Years",
  employees$org_tenure <= 10 ~ "6-10 Years",
  TRUE ~ "Over 10 Years"
)

# Store aggregate measures to cube
dept_tenure <- employees %>%
               dplyr::filter(active == 'Yes') %>%
               dplyr::group_by(dept, tenure_band) %>%
               dplyr::summarise(cnt = dplyr::n())

# Specify ordered factor
dept_tenure$tenure_band <- ordered(dept_tenure$tenure_band, levels = c("Under 1 Year", "1-2 Years", "3-5 Years", "6-10 Years", "Over 10 Years"))

# Assign proper case field names
dept_tenure_proper <- dept_tenure %>%
                      rename('Department' = dept,
                             'Tenure' = tenure_band,
                             'Count' = cnt)

```

```{r, eval = FALSE}

### Data Table ###

# Load library
library(DT)

# Format output with datatable
DT::datatable(dept_tenure_proper, rownames = FALSE)

```  

## Heatmaps

```{r, eval = FALSE}

### Data Prep ###

# Load library
library(dplyr)

# Append new tenure band column
employees$tenure_band <- dplyr::case_when(
  employees$org_tenure < 1 ~ "Under 1 Year",
  employees$org_tenure < 2.5 ~ "1-2 Years",
  employees$org_tenure < 5.5 ~ "3-5 Years",
  employees$org_tenure <= 10 ~ "6-10 Years",
  TRUE ~ "Over 10 Years"
)

# Store aggregate measures to cube
dept_tenure <- employees %>%
               dplyr::filter(active == 'Yes') %>%
               dplyr::group_by(dept, tenure_band) %>%
               dplyr::summarise(cnt = dplyr::n())

# Specify ordered factor
dept_tenure$tenure_band <- ordered(dept_tenure$tenure_band, levels = c("Under 1 Year", "1-2 Years", "3-5 Years", "6-10 Years", "Over 10 Years"))

```

```{r, eval = FALSE}

### Heatmap ###

# Load library
library(ggplot2)

ggplot2::ggplot(dept_tenure, aes(x = tenure_band, y = dept, fill = cnt)) +
ggplot2::geom_tile() +
ggplot2::labs(title = 'A large portion of our workforce has between 3 and 10 years\n of company tenure and works within R&D.', x = 'Tenure', y = 'Department') +
ggplot2::guides(fill = guide_legend(title = "Employee Count")) +
ggplot2::scale_fill_continuous(low = "#F2F2F2", high = "#0070C0") +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"))

```

## Scatterplots

```{r, eval = FALSE}

### Data Prep ###

# Subset df to active sales employees
sales <- subset(employees, dept == 'Sales' & active == 'Yes')

# Set quote attainment flag for data viz coloring
sales$quota_flg <- ifelse(sales$ytd_sales >= 150000, 1, 0)

```

```{r, eval = FALSE}

### Scatterplots ###

# Load libraries
library(ggplot2)
require(scales)

# Basic scatterplot
ggplot2::ggplot(sales, aes(x = work_exp, y = ytd_sales, group = quota_flg)) +
ggplot2::geom_point() +
ggplot2::labs(title = 'The relationship between work experience and YTD sales is positive.', x = 'Work Experience', y = 'YTD Sales (USD)') +
ggplot2::scale_y_continuous(labels = scales::comma) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"))

# Scatterplot with preattentive attributes
ggplot2::ggplot(sales, aes(x = work_exp, y = ytd_sales, group = quota_flg)) +
ggplot2::geom_point(aes(color = as.factor(quota_flg))) +
ggplot2::geom_hline(yintercept = 150000, linetype = 'dotted', color = "#0070C0") + 
ggplot2::annotate(geom = "text", x = 2, y = 159000, label = "Sales Quota = $150k", color = "#0070C0", size = 3) +
ggplot2::labs(title = 'Some employees with more work experience have \nalready met the full year sales quota.', x = 'Work Experience', y = 'YTD Sales (USD)') +
ggplot2::scale_color_manual(values = c("0" = "#BFBFBF",
                                       "1" = "#0070C0")) +
ggplot2::scale_y_continuous(labels = scales::comma) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"))

```

## Line Charts

```{r, eval = FALSE}

### Data Prep ###

# Set seed for reproducibility
set.seed(1234)

# Create data
months = 1:24
eng_rt = 5 - runif(1, 2.7, 2.9) + 2.41*months - .41*months^2 + .02*months^3
fin_rt = runif(1, 5, 8) - 6.97 + 15*months - .53*months^2
ppl_rt = 3 - runif(1, 5, 8) - 6.97 + 12*months - .4*months^2
prd_rt = runif(1, 5, 8) - 6.97 + 13*months - .53*months^2

# Combine dimensions and metrics within df
attrition_dat <- data.frame(month = rep(months, 4),
                            dept = c(rep('Engineering', length(months)), 
                                     rep('Finance', length(months)),
                                     rep('People', length(months)),
                                     rep('Product', length(months))),
                            rate = c(eng_rt,
                                     fin_rt,
                                     ppl_rt,
                                     prd_rt))

# Ordered factor for subsequent layering of lines in graph (last value takes the top position)
attrition_dat$dept <- factor(attrition_dat$dept, c("Product", "Finance", "People", "Engineering"))

```

```{r, eval = FALSE}

### Single Series Line Graphs ###

# Load library
library(ggplot2)

ggplot2::ggplot(subset(attrition_dat, dept == 'Engineering'), aes(x = month, y = rate, group = dept)) + 
ggplot2::labs(title = 'Engineering attrition has increased over the last 24 months, \nlargely due to an exponential spike in the last year.', x = 'Month', y = 'Attrition Rate') +
ggplot2::geom_line(color = '#0070C0', size = 1) +
ggplot2::scale_x_continuous(limits = c(0, 25), breaks = seq(0, 24, by = 3)) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```
  
```{r, eval = FALSE}

### Two Series Line Graphs ###

# Load library
library(ggplot2)

ggplot2::ggplot(subset(attrition_dat, dept %in% c('Engineering', 'Product')), aes(x = month, y = rate, color = dept)) + 
ggplot2::labs(title = 'The attrition trends for Engineering and Product \nare negatively correlated over the last year.',
              x = 'Month',
              y = 'Attrition Rate',
              col = 'Department') +
ggplot2::geom_line(size = 1) +
ggplot2::scale_x_continuous(limits = c(0, 27), breaks = seq(0, 24, by = 3)) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'Engineering' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'Engineering', color = "#0070C0", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'Product' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'Product', color = "#808080", size = 4, hjust = 0) +
ggplot2::scale_color_manual(values = c("Engineering" = "#0070C0",
                                       "Product" = "#BFBFBF")) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```
  
```{r, eval = FALSE}

### Multiple Series Line Graphs ###

# Load library
library(ggplot2)

ggplot2::ggplot(attrition_dat, aes(x = month, y = rate, color = dept)) + 
ggplot2::labs(title = 'The attrition trend for Engineering is quite different \nrelative to attrition patterns for other departments.',
              x = 'Month',
              y = 'Attrition Rate',
              col = 'Department') +
ggplot2::geom_line(size = 1) +
ggplot2::scale_x_continuous(limits = c(0, 27), breaks = seq(0, 24, by = 3)) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'Engineering' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'Engineering', color = "#0070C0", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'Product' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'Product', color = "#808080", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'Finance' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'Finance', color = "#808080", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = max(attrition_dat$month) + .5, y = attrition_dat[attrition_dat$dept == 'People' & attrition_dat$month == max(attrition_dat$month), 'rate'], label = 'People', color = "#808080", size = 4, hjust = 0) +
ggplot2::scale_color_manual(values = c("Engineering" = "#0070C0",
                                       "Product" = "#BFBFBF",
                                       "Finance" = "#BFBFBF",
                                       "People" = "#BFBFBF")) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, margin = ggplot2::margin(t = 0, r = 0, b = 20, l = 0), colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```

## Slopegraphs

```{r, eval = FALSE}

### Data Prep ###

# Build data frame with YoY headcount metrics by department
prepost_scores <- data.frame(date = c(rep('Time 1', 2), rep('Time 2', 2)),
                             group = rep(c('Treatment', 'Control'), 2),
                             score = c(10, 13, 55, 16))

```  

```{r, eval = FALSE}

### Slopegraphs ###

# Load library
library(ggplot2)

# Calculate treatment and control group changes for inclusion in annotation
treatment_chg <- subset(prepost_scores, group == 'Treatment' & date == 'Time 2', select = score) - subset(prepost_scores, group == 'Treatment' & date == 'Time 1', select = score)
control_chg <- subset(prepost_scores, group == 'Control' & date == 'Time 2', select = score) - subset(prepost_scores, group == 'Control' & date == 'Time 1', select = score)

ggplot2::ggplot(prepost_scores, aes(x = date, y = score, group = group)) +
ggplot2::geom_line(aes(color = group), size = 2) +
ggplot2::geom_point(aes(color = group), size = 4) +
ggplot2::expand_limits(y = 0) +
ggplot2::annotate(geom = "text", x = 2.1, y = prepost_scores[prepost_scores$group == 'Treatment' & prepost_scores$date == 'Time 2', 'score'] - 2, label = paste0(prepost_scores[prepost_scores$group == 'Treatment' & prepost_scores$date == 'Time 2', 'score'], "% (", ifelse(treatment_chg >= 0, '+', ''), treatment_chg, ")", "\nTreatment Group"), color = "#0070C0", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = 2.1, y = prepost_scores[prepost_scores$group == 'Control' & prepost_scores$date == 'Time 2', 'score'] - 2, label = paste0(prepost_scores[prepost_scores$group == 'Control' & prepost_scores$date == 'Time 2', 'score'], "% (", ifelse(control_chg >= 0, '+', ''), control_chg, ")", "\nControl Group"), color = "#808080", size = 4, hjust = 0) +
ggplot2::labs(title = '          A more favorable change in engagement was observed \n          for the treatment group relative to \n          the control group.', x = 'Observation Period') +
ggplot2::scale_color_manual(values = c("Control" = "#BFBFBF",
                                       "Treatment" = "#0070C0")) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank(),
               axis.text.y = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(colour = "#404040"),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_blank())

```

## Bar Charts
  
```{r, eval = FALSE}

### Data Prep ###

# Set seed for reproducibility
set.seed(1234)

# Generate favorability distributions
fav_pct <- round(runif(7, 20, 45), 0)
neu_pct <- round(runif(7, 20, 45), 0)
unfav_pct <- 100 - fav_pct - neu_pct
scores <- c(fav_pct, neu_pct, unfav_pct)

# Average top box (favorable) score
topbox_avg <- round(mean(fav_pct), 0)

# Build data frame with YoY headcount metrics by department
engagement_scores <- data.frame(dept = rep(c('Engineering', 'Finance', 'Legal', 'Marketing', 'People', 'Product', 'Sales'), 3),
                                favorability = c(rep('Favorable', 7), rep('Neutral', 7), rep('Unfavorable', 7)),
                                pct = scores)

# Rank departments by top box score to support sorting
dept_rank <- engagement_scores %>%
             dplyr::filter(favorability == 'Favorable') %>% 
             dplyr::arrange(desc(pct)) %>% 
             dplyr::mutate(rank = dense_rank(desc(pct))) %>%
             dplyr::select(dept, rank)

# Flag top department records in df to support conditional coloring
engagement_scores$top_score = ifelse(engagement_scores$dept == dept_rank[1, 'dept'], 1, 0)

# Add department rank based on top box scores
engagement_scores <- left_join(engagement_scores, dept_rank, by = "dept")

```  
  
```{r, eval = FALSE}

### Vertical Bar Charts ###

ggplot2::ggplot(subset(engagement_scores, favorability == 'Favorable'), aes(x = reorder(dept, -pct), y = pct, fill = as.factor(top_score))) +
ggplot2::labs(title = 'The People team is leading in department-level engagement.', x = 'Department', y = 'Engagement Score') +
ggplot2::geom_bar(stat = "identity") +
ggplot2::geom_hline(yintercept = topbox_avg, linetype = 'dotted', color = "#404040") + 
ggplot2::annotate(geom = "text", x = 7.1, y = topbox_avg + 1.3, label = paste0("Avg = ", topbox_avg), color = "#404040", size = 3) +
ggplot2::scale_fill_manual(values = c("1" = "#0070C0",
                                      "0" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 0, b = 20, l = 0), colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```

```{r, eval = FALSE}

### Horizontal Bar Charts ###

ggplot2::ggplot(subset(engagement_scores, favorability == 'Favorable'), aes(x = reorder(dept, pct), y = pct, fill = as.factor(top_score))) +
ggplot2::labs(title = 'The People team is leading in department-level engagement.', x = 'Department', y = 'Engagement Score') +
ggplot2::geom_bar(stat = "identity") +
ggplot2::coord_flip() +
ggplot2::geom_hline(yintercept = topbox_avg, linetype = 'dotted', color = "#404040") + 
ggplot2::annotate(geom = "text", x = 1, y = topbox_avg + 2.3, label = paste0("Avg = ", topbox_avg), color = "#404040", size = 3) +
ggplot2::scale_fill_manual(values = c("1" = "#0070C0",
                                      "0" = "#BFBFBF")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 0, b = 20, l = 0), colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```
  
```{r, eval = FALSE}

### Stacked Bar Charts ###

ggplot2::ggplot(engagement_scores, aes(x = reorder(dept, -rank), y = pct, fill = factor(favorability, levels = c("Unfavorable", "Neutral", "Favorable")))) +
ggplot2::labs(title = 'Half of Engineering respondents report unfavorable engagement.', x = 'Department', y = 'Engagement Score') +
ggplot2::guides(fill = guide_legend(title = "Favorability")) +
ggplot2::geom_bar(position = "fill", stat = "identity") +
ggplot2::coord_flip() +
ggplot2::scale_fill_manual(values = c("Favorable" = "#0070C0",
                                      "Neutral" = "#D9D9D9",
                                      "Unfavorable" = "#ED7D31")) +
ggplot2::scale_y_continuous(labels = scales::percent) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 0, b = 20, l = 0), colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```

## Combination Charts

```{r, eval = FALSE}

### Data Prep ###

# Set seed for reproducibility
set.seed(12345)

# Turnover rates
vol_rt <- round(runif(24, 5, 15), 1)
inv_rt <- round(runif(24, 1, 5), 1)
tot_rt <- vol_rt + inv_rt
turnover_dat <- data.frame(month = 1:24,
                           inv_rt = inv_rt,
                           vol_rt = vol_rt,
                           tot_rt = tot_rt)

```

```{r, eval = FALSE}

### Combination Charts ###

# Load library
library(ggplot2)

ggplot2::ggplot(turnover_dat) + 
ggplot2::labs(title = 'The largest share of overall monthly attrition over the 24-month period \nhas consistently been voluntary terminations.',
              x = 'Month',
              y = 'Attrition Rate') +
ggplot2::geom_bar(aes(x = month, y = tot_rt), fill = '#D9D9D9', stat = "identity") +
ggplot2::geom_line(aes(x = month, y = vol_rt), size = 1, color = "#0070C0", group = 1) +
ggplot2::geom_line(aes(x = month, y = inv_rt), size = 1, color = "#808080", group = 1) +
ggplot2::scale_x_continuous(limits = c(0, 27), breaks = seq(0, 24, by = 3)) +
ggplot2::scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, by = 5)) +
ggplot2::annotate(geom = "text", x = max(turnover_dat$month) + .7, y = turnover_dat[turnover_dat$month == max(turnover_dat$month), 'vol_rt'], label = 'Voluntary', color = "#0070C0", size = 4, hjust = 0) +
ggplot2::annotate(geom = "text", x = max(turnover_dat$month) + .7, y = turnover_dat[turnover_dat$month == max(turnover_dat$month), 'inv_rt'], label = 'Involuntary', color = "#808080", size = 4, hjust = 0) +
ggplot2::theme(panel.background = ggplot2::element_blank(),
               legend.position = "none",
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```

## Waterfall Charts

```{r, message = FALSE, warning = FALSE}

### Data Prep ###

# Generate headcount data with id field to define bar order
hc_dat <- data.frame(id = 1:6,
                     event = c("Starting HC", "Hires", "Transfers In", "Transfers Out", "Exits", "Ending HC"),
                     type = c("Headcount", "Growth", "Growth", "Loss", "Loss", "Headcount"),
                     count = c(100, 50, 10, -10, -20, 130),
                     start = NA,
                     end = NA)

# Define start and end values to support waterfall chart
hc_dat$end <- cumsum(hc_dat$count)
hc_dat$end <- c(head(hc_dat$end, -1), 0)
hc_dat$start <- c(0, head(hc_dat$end, -1))

# Swap start/end values for last record (Ending HC)
hc_dat[nrow(hc_dat), "end"] <- hc_dat[nrow(hc_dat), "start"]
hc_dat[nrow(hc_dat), "start"] <- 0

```

```{r, eval = FALSE}

### Waterfall Chart ###

# Load library
library(ggplot2)

ggplot2::ggplot(hc_dat, aes(x = event, fill = type)) +
ggplot2::geom_rect(aes(x = reorder(event, id),
                       xmin = id - 0.45,
                       xmax = id + 0.50,
                       ymin = end,
                       ymax = start)) +
geom_text(aes(id, end, label = ifelse(id %in% c(1,6), end, '')), # Only label start and end HC
              vjust = 1.5) +
ggplot2::labs(title = 'Hires and inbound transfers have outpaced outbound transfers and exits \nin Engineering, leading to a net YTD increase in headcount.',
              x = 'Event',
              y = 'Headcount') +
ggplot2::scale_fill_manual(values = c("Headcount" = "#D9D9D9",
                                      "Growth" = "#0070C0",
                                      "Loss" = "#ED7D31")) +
ggplot2::theme(legend.position = "none",
               panel.background = ggplot2::element_blank(),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0), colour = "#404040"),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(t = 0, r = 10, b = 0, l = 0), colour = "#404040"),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank())

```

## Waffle Charts

```{r, message = FALSE, warning = FALSE}

### Data Prep ###

# Create df with TA funnel metrics
ta_dat <- data.frame(stage = c("Apply", "Phone Screen", "Interview", "Offer Extend", "Offer Accept"),
                     cnt = c(60, 20, 10, 6, 4))

# Set depth of waffle chart (# of y-axis rows)
depth <- 10

# Each observation needs an x and y coordinate, and y needs to be specified first for a waffle chart with horizontal accumulation
waffle_dat <- expand.grid(y = 1:depth,
                          x = seq_len(ceiling(sum(ta_dat$cnt) / depth)))

# Expand the applicant counts into a vector of stage labels
stages <- rep(ta_dat$stage, ta_dat$cnt)

# Integrate stages and fill any extra tiles with NA
waffle_dat$stage <- c(stages, rep(NA, nrow(waffle_dat) - length(stages)))

```

```{r, eval = FALSE}

### Waffle Chart ###

# Load library
library(ggplot2)

ggplot2::ggplot(waffle_dat, aes(x = x, y = y, fill = stage)) + 
ggplot2::labs(title = "We select 10 in every 100 applicants. \nOur offer acceptance rate (OAR) is 40%.") + 
ggplot2::geom_tile(color = "white") +
ggplot2::scale_fill_manual(values = c("Apply" = "#D9D9D9", 
                                      "Phone Screen" = "#BFBFBF", 
                                      "Interview" = "#A6A6A6", 
                                      "Offer Extend" = "#808080",
                                      "Offer Accept" = "#0070C0")) +
ggplot2::scale_y_reverse() +
ggplot2::theme_void() +
ggplot2::theme(legend.title = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(hjust = 0, colour = "#404040"))

```

## Sankey Diagrams

```{r, eval = FALSE}

### Data Prep ###

# Load library
library(dplyr)

# Set seed for reproducibility
set.seed(1234)

# Create nodes df
nodes <- data.frame(name = c('Engineering', 'Finance', 'Legal', 'Marketing', 'People', 'Product', 'Sales', # source
                             'Engineering', 'Finance', 'Legal', 'Marketing', 'People', 'Product', 'Sales')) # destination

# Create links df
links <- expand.grid(source = 0:6, target = 7:13)

# Append employee transfer counts per department pair to links df
links$value <- ifelse(links$source == links$target-7, round(rnorm(1000, 150, 50), 0), round(rnorm(1000, 30, 5), 0))

# Append source department variable for colored connections
links$dept <- dplyr::case_when(
  links$source == 0 ~ "Engineering",
  links$source == 1 ~ "Finance",
  links$source == 2 ~ "Legal",
  links$source == 3 ~ "Marketing",
  links$source == 4 ~ "People",
  links$source == 5 ~ "Product",
  links$source == 6 ~ "Sales",
  TRUE ~ "NA"
)

# Append within/outside department transfer variable for colored connections
links$wiout_dept <- dplyr::case_when(
  (links$source == 0 & links$target == 7) | (links$source == 1 & links$target == 8) | (links$source == 2 & links$target == 9) | (links$source == 3 & links$target == 10) | (links$source == 4 & links$target == 11) | (links$source == 5 & links$target == 12) | (links$source == 6 & links$target == 13) ~ "Within",
  TRUE ~ "Outside"
)

# Append dichotomous product/other indicator to links and nodes data frames
links$prod <- ifelse(links$dept == 'Product', 'Product', 'Other')
nodes$prod <- ifelse(nodes$name == 'Product', 'Product', 'Other')

```

```{r, eval = FALSE}

### Sankey Diagrams ###

# Load library
library(networkD3)

# Sankey diagram 1
networkD3::sankeyNetwork(Links = links,
                         Nodes = nodes,
                         Source = "source", 
                         Target = "target",
                         Value = "value", 
                         NodeID = "name",
                         fontSize = 12, 
                         nodeWidth = 30)

# Sankey diagram 2
networkD3::sankeyNetwork(Links = links,
                         Nodes = nodes,
                         Source = "source", 
                         Target = "target",
                         Value = "value", 
                         NodeID = "name",
                         fontSize = 12, 
                         nodeWidth = 30, 
                         LinkGroup = "dept")

# Sankey diagram 3
networkD3::sankeyNetwork(Links = links,
                         Nodes = nodes,
                         Source = "source", 
                         Target = "target",
                         Value = "value", 
                         NodeID = "name",
                         fontSize = 12, 
                         nodeWidth = 30, 
                         LinkGroup = "wiout_dept")

# Sankey diagram 4
# Define color palette
colorJS <- paste('d3.scaleOrdinal(["#BFBFBF", "#0070C0"])')

networkD3::sankeyNetwork(Links = links,
                         Nodes = nodes,
                         Source = "source", 
                         Target = "target",
                         Value = "value", 
                         NodeID = "name",
                         fontSize = 12, 
                         nodeWidth = 30, 
                         NodeGroup = "prod",
                         LinkGroup = "prod",
                         colourScale = colorJS)

```

## Pie Charts

```{r, EVAL = FALSE}

### Data Prep ###

# Create data cube for gender representation among active employees
smmry_gender <- data.frame(gender = c('Male', 'Female'),
                           cnt = c(732, 501),
                           pct = c(59.4, 40.6))

```

```{r, eval = FALSE}

### Pie Chart ###

# Load library
library(ggplot2)

ggplot2::ggplot(smmry_gender, aes(x = "", y = pct, fill = as.factor(gender))) +
ggplot2::geom_bar(stat = "identity") +
ggplot2::coord_polar("y", start = 0) +
ggplot2::geom_text(aes(label = paste0(pct, "%")), color = ifelse(smmry_gender$gender == 'Male', 'white', 'black'), position = position_stack(vjust = 0.5)) +
ggplot2::labs(title = 'Nearly 60 percent of active employees identify as male.') +
ggplot2::scale_fill_manual(values = c("Female" = "#BFBFBF", 
                                      "Male" = "#0070C0")) +
ggplot2::theme_void() +
ggplot2::theme(legend.title = ggplot2::element_blank(),
               panel.background = ggplot2::element_blank(),
               axis.ticks.x = ggplot2::element_blank(),
               axis.ticks.y = ggplot2::element_blank(),
               plot.title = ggplot2::element_text(colour = "#404040"))

```

