# Foreword {-}

If one were to try and pin down origins of the field of people analytics, I would propose we start in the year 1911 when three events that represent the foundational ingredients to our emerging profession took place. In this year, Fredrick Taylor published his seminal “Principles of Scientific Management”, Charles Finley merged three firms into the Computing-Tabulating-Recording Company (later renamed International Business Machines), and Karl Pearson founded the world’s first university statistics department at the City University of London. Mix the scientific method applied to organizations, scaling data systems, and advanced statistical knowledge in about equal parts, give them a bit over a century to simmer, distill, and age and voila, you have modern people analytics! Readers will find all three of these ingredients mixed with a few more contemporary spices in The Fundamentals of People Analytics.

This book is timely because more and more companies are investing in people analytics as a capability. In my view, this is attributed to three primary forces. First, organizations are simply more complex and in many industries that complexity is increasingly wrapped up in collaboration by employees with scarce skill sets. It is not an accident that the modern rise of people analytics started and has been most prevalent in large tech companies where skill scarcity and collaborative production are high. However, it has become clear that people analytics has much to offer, whether a company is full of software engineers or frontline service workers. This has been highlighted in recent years as the Covid pandemic brought significant labor shortage and reevaluation across a broader range of industries. Even as the pandemic recedes, other macro trends are conspiring to make all sorts of labor scarcer and more valuable. It is fair to say that in many industries, finding and optimizing human resources are already the most difficult constraint firms must solve for. I predict this will become more widespread and acute across the economy, driving continued investment in people analytics as a field. 

Second, data is simply cheaper and more accessible than it has ever been, including data about people and the production process. While any people analytics practitioner will be quick to tell you that the most convenient data are not always the right data, there are so much relevant data available for people analytics that we now have the fortunate problem of how to collect, munge and analyze it at speed and scale. We are only getting more with major progress being made in such core areas as collaboration and skills data. As the data accumulates, it will require analysts and leaders with more sophisticated data skillsets. We are rapidly moving toward a world where some skills in spreadsheets or basic data visualization, while valuable, are no longer adequate for advancing in a people analytics career. We are in desperate need to create higher skilled analysts without having to send everyone back for a PhD or relying on generalized data science programs. I am excited to hand this book to any number of young and mid-career people analysts in my network to provide them a curated and structured guide to efficiently building the most relevant skills on one of the most relevant statistical platforms in R. I hope many Masters of HR programs adopt this text in place of more generalized statistical training they tend to provide today.   

Finally, in my view much of the initial and ongoing investments in people analytics by firms is driven by the normative pressure that comes from requiring the appearance of data-driven decision making. It is simply no longer acceptable as an executive leading any function, including HR, to show up without data and analysis when recommending key decisions – whether it is used or not or whether it is correct or not. This provides a concrete floor to investment in the field of people analytics, even if in many instances it may be performative. However, people analytics also has a high ceiling where the insights we produce can significantly enable decision makers at all levels to create more resilient, innovative, efficient, and humane organizations. To move from performative to effective people analytics is itself a complex technical and organizational task. This book is filled with not only the core technical knowledge, but also much hard-won craft knowledge required to make this leap. I believe readers will find themselves referring to the more conceptual and strategic chapters again and again for their concise but multilayered insights and frameworks to realize the full and growing potential of people analytics. 

Ryan Hammond, PhD

Ryan holds a BS and MS from Cornell’s School of Industrial and Labor Relations and a PhD from the MIT Sloan School of Management. He has founded two early people analytics startups and helped firms from 1,000 to 70,000 employees stand up people analytics capabilities. He has published in top tier journals on subjects such as the link between network collaboration and firm performance as well as gender pay equity in startups. He is currently the Head of Total Rewards and People Analytics at Airtable.